### ISSUE TITLE
Tabs v4 - Active / Inactive backgroundColor not working

### ISSUE THREAD

**Issue by fxhereng** [aksonov/react-native-router-flux#2263] opened 2017-08-18 10:36 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta18
- react-native v0.47.1

### Problem

In the Tabs scene: the props `inactiveBackgroundColor`& `activeBackgroundColor` doesn't change anything to the tab background color, it stays white.

Code:
```javascript
<Router sceneStyle={{backgroundColor:Colors.white}}>
	<Scene key='root'>
		<Scene key='Splash' initial={false} component={Splash} hideNavBar/>
		<Scene key='Login' component={Login} hideNavBar/>
		<Scene key='ChooseInstallation' component={ChooseInstallation} navBar={(props) => this.renderNavigationBar(props, false)}/>
		<Scene key='CreateIcon' component={CreateIcon} navBar={(props) => this.renderNavigationBar(props, false)}/>

		<Scene key='TabBar' tabs showIcon={true} showLabel={true} swipeEnabled={false} lazy={false}
		activeTintColor={Colors.main_color} inactiveTintColor={Colors.black} indicatorStyle={Styles.indicatorStyle}
  		labelStyle={Styles.labelStyle} tabStyle={Styles.tabStyle} iconStyle={Styles.iconStyle} upperCaseLabel={false}
  		inactiveBackgroundColor={Colors.white} activeBackgroundColor={'#dddddd'}
  		initial={true} tabBarPosition={'bottom'} 
  		navBar={(props) => this.renderNavigationBar(props, false, true)}>

			<Scene key='dashboard' title={LocalizedStrings.dashboard} initial={true} icon={TabIcon} iconString={'dashboard'}>
				<Scene key='Dashboard' component={Dashboard} sceneStyle={Styles.sceneWithTabBar}  hideNavBar />
			</Scene>
			<Scene key='real_time' title={LocalizedStrings.real_time} icon={TabIcon} iconString={'realtime'}>
				<Scene key='RealTime' component={Dashboard} sceneStyle={Styles.sceneWithTabBar} hideNavBar />
			</Scene>
			<Scene key='my_consumption' title={LocalizedStrings.my_consumption} icon={TabIcon} iconString={'my_consumption'}>
				<Scene key='MyConsumption' component={Dashboard} sceneStyle={Styles.sceneWithTabBar} hideNavBar />
			</Scene>
			<Scene key='my_objectives' title={LocalizedStrings.my_objectives} icon={TabIcon} iconString={'my_objectives'}>
				<Scene key='MyObjectives' component={Dashboard} sceneStyle={Styles.sceneWithTabBar} hideNavBar />
			</Scene>

		</Scene>

	</Scene>
</Router>
```

Tabs styles:

```javascript
iconStyle: {
	width: 44 * initialScale,
	height: 44 * initialScale
},
tabStyle: {
	alignItems: 'center', 
	justifyContent: 'center',
	paddingHorizontal: 0,
	paddingBottom: 2,
},
labelStyle: {
	fontSize: 12,
	fontFamily: Fonts.light,
	marginTop: -2
},
indicatorStyle: {
	backgroundColor: 'transparent'
}
```

**Comment by aksonov** [comment] 2017-08-21 12:32
Duplicate of https://github.com/react-community/react-navigation/issues/1485

**Comment by aksonov** [comment] 2017-08-23 09:46
Will fix it with workaround found at https://github.com/react-community/react-navigation/issues/504

**Closed** 2017-08-23 09:47 UTC
Labels: help wanted
