### ISSUE TITLE
Call tab nested scene from outer scene

### ISSUE THREAD

**Issue by igorarkhipenko** [aksonov/react-native-router-flux#2079] opened 2017-07-20 16:37 UTC
My router looks like this:
```
<Router createReducer={this.reducerCreate.bind(this)}>
        <Scene key="root">
          <Scene key="auth" type="reset" hideNavBar initial={initial.auth} hideTabBar
            component={Auth} title="Auth"
          />
          <Scene key="main" tabBarComponent={Navigator} hideNavBar tabs initial={initial.main}>
            <Scene key="coaches" tabBarLabel="Coaches"
              type="reset" component={Coaches} title="Coaches"
            />
            <Scene key="dashboard" tabBarLabel="Dashboard"
              component={Dashboard} title="Dashboard" type="reset"
            />
            <Scene key="aboutMe" tabBarLabel="About me"
              component={aboutMe} title="About me" type="reset" 
            />
          </Scene>
          <Scene key="personalInfo" hideTabBar
            component={MyProfile} title="Personal Info"
          />
        </Scene>
      </Router>
```
And the problem is `About me` scene cannot be called from `Personal Info` as well as vise versa case when the call is going from nested scene to outer one because of an error `'There is no route defined for key routeName'`. How can I get rid of this error? Thank you.

**Comment by aksonov** [comment] 2017-07-21 07:31
Duplicate of #2066

**Closed by aksonov** 2017-07-21 07:31 UTC
