### ISSUE TITLE
want to disable drawer 

### ISSUE THREAD

**Issue by d12544** [aksonov/react-native-router-flux#3260] opened 2018-09-12 13:11 UTC
Need to disable drawer open on swiping gesture in some screen in stack navigator
panhandlers and gestureEnabled not working

**Comment by daviscabral** [comment] 2018-09-12 13:47
maybe a typo? `gesturesEnabled` (with an S). Can you confirm it?

**Comment by daviscabral** [comment] 2018-09-12 14:04
Duplicate of #3169.

**Closed by daviscabral** 2018-09-12 14:04 UTC

**Comment by d12544** [comment] 2018-09-12 14:10
GesuturesEnabled* . It was a typo. Not working
