### ISSUE TITLE
when press back button in nested tab router, it will pop out

### ISSUE THREAD

**Issue by JianlongCao** [aksonov/react-native-router-flux#110] opened 2016-01-08 10:37 UTC
After 2.0.2, I noticed back button was attached Actions.pop(), when pressed the back button in nested routers, it will pop out to my login page. Take official example to explain: when tab1_1-> tab1_2, then press back to tab1_1, it will pop to launch page.

**Comment by MITDelian** [comment] 2016-01-13 00:36
I have also been seeing this issue

**Comment by aksonov** [comment] 2016-01-13 13:19
Please check with 2.0.8

**Comment by joelcloralt** [comment] 2016-01-14 01:25
This happens to me with 2.0.9. I was able to reproduce with Example. 

for me, It happens on the second tab and not the first one.

![react-native-router-flux-bug110](https://cloud.githubusercontent.com/assets/881780/12313220/0bdd41b2-baa9-11e5-8366-d30f182852c9.gif)

**Comment by JianlongCao** [comment] 2016-01-14 02:58
Tested on 2.0.8, 2.0.9, not work for me.
same with @joelcloralt , happened on second tab

**Comment by aksonov** [comment] 2016-01-14 09:13
I can't reproduce this issue with latest version (2.0.9), could you post exact Example code?

**Comment by joelcloralt** [comment] 2016-01-14 09:16
yep
```
  <Router hideNavBar={true} >
  <Schema name="modal" sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
  <Schema name="default" sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
  <Schema name="withoutAnimation"/>
  <Schema name="tab" type="switch" icon={TabIcon} />

  <Route name="register" component={Register} title="Register"/>
  <Route name="home" component={Home} title="Replace" type="replace"/>
  <Route name="login" schema="modal">
    <Router name="loginRouter">
        <Route name="loginModal" component={Login} title="Login" schema="modal"/>
        <Route name="loginModal2" hideNavBar={true} component={Login2} title="Login2"/>
    </Router>
  </Route>
  <Route name="register2" component={Register} title="Register2"  schema="withoutAnimation"/>
  <Route name="tabbar">
    <Router footer={TabBar} showNavigationBar={false}>
      <Route name="tab1" schema="tab" title="Tab #1" >
          <Router onPop={()=>{console.log("onPop is called!"); return true} }>
              <Route name="tab1_1" component={TabView} title="Tab #1_1" />
              <Route name="tab1_2" component={TabView} title="Tab #1_2" />
              <Route name="tab1_3" component={TabView} title="Tab #1_3" />
          </Router>
      </Route>
      <Route name="tab2" schema="tab" title="Tab #2" >
        <Router onPop={()=>{console.log("onPop is called!"); return true} }>
            <Route name="tab2_1" component={TabView} title="Tab #2_1" />
            <Route name="tab2_2" component={TabView} title="Tab #2_2" />
            <Route name="tab2_3" component={TabView} title="Tab #2_3" />
        </Router>
      </Route>
      <Route name="tab3" schema="tab" title="Tab #3" component={TabView} />
      <Route name="tab4" schema="tab" title="Tab #4" component={TabView} />
      <Route name="tab5" schema="tab" title="Tab #5" component={TabView} />
    </Router>
  </Route>
  <Route name="launch" header={Header} component={Launch} wrapRouter={true} title="Launch" hideNavBar={true} initial={true}/>
</Router>
```

**Comment by aksonov** [comment] 2016-01-14 09:18
Also i need to modify TabView, right? I've used something like this, but my Back button for Tab2_2 always point me to Tab2_1. Are you sure you are using 2.0.9 (demo uses 2.0.6 by default now) ?

**Comment by joelcloralt** [comment] 2016-01-14 09:22
I saw that and updated my package.json
` "react-native-router-flux": "^2.0.9"`

Yeah TabView demo only has a back button if the name of the tab is tab1 
```
{this.props.name === "tab1_1" && ....
```

I tried to modify it and noticed the name of tab2 changed to an underscore?

```
{this.props.name === "_tab2_1" &&
                <Button onPress={Actions.tab2_2}>next screen for tab2_1</Button>
                }
``` 
It was the only way to display the `next` button when browsing tab2 but the action points to `tab2_2` which is the right name.

**Comment by JianlongCao** [comment] 2016-01-14 10:43
Tested example on 2.0.9, there is an underscore of tab2 name...
![511c29f1e4b41924b8d50f34e4dadd4c](https://cloud.githubusercontent.com/assets/11714158/12322333/595d7b6a-baee-11e5-810d-79953281c379.gif)

**Comment by MITDelian** [comment] 2016-01-14 23:08
I dug into this a bit today without much success

**Comment by joelcloralt** [comment] 2016-01-15 01:18
:( for some reason `onPop()` is not being called on that second tab's back button. You can see that in the gif I posted with the console.log.

**Comment by joelcloralt** [comment] 2016-01-17 08:47
Any luck here? I haven't been able to figure it out either. I did notice that on the second tab, when calling the action to push to the next route, it actually triggers `onJump()`.

So the same route structure is triggering `push()` on tab1 and `jump()` on tab2.

**Comment by aksonov** [comment] 2016-01-25 14:41
Please check with latest 2.1.3 version

**Comment by joelcloralt** [comment] 2016-01-25 23:39
@aksonov It works for me. Thanks for fixing this!

**Comment by apaquino** [comment] 2016-01-26 02:02
@aksonov works great for me.  Thanks!

**Comment by JianlongCao** [comment] 2016-01-26 03:52
@aksonov Thanks for fixing this issue! It works for me!
But after changing 2.0.1 to 2.1.3, I found componentWillDidMount will be called every time when props updated, any issue opened for this?
my Code :
```
componentDidMount() {
		console.log("componentDidMount")
		const {actions,user} = this.props;
		actions.getDevices(user);
	}
	componentWillReceiveProps(nextProps) {
		if(this.mount) {
			console.log("componentWillReceiveProps")
		}
	}

	componentWillUnmount() {
		this.mount = false
		console.log("componentWillUnmount")
	}

```

<img width="885" alt="2016-01-26 11 50 04" src="https://cloud.githubusercontent.com/assets/11714158/12572125/0e768068-c423-11e5-8aa1-de8008aa5e97.png">

**Comment by aksonov** [comment] 2016-01-26 15:41
It is interesting, could you do more debug and check when the component is unmount  (stack trace)?

**Comment by aksonov** [comment] 2016-02-05 13:58
I'm closing this ticket, open new one for unmounting with more details

**Closed by aksonov** 2016-02-05 13:58 UTC
