### ISSUE TITLE
setState warning when calling a new route with type reset from componentDidMount

### ISSUE THREAD

**Issue by reyalpsirc** [aksonov/react-native-router-flux#498] opened 2016-04-11 11:38 UTC
### Version
- react-native-router-flux v3.2.8
- react-native v0.22.2

### Expected behaviour
Go from a SplashScreen page to the Home page without setState warnings

### Actual behaviour
It reset's the stack but also generates the warning 3 times.
If I go to the Home page without using `reset` (so a normal push is done), it works well.

<img src="https://cloud.githubusercontent.com/assets/5243311/14425537/dc8ff81a-ffdf-11e5-9347-29545a0fda33.png" width="200">

### Steps to reproduce

- Setup the main js file with the following router data:
```
    <Router>
        <Scene key="root">
            <Scene key="splashscreen" component={Splashscreen} initial={true} hideNavBar={true}/>
            <Scene key="home" component={Home}/>
        </Scene>
    </Router>
```
- Create the splashscreen component with the following code:
```
    export default class Splashscreen extends Component {
        componentDidMount(){
            Actions.home({type: "reset"});
        }
        render() {
            return (
                <View></View>
            );
        }
    }
```
- Create a home component with dummy render.

### Extra info

* If the Splashscreen code uses a `setTimeout` function for calling `Actions.home({type: "reset"});`, then it works fine.
* This happens to me while developing a react-native app with Parse server (running on localhost) once checking for an existing logged user on startup.

**Comment by aksonov** [comment] 2016-04-11 12:10
Duplicate of #472 ?

**Closed** 2016-04-11 12:10 UTC

**Comment by reyalpsirc** [comment] 2016-04-11 12:37
Ah yes, it is. I searched on the issues but seems that I did not search enough...

**Comment by epas1117** [comment] 2017-04-11 22:21
Sorry I didn't understood, the solution is to add a timeout setTimeout(()=> { Actions.dashboard(); },0);
