### ISSUE TITLE
Unable to run tests with Mocha 

### ISSUE THREAD

**Issue by sathyakumarseshachalam** [aksonov/react-native-router-flux#694] opened 2016-05-17 15:33 UTC
### Version
- react-native-router-flux 3.22.23
- react-native v0.22.0
- mocha 2.4.5

### Expected behaviour
Running test using mocha. 
```
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "mocha --require react-native-mock/mock.js --compilers js:babel-core/register --recursive test/*.js"
  },
```

### Actual behaviour
Get an error like 
```
/Users/sseshac/src/personal/app/mytest/node_modules/react-native-router-flux/index.js:1
(function (exports, require, module, __filename, __dirname) { import Actions from './src/Actions';
                                                              ^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
```

**Comment by cridenour** [comment] 2016-05-17 23:12
Duplicate of #628 - feel free to continue conversations there if this is a blocker for you.

**Closed by cridenour** 2016-05-17 23:12 UTC
