### ISSUE TITLE
currentScene is not showing the currently mounted screens key

### ISSUE THREAD

**Issue by SourceCipher** [aksonov/react-native-router-flux#3165] opened 2018-08-10 09:00 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.40
- react-native 0.55.4

### Expected behaviour

If opening the screen with the key 'main', currentScene should show the main screens key

### Actual behaviour

If the screen opens with the key 'main' it should show this key in currentScene, but it shows the previous screens key which main was mounted from

**Comment by aksonov** [comment] 2018-08-10 09:41
@SourceCipher Could you reproduce this issue with Example project? The main difference between current RNRF version and older is that currentScene is set AFTER component is mounted/rendered. So for custom navbars you have to read currentScene from actual `navigation.state` (because it is passed before rendering), not `Actions.currentScene`

**Comment by aksonov** [comment] 2018-08-10 09:42
You may also check `ReduxExample`, how it renders 'current scene' (as `name` prop)

**Comment by SourceCipher** [comment] 2018-08-10 11:14
@aksonov  I am using mobx but I dont think adding with observables is a good idea. I will try using navigation.state even tho not really sure how to implement it :/ But using `Actions.currentScene` on componentDidMount is still showing the wrong scene tho

**Comment by aksonov** [comment] 2018-08-10 12:43
For mobx it is even easier (we are using it) - just create simple mobx store `navStore` and with one observable `scene` and `setScene` action, then pass `onStateChange` param to Router:

`<Router onStateChange={() => navStore.setScene(Actions.currentScene)}>...</Router>`

and then you can observe `navStore` from your components and use `navStore.scene`

**Comment by SourceCipher** [comment] 2018-08-10 12:49
@aksonov  oh I see.. I think I can do that with the mobx the same way as well

**Comment by SourceCipher** [comment] 2018-08-10 14:42
@aksonov  your solution worked after I used this with Mobx. Well done

**Comment by daviscabral** [comment] 2018-08-18 17:42
Thank you @SourceCipher for letting us know that the solution provided worked. Closing this one.

**Closed by daviscabral** 2018-08-18 17:42 UTC
Labels: question

**Comment by MasoudShah** [comment] 2020-03-08 21:11
If you implement onEnter event in the scene, the currentScene updates correctly.
