### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'route.routeName')

### ISSUE THREAD

**Issue by ihor** [aksonov/react-native-router-flux#2718] opened 2017-12-19 09:05 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux ^4.0.0-beta.24 (v3 is not supported)
- react-native v0.50.1

### Actual behavior
<img width="316" alt="screen shot 2017-12-19 at 10 01 30" src="https://user-images.githubusercontent.com/490943/34148941-adce0d96-e4a3-11e7-94ea-76ef67356573.png">

The problem is caused by react-navigation v1.0.0-beta.22: [TypeError: undefined is not an object (evaluating 'route.routeName')](https://github.com/react-community/react-navigation/issues/3153)

Can we release a version with the react-navigation version freezed to v1.0.0-beta.21? beta.22 seems to be too buggy, it's having other issues:
- [v1.0.0-beta.22 tabBarIcon does not work](https://github.com/react-community/react-navigation/issues/3155)
- [Resetting navigation state on v1.0.0-beta.22](https://github.com/react-community/react-navigation/issues/3149)

**Comment by rohitgoyal** [comment] 2017-12-19 11:44
I got the same issue with this code

```
export default class Screens extends React.Component {
  render() {
    return <Router>
      <Scene key="root">
        {/* <Scene key="register" component={Register} title="Register"/> */}
        <Scene key="drawer" drawer contentComponent={SideMenu} >
          <Scene key="main">
            <Scene key="home" component={Home} hideNavBar={true}/>
          </Scene>
        </Scene>
      </Scene>
    </Router>
  }
}
```

**Comment by Anandks1993** [comment] 2017-12-19 12:11
I getting the same issue with the following code
```<Router
                titleStyle={{ color: '#FFFFFF' }}
                navigationBarStyle={{
                    backgroundColor: '#2FA5FF',
                }}
                sceneStyle={{ backgroundColor: '#F5FCFF' }}
                backAndroidHandler={this.onBackPress}>
                <Scene key="root">
                    <Drawer
                        title="Menu Options"
                        key="drawer"
                        contentComponent={DrawerContent}
                        drawerWidth={250}
                        drawerImage={MenuButton}
                    >
                        <Scene
                            headerTintColor="#FFFFFF"
                            key="Home"
                            initial
                            title="Home"
                            component={Home} />
                        <Scene
                            headerTintColor="#FFFFFF"
                            key="pairedDevices"
                            title="Paired Devices"
                            component={PairedDevices} />
                        <Scene
                            headerTintColor="#FFFFFF"
                            key="chart"
                            title="Chart"
                            component={TimeSeriesLineChartScreen} />
                        <Scene
                            headerTintColor="#FFFFFF"
                            key="blemanager"
                            title="BLE Manager"
                            component={BLEManager} />
                    </Drawer>
                </Scene>
            </Router>

But it was working 2 hours before, I installed `react-navigation` and then I uninstalled immediately, After that I was stuck with this issue.

**Comment by Shariaty** [comment] 2017-12-19 12:20
I have the same issue here , downgrade to react-navigation v1.0.0-beta.21 solved the problem for now

**Comment by Anandks1993** [comment] 2017-12-19 12:31
@Shariaty How did you downgrade `react-navigation` ? Because it is installed as dependency for `react-native-router-flux` right ?

**Comment by Shariaty** [comment] 2017-12-19 12:43
replace the node_modules with one of my older projects that has the react-navigation beta.21 and  router flux "^4.0.0-beta.24",  it is a temporary fix.

**Comment by Anandks1993** [comment] 2017-12-19 12:47
Okay

**Comment by shubham81407** [comment] 2017-12-19 13:00
+1

**Comment by sonaye** [comment] 2017-12-19 14:48
Adding
```javascript
drawerOpenRoute: 'DrawerOpen',
drawerCloseRoute: 'DrawerClose',
drawerToggleRoute: 'DrawerToggle'
```
to the drawer configs fixed the issue for me.

**Comment by outaTiME** [comment] 2017-12-19 17:37
Any update?

**Comment by aksonov** [comment] 2017-12-19 17:42
Check latest master, I locked rn version

**Comment by sonaye** [comment] 2017-12-19 17:43
https://github.com/react-community/react-navigation/issues/3148#issuecomment-352778884

**Comment by padmanabanSampath** [comment] 2017-12-19 18:15
@Balpi thankyou for referencing, i just did it and worked

**Comment by carlosalber24** [comment] 2017-12-20 04:26
Running `npm install git+https://github.com/aksonov/react-native-router-flux.git#37c6553` should work temporarily for you.

**Comment by shubham81407** [comment] 2017-12-20 04:50
I have the same issue with this code:-
react-native-router-flux: 4.0.0-beta.22
react-native: 0.49.3
```
<Router
    backAndroidHandler={() => Actions.pop()}
    sceneStyle={styles.sceneStyle}
  >
    <Scene key="root">
      <Scene
        key="scene1"
        component={Scene1}
        title="Scene 1"
        navigationBarStyle={styles.navigationBarStyle}
        navBarButtonColor={styles.navBarButtonColor}
        titleStyle={styles.titleStyle}
        initial
      />
      <Drawer
        hideNavBar
        key="dashboard"
        drawerImage={Images.menuIcon}
        contentComponent={Navigation}
        drawerWidth={styles.drawerWidth}
      >
        <Scene
          key="dashboard"
          component={Dashboard}
          title={strings.dashboard}
          navigationBarStyle={styles.navigationBarStyle}
          navBarButtonColor={styles.navBarButtonColor}
          titleStyle={styles.titleStyle}
          renderRightButton={renderNotificationButton}
        />
      </Drawer>
    </Scene>
  </Router>

```

**Comment by Anandks1993** [comment] 2017-12-20 05:41
@shubham81407 Did you check what version of `react-navigation` is installed ? Now it should work as the version is locked to `react-navigation@1.0.0-beta.21`.

**Comment by shubham81407** [comment] 2017-12-20 06:08
@Anandks1993 I have react-navigation@1.0.0-beta.22 version in package-lock.json

**Comment by Anandks1993** [comment] 2017-12-20 06:10
@shubham81407 Downgrade to `react-navigation@1.0.0-beta.21` or again install `react-native-router-flux` It will solve the issue.

**Comment by shubham81407** [comment] 2017-12-20 06:12
@Anandks1993 Can you tell me why this issue is coming in react-navigation@1.0.0-beta.22?

**Comment by Anandks1993** [comment] 2017-12-20 06:16
@shubham81407 I don't know, May be some kind of bug :neutral_face:

**Comment by shubham81407** [comment] 2017-12-20 06:17
@Anandks1993 thanks for the solution.

**Comment by gopaldevra** [comment] 2017-12-20 06:20
Same issue, and the  same [library](https://www.npmjs.com/package/react-native-router-flux) is flagged failed on the npm website.

**Comment by ihor** [comment] 2017-12-20 08:54
@shubham81407 how is it possible? react-navigation@1.0.0-beta.22 was released yesterday.

**Comment by Shariaty** [comment] 2017-12-21 06:30
The error still exist when installing a new fresh router-flux or run npm install !!?
how should i install my other packages !!
my other package after installation dose not recognize react-native link command , and it says I should run npm install , after that link works but router flux and my drawer crash.

**Comment by ihor** [comment] 2017-12-21 12:25
@Shariaty did you try to you the following dependency?
```
"react-native-router-flux": "git+https://github.com/aksonov/react-native-router-flux.git"
```

**Comment by CptFabulouso** [comment] 2017-12-22 13:34
In my case it was caused by drawer. I found [this issue](https://github.com/react-community/react-navigation/issues/3148) in react-navigation that solved it.
So now my drawer component looks like this 
```
<Drawer 
	key='drawer' 
	contentComponent={NavigationDrawer} 
	drawerWidth = {0.8*Metrics.screenWidth}
	//following props added to fix the issue
	drawerOpenRoute = 'DrawerOpen'
	drawerCloseRoute = 'DrawerClose'
	drawerToggleRoute = 'DrawerToggle'
>
```

maybe it will help someone

**Comment by ducnhat** [comment] 2017-12-28 03:41
@ihor 
I found this solution https://github.com/react-navigation/react-navigation/issues/3148#issuecomment-352778884.

**Comment by aksonov** [comment] 2018-01-04 13:13
It was breaking change for latest RNav beta.22. Should be fixed with latest RNRF beta.26

**Closed by aksonov** 2018-01-04 13:13 UTC

**Comment by mjstelly** [comment] 2018-06-15 19:00
I'm not sure what changed between January and now, but this issue arose again. Running the latest repo `example` with `"react-native-router-flux": "4.0.0-beta.26"` and `"react-navigation": "1.5.8"`. From the main screen select "Go to Tabbar Page". The app crashes with the error listed in the title. I didn't know if I should have created a new issue or simply extend this one. I chose the latter, obviously.

**Comment by aksonov** [comment] 2018-06-16 06:42
You must use latest version of RNRF

**Comment by mjstelly** [comment] 2018-06-16 12:07
Your reply begs the question: When will 4.x be stabilized for production? Hitting a moving target while trying to get an app to market is risky business.
