### ISSUE TITLE
Question: how stable is v4?

### ISSUE THREAD

**Issue by ivanquirino** [aksonov/react-native-router-flux#2774] opened 2018-01-10 03:53 UTC
We are starting a new app and plan to use v4, since it's in beta, how stable is it?

**Comment by todorone** [comment] 2018-01-10 08:37
I use it in production, it performs pretty good, while all basic features do work, some features don't work as expected...

**Comment by Blapi** [comment] 2018-01-10 10:55
Check #2001, comments are helpful and will give you an overall idea.

imo, v4 is really fine, better than the v3, more complete and more fluid, I'm really happy to use this library for my Android app !

Closing this because it's kind of a duplicate of #2001

**Closed by Blapi** 2018-01-10 10:55 UTC

**Comment by ivanquirino** [comment] 2018-01-10 22:43
thanks!
