### ISSUE TITLE
Multiple routers in an application

### ISSUE THREAD

**Issue by zhouhao27** [aksonov/react-native-router-flux#513] opened 2016-04-12 10:22 UTC
The structure of my project is:

```
root -- launch(initial) -->
                         |--- login   ---> home --- posts (initial) --->  
                         |--- register                                 |--- new post
                                                                       |--- post details
```

I want to separate to two routers, one in my app.js, the other in home.js. 

**app.js:**

```
export default class App extends React.Component {
  render() {
    return (
      <Router>
        <Scene key="root" hideNavBar={true}>
          <Scene key="launch" component={Launch} title="Launch" initial={true} />
          <Scene key="login" component={Login} />
          <Scene key="register" component={Register} />
          <Scene key="home" component={Home} />
        </Scene>
      </Router>
    )
  }
}
```

**home.js:**

```
export default class Home extends React.Component {
  render() {
    return (
      <Router>
        <Scene key="home" hideNavBar={false}>
          <Scene key="posts" component={Posts} title="Posts" initial={true}  onLeft={()=>Actions.login()} leftTitle="Logout"/>
        </Scene>
      </Router>
    )
  }
}

```

It works well except that I don't know how to return to **login**. I got the error:

> missed route data for key=login

Any idea? Thanks.

**Comment by aksonov** [comment] 2016-04-12 10:23
Sorry, it is not intended usage of the component (v3 version)

**Comment by aksonov** [comment] 2016-04-12 14:25
Duplicate of #353

**Closed by aksonov** 2016-04-12 14:25 UTC

**Comment by luco** [comment] 2017-01-12 11:29
@aksonov I think there should have a method to control multiple routers. In e.g., I have two routers, one for my navigation, other for sidebar drawer. I can't communicate each other, I get the same `missed route data for key=home` as @zhouhao27 does.
