### ISSUE TITLE
deep linking - error

### ISSUE THREAD

**Issue by mounlion** [aksonov/react-native-router-flux#2787] opened 2018-01-11 09:47 UTC
### Version
Tell us which versions you are using: 
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-router-flux": "4.0.0-beta.27"

### Expected behaviour

Open scene

### Actual behaviour

![simulator screen shot - iphone 6 - 2018-01-11 at 12 45 17](https://user-images.githubusercontent.com/17071211/34818961-6d9ac174-f6cd-11e7-8673-7ae836feb0e4.png)

**Comment by Blapi** [comment] 2018-01-11 09:54
Show some code ???

**Comment by mounlion** [comment] 2018-01-11 09:55
```
<Provider store={store}>
                <RouterWithRedux uriPrefix={'google.ru'}>
                    <Lightbox>
                        <Scene key="root" hideNavBar hideTabBar>
                            <Scene key='Institution' component={Institution} path={"/institution/:id/"} />
                        </Scene>
                        <Scene key="SpinnerLightbox" component={SpinnerLightbox} />
                    </Lightbox>
                </RouterWithRedux>
            </Provider>
```

**Comment by Blapi** [comment] 2018-01-11 10:05
What's the behaviour when you use Router instead of RouterWithRedux ?

**Comment by mounlion** [comment] 2018-01-11 10:06
```
const RouterWithRedux = connect()(Router);
```

**Comment by Blapi** [comment] 2018-01-11 10:30
That was no what I was not meaning but anyway, can you have more logs about this bug? deep-linking is supposed to work so I'm not sure the issue is with the library

**Comment by aksonov** [comment] 2018-01-11 10:39
@mounlion prefix is not correct at all, please check deep linking examples

**Comment by EvianZhow** [comment] 2018-02-08 10:25
@aksonov I've encountered this issue. Since @mounlion doesn't provide any useful information or its scenario, I tell mine. 

My iOS app was registered with two URL schema, one called `myApp://` and another called `stripeOrAnythingElsePayment://`, in `App` component, I registered `myApp` prefix and it handles all the routing logic, that's fine. But then coming to payment, my app jump out into third-party to finish its payment process. After success, third-party will call `stripeOrAnythingElsePayment://` to return to my own App, and at that time, app crashed due to this issue. 

Simple to reproduce, just create a project with two different URL schema and register `App` with one, then open another using `xcrun simctl openurl booted "ANOTHER_URL://`. 

Hope it helps.

**Comment by EvianZhow** [comment] 2018-02-08 10:30
@Blapi Please have a glimpse at what I've explained.

**Comment by Blapi** [comment] 2018-02-10 16:08
@EvianZhow I'm developing on Android and I'm using react-native-deep-linking on my end, I'm sorry

**Comment by Blapi** [comment] 2018-08-01 09:45
@EvianZhow what's the status there?

**Comment by EvianZhow** [comment] 2018-08-01 09:49
@Blapi Fixed in latest version

**Closed** 2018-08-01 09:59 UTC
