### ISSUE TITLE
rightTitle / leftTitle  

### ISSUE THREAD

**Issue by cadudragon** [aksonov/react-native-router-flux#2019] opened 2017-07-12 15:17 UTC
rightTitle and leftTitle  doesnt show in (Android Emulator)

I've tried in my project than in the repository example:

```
 <Scene key="loginModal" component={Login} title="Login" rightTitle="Right" onLeft={Actions.pop}/>
              <Scene
                key="loginModal2"
                component={Login2}
                title="Login2"
                panHandlers={null}
                duration={1}
              />
```

**Comment by aksonov** [comment] 2017-07-12 15:43
Where is onRight? I don't see any leftTitle

**Comment by cadudragon** [comment] 2017-07-12 15:58
rightTitle only works with onRight?
I've changed my project and still don wokrs.

Let me show my cenario.
This is my Router Component:

```
        <Router>
            <Scene key="root" modal hideNavBar>
                <Scene
                    key="auth"
                    initial title="Please Login"
                    onRight={() => console.log('Right button')}
                    rightTitle="Right"
                >
                    <Scene key="login" component={LoginForm} />
                </Scene>
                <Scene key="main">
                    <Scene
                        renderRightButton={() => <Text onPress={() => { console.log('Add'); }}>Add</Text>}
                        key="employeeList"
                        component={EmployeeList}
                        title="Employeessss"
                        onRight={() => alert('Right button')}
                    />
                </Scene>
            </Scene>
        </Router>
```

I'm trying to use rightTitle in the  key Scene and doesnt show:
![image](https://user-images.githubusercontent.com/10310408/28126852-1dcc3008-6701-11e7-944f-bf3656a9b3ba.png)

Am I doing somenthing wrong?

For now I'm using renderRightButton instead of rightTitle.

**Comment by aksonov** [comment] 2017-07-12 16:01
Could you try PR #2015 ?

**Comment by cadudragon** [comment] 2017-07-12 16:52
I'm still newbie with git and npm, but I think I've done right:

npm install aksonov/react-native-router-flux#pull/2015/head
My dependencies look like this:
![image](https://user-images.githubusercontent.com/10310408/28129243-02305902-6709-11e7-9b8f-2abca787d2ae.png)



After rerun the rightTitle still not appearing

**Comment by aksonov** [comment] 2017-07-12 16:58
I can't reproduce. Please check Example from that PR, I've just committed rightTitle for Login Page and see it normally.

If you see it but don't see within your project, fork Example and try to reproduce it with Example.

**Comment by aksonov** [comment] 2017-07-13 06:00
Should work with v4 beta.8

**Comment by parachute-dev** [comment] 2017-07-16 22:38
Still seem to have the same issue - no text appearing - tried rightTitle & leftTitle (using onLeft & onRight too). Currently using ^4.0.0-beta.11

This is with the android emulator on Windows. 

  "dependencies": {
    "firebase": "^4.1.3",
    "mobx": "^3.2.1",
    "mobx-react": "^4.2.2",
    "prop-types": "^15.5.10",
    "react": "16.0.0-alpha.12",
    "react-native": "0.46.3",
    "react-native-router-flux": "^4.0.0-beta.11",
    "react-navigation": "^1.0.0-beta.11",
    "react-redux": "^5.0.5",
    "redux": "^3.7.2",
    "redux-thunk": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "20.0.3",
    "babel-preset-react-native": "2.1.0",
    "eslint-config-rallycoding": "^3.2.0",
    "jest": "20.0.4",
    "react-test-renderer": "16.0.0-alpha.12"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by aksonov** [comment] 2017-07-17 06:49
Could you reproduce it with Example?

**Comment by parachute-dev** [comment] 2017-07-17 08:03
Hi there - yes of course, thanks for the response - as below.
     

   <Router>
            <Scene key="modal" modal hideNavBar>
                <Scene key="root" hideNavBar hideTabBar>
                    <Scene key="auth">
                        <Scene
                            key="login"
                            component={LoginForm}
                            leftTitle="show"
                            onLeft={() => console.log('left')}
                            title="Please Login"
                        />
                    </Scene>
                    <Scene key="main">
                        <Scene
                            leftTitle="Cancel"
                            onLeft={Actions.pop}
                            key="employeeList"
                            rightTitle="Add"
                            onRight={() => console.log('right')}
                            component={EmployeeList}
                            title="Employees"
                        />
                    </Scene>
                </Scene>
            </Scene>
        </Router>
![desktop screenshot](https://user-images.githubusercontent.com/7774740/28259561-c9f7e838-6ace-11e7-8a1e-af8cca58ad0c.png)

**Comment by aksonov** [comment] 2017-07-17 08:11
I mean Example project included into this github. Please clone and modify to reproduce the issue.

**Comment by parachute-dev** [comment] 2017-07-17 08:29
Hey - sorry - have done so now. Still not seeing what I expect on tab1_1 It should show a right title? 

renderRightButton does work however on tab2_1

![desktop screenshot](https://user-images.githubusercontent.com/7774740/28260290-3eabf2fc-6ad2-11e7-9e40-ecf4c9f68ffe.png)

**Comment by aksonov** [comment] 2017-07-17 08:31
Could you check iOS? Looks like different behaviour for iOS/Android again...

**Comment by aksonov** [comment] 2017-07-17 08:33
@diegocouto Do you have the same missed rightTitle on Android for Tab#1_1 ?

**Comment by diegocouto** [comment] 2017-07-17 10:56
@aksonov I do! On Tab#2_1 the right text is displayed, but not the Tab#1_1 button. It's the same issue with positioning that we faced with the back button. I'm already working on a PR.

**Comment by parachute-dev** [comment] 2017-07-17 11:13
@diegocouto Thanks - also noticed that the alignment isn't in the centre for the header - not sure if there's another flag to change this in the API?

**Comment by diegocouto** [comment] 2017-07-17 11:25
@parachute-dev The title is center aligned on iOS only, probably to comply to the [material design guidelines](https://material.io/guidelines/layout/structure.html#structure-app-bar).

When defining your scene, you can use `titleStyle` attribute to define new styles to the scene title. 😃

**Comment by parachute-dev** [comment] 2017-07-17 11:37
Thanks!

[image: Parachute] <http://www.thisisparachute.com/> *David R. Bova *-
*Technical
Director at Parachute*

*Address:* 4 Lansdowne Crescent, Glasgow G20 6NQ
*Tel:* 0141 357 4556 | *Mobile:* 07514 645179
david@thisisparachute.com | http://www.thisisparachute.com
<http://thisisparachute.com/>

[image: Twitter] <http://twitter.com/thisisparachute>[image: Facebook]
<http://www.facebook.com/thisisparachute>[image: Pinterest]
<http://pinterest.com/thisisparachute>
*Confidentiality Note: *This email may contain confidential and/or private
information. If you received this email in error please delete and notify
sender.

**Comment by cadudragon** [comment] 2017-07-17 12:36
v4 beta.8 also not showing the output of right/leftTitle.

**Comment by aksonov** [comment] 2017-07-17 17:20
@cadudragon Please try latest master

**Closed** 2017-07-19 20:04 UTC

**Comment by OrianeInMoon** [comment] 2017-08-01 09:33
on 4.0.0-beta.15:
`leftTitle` is only displayed when no `onLeft` function is provided.

**Comment by aksonov** [comment] 2017-08-01 09:35
Have you checked 4.0.0-beta.14?

**Comment by OrianeInMoon** [comment] 2017-08-01 09:36
The same occured using 4.0.0-beta.14.

In fact, it only works when using `onLeft={Actions.pop}`, not when using `onLeft={Actions.mypage}`

**Comment by aksonov** [comment] 2017-08-01 09:48
It means actions is not generated yet i.e. Null value

**Comment by OrianeInMoon** [comment] 2017-08-01 09:51
So why I can see  the wanted action using `console.log(Actions)` before the Router declaration !?
