### ISSUE TITLE
when touch to Android Back Button, nothing happens !

### ISSUE THREAD

**Issue by duyhungp** [aksonov/react-native-router-flux#2546] opened 2017-10-25 14:53 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.20
- react-native v0.47.2

### Expected behaviour
At home screen and android device, when touch to Android Back Button, app will be exist

### Actual behaviour
when touch to Android Back Button, nothing happens !

```javascript
<Router createReducer={reducerCreate}>
  <Modal transitionConfig={() => ({ screenInterpolator: CardStackStyleInterpolator.forFadeFromBottomAndroid })}>
    <Stack hideNavBar>
      <Drawer headerMode='none' contentComponent={Sidebar}>
        <Scene initial key='home' component={HomeScreen}/>
      </Drawer>
    </Stack>
    <Scene key='search' component={SearchScreen} title='Tìm kiếm' hideNavBar />
    <Scene key='item' component={ItemScreen} hideNavBar />
    <Stack key='room' hideNavBar>
      <Drawer headerMode='none' drawerPosition='right' contentComponent={ChatBoxSettingScreen}>
        <Scene key='roomChild' component={RoomScreen} />
      </Drawer>
    </Stack>
    <Scene key='createRoom' component={CreateRoomScreen} hideNavBar />
    <Scene key='webView' component={WebViewScreen} />
  </Modal>
</Router>
```

**Comment by daviscabral** [comment] 2017-10-25 21:11
Do you have any `BackHandler.addEventListener` in your app that might be affecting it?

**Comment by Maxitk** [comment] 2017-11-10 09:06
I have the same problem,how can I solve?
I have checked all my codes,there are no backHandler at all.

**Comment by yangningBU** [comment] 2017-11-12 09:23
I'm having the same problem as well. No custom handler set. I do believe it started happening when once I added a nested <Scene>, but I will try to attach a reproducible package.

**Comment by yangningBU** [comment] 2017-11-12 09:28
I believe this is a dupe of #2540

**Comment by aksonov** [comment] 2018-01-05 08:40
I just checked Example, hardware back works well on Android.

**Closed by aksonov** 2018-01-05 08:40 UTC
