### ISSUE TITLE
Deep linking does not work properly

### ISSUE THREAD

**Issue by GmaMontero** [aksonov/react-native-router-flux#2297] opened 2017-08-28 18:11 UTC
### Version
Tell us which versions you are using: 
- react-native-router-flux 4.0.0-beta.19
- react-native 0.47.2

### Expected behaviour
When I receive a deep link from a browser I want to open a specific scene.

### Actual behaviour
When I receive the deep link, it opens the scene but also mounts the initial one.

-------> Router.js
class FlowRouter extends React.Component {
  constructor(props) {
      super(props);
      this.handleOpenURL = this.handleOpenURL.bind(this);
  }

  componentDidMount() {
    Linking.getInitialURL().then(url => this.handleOpenURL({ url })).catch(console.error);
  }

  handleOpenURL(event) {
      if (event.url) {
        var path = event.url.split("http://www.cerveapp.com.ar")
        crossroads.parse(path[1]);
      }
  }

  onBackPress(){
    if (Actions.state.index === 0) {
      return false;
    }
    Actions.pop();
    return true;
  }

  render() {
    crossroads.addRoute('/id/{place_id}', place_id => Actions.PlaceDetail({ place_id }));

    return <Router backAndroidHandler={this.onBackPress}>
      <Scene key="root">
        <Scene key="Loader" component={Loader} hideNavBar={true} />
        <Scene key="Map" component={Map} hideNavBar={true} type="replace" />
        <Scene key="PlaceDetail" component={PlaceDetail} title="Detalle de cerveceria"/>
      </Scene>
    </Router>
  }
}

-------> Loader.js
class Loader extends React.Component {
  componentDidMount(){
    this.searchPosition();
  }

  searchPosition(){
    let navParams = this.props.navigation.state.params;
    let _that = this;
    GeoLocation.getPosition({
      highAccuracy: false,
      cbSucess : function(position){
            Actions.Map({
              position: position,
              place_id : navParams.place_id
            });
      }
    });
  }

  render() {
    return (
      <View style={styles.loader.mainContainer}>
      </View>
    );
  }
}

Without deep link the flow is: Loader -> GET CURRENT POSITION -> Map -> WHEN CLICK MARKER -> PlaceDetail

With the deep link the idea is: PlaceDetail

But the loading is mounted, which causes the map to be displayed. Taking out the detailPlace.

Could you please help me?

![screenshot_20170825-145915](https://user-images.githubusercontent.com/3322355/29786510-ca61fa30-8c01-11e7-92d5-a9346896e7dc.png)

![screenshot_20170825-145952](https://user-images.githubusercontent.com/3322355/29786535-e534886e-8c01-11e7-89c8-0995984c72b9.png)

**Comment by aksonov** [comment] 2017-08-29 08:38
Deep linking is not supported yet. Check #2148

**Comment by aksonov** [comment] 2017-08-29 08:39
Duplicate of #2137

**Closed by aksonov** 2017-08-29 08:39 UTC
