### ISSUE TITLE
Actions.popTo('home',{'name':'1'})cannot trigger componentWillReceiveProps

### ISSUE THREAD

**Issue by jeffy7** [aksonov/react-native-router-flux#2669] opened 2017-12-01 09:34 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24
- react-native v0.50.3

### Expected behaviour
1.home->A->B ,B call Actions.popTo('home',{'name':'1'}),at scene home ,method componentWillReceiveProps will work 

### Actual behaviour
1.home->A->B ,B call Actions.popTo('home',{'name':'1'}),at scene home ,method componentWillReceiveProps doesn't work 
2.but at B  call  Actions.pop({'name':'1'}) ,it pop to A, componentWillReceiveProps work,
3.at B sence,Actions.pop({popNum:2}),it pop to A ,doesn't popTo home.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.I from scene home to scene A,then sceneA to scene B  
2.at scene B I call Actions.popTo('home',{'name':'1'})
3.it back to scene home ,but did't call componentWillReceiveProps

maybe i used wrong method,Ineed home->A->B  ,and ,Back to home ,and at scene home i can do something .

thx!

**Comment by luco** [comment] 2018-01-02 20:47
+1

**Comment by aksonov** [comment] 2018-01-04 14:34
It is not yet supported, PR is welcome!

**Comment by aksonov** [comment] 2018-01-04 15:12
Duplicate of #2621

**Closed by aksonov** 2018-01-04 15:12 UTC
Labels: enhancement, help wanted
