### ISSUE TITLE
Menu Burger Error. 

### ISSUE THREAD

**Issue by oseifrimpong** [aksonov/react-native-router-flux#2394] opened 2017-09-17 19:34 UTC
Having this error. I have browsed for the solution but still can't find it. Any help out here? I have done the following: 

- Restarted packager and Emulator. 
- Restarted my Mac
- Deleted and reinstalled node_modules.

### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.47.0

![erro](https://user-images.githubusercontent.com/3536601/30524172-35a30346-9c21-11e7-9287-96e213fbdf04.jpeg)

**Comment by mindhivefi** [comment] 2017-09-21 17:33
The problem is that package is missing image files. I managed to make it work just be copyining the images -folder with its contents from here to its place in node_modules/react-native-router-flux/ -folder.

@aksonov, I guess this will be fixed, if you can make a package with /images/ -folder included.

**Comment by mcabs3** [comment] 2017-09-23 14:14
Can you try reinstalling the package? I just tried it in one of my projects and I see the images folder just fine?

**Comment by mindhivefi** [comment] 2017-09-28 14:37
Didn't help. But I still can use it when I copy the folder. So this is something that I can cope with.

**Comment by mtford90** [comment] 2017-11-28 07:30
This is quite annoying - i've had to create a `post_install` script that copies `images` into the `node_modules` folder as everytime I install a new package, this breaks.

**Comment by Juan1ll0** [comment] 2017-12-21 15:06
Could be something like this [https://github.com/aksonov/react-native-router-flux/issues/2567](url) ?

**Comment by aksonov** [comment] 2018-01-05 10:26
Sorry, but I can't reproduce it. Just installed clean RNRF Example project and it works without problems.

**Closed by aksonov** 2018-01-05 10:26 UTC
