### ISSUE TITLE
Swipe broken in example

### ISSUE THREAD

**Issue by xanderlu** [aksonov/react-native-router-flux#206] opened 2016-02-13 01:47 UTC
This commit seemed like it was supposed to fix the swipe issue: https://github.com/aksonov/react-native-router-flux/commit/a34fe3777a5e218cfb445867daa66caa576d79a6. However, in the example, swiping is still broken. It has the same exact issue reported in https://github.com/aksonov/react-native-router-flux/issues/197 and https://github.com/aksonov/react-native-router-flux/issues/176

The only way I could get it to work is to add `Actions.currentRouter = this.router` to https://github.com/xanderlu/react-native-router-flux/commit/dd660e8090d09b2bbcd5d2857c535c1cda44f01d. I can use this for now, but I'm wondering if there's a way to do it without modifying the library. And whether or not the solution above is going to pose any problems. `currentRouter` probably gets assigned twice since `BEFORE_FOCUS` is dispatched every time the route changes, so I'm wondering if there's a better way to do this.

**Comment by lynndylanhurley** [comment] 2016-02-13 19:32
Hi @xanderlu - #204 was meant only to dispatch the `BEFORE_FOCUS` and `AFTER_FOCUS` events. It doesn't fix the `No current route is set` bug, or any other bugs.

I haven't experienced the swiping issue - what are the steps to reproduce?

**Comment by xanderlu** [comment] 2016-02-14 21:30
Ah, my bad. I thought it was supposed to fix that bug since the issue that I field for it was duped to the bug that #204 closed. More details can be found on #197, but here are the general repro steps:

1. Clone the repository

1. Change entry for react-native-router-flux for package.json to point to current version. I just set it to `file:../`

1. run `npm install`

1. launch the project in the iOS Simulator

1. click on `Go to TabBar Page'

1. swipe back to the main page

1. try clicking on any of the pages.

**Comment by xanderlu** [comment] 2016-02-14 21:31
I think the fix is to set Actions.currentRouter, and it does seem to work (see https://github.com/xanderlu/react-native-router-flux/commit/dd660e8090d09b2bbcd5d2857c535c1cda44f01d), but I'm not sure if I'm putting it in the optimal spot or if doing so will cause other issues..

**Comment by Elyx0** [comment] 2016-02-17 03:40
Experienced this today too. Had to change schema to the Android version even on ios so gestures pop would not be present in the FloatFromBottom

**Comment by aksonov** [comment] 2016-02-19 08:07
Duplicate of #197, is there any PR to fix it?

**Closed by aksonov** 2016-02-19 08:07 UTC

**Comment by xanderlu** [comment] 2016-02-20 23:41
#231 should fix it.

**Comment by ms88privat** [comment] 2016-04-09 16:04
@xanderlu thanks for this PR. But this is not working for me. If I swipeToGoBack, and do `Actions.pop()`, it does not route.. Only `BEFORE_ROUTER_POP` and `AFTER_ROUTER_POP` are getting dispatched.

It does work when I `pop()` a second time. If I don't use swipeToGoBack it is working on the first time like expected.

Could you please help me here? I'm using the 2x Version, so this should matter

**Comment by ms88privat** [comment] 2016-04-09 16:24
![image](https://cloud.githubusercontent.com/assets/6705521/14404837/313462d6-fe80-11e5-85fe-7d0e0ac91d3d.png)

the stack is not updating for every swipeToGoBack :/
