### ISSUE TITLE
Unexpected behavior: Drawer displays a navbar with a back button

### ISSUE THREAD

**Issue by aelallam** [aksonov/react-native-router-flux#2736] opened 2017-12-23 10:14 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v^4.0.0-beta.24
- react-native v0.50.3

### Expected behaviour

When I open the drawer, the drawer will not have a navbar.

### Actual behaviour

Once I open the drawer, the drawer has a navbar with a back button.

### Steps to reproduce
The following is the hierarchy of my router: 
```
<Scene key="main">
        <Scene key="splash" hideNavBar={true} component={Splash} initial />

        <Scene key="eng" drawer drawerWidth={250} contentComponent={MenuContent}>
          <Scene key="home" component={Home} title="Home" />
          <Scene key="company" component={Companies} title="Companies" />
        </Scene>
</Scene>
```
A main scene that  holds two scenes. The scene with key="eng" has a drawer. 
**Note: when the drawer is in the key=main scene it worked as expected (with non nested children inside).**

**Comment by Blapi** [comment] 2017-12-23 21:54
Did you try with `hideNavBar` in your Drawer ?

(it is recommended that your first Scene has the key "root")

**Comment by aelallam** [comment] 2017-12-24 08:06
I added hideNavBar in the scene  with the drawer (key = eng) however this hides the navbar of all the children. Why is it treating the drawer as a scene?

**Comment by aksonov** [comment] 2018-01-04 12:12
@aelallam Could you check Example project?

**Comment by aksonov** [comment] 2018-01-04 13:25
I can't reproduce it with Example, closing for now.

**Closed by aksonov** 2018-01-04 13:25 UTC

**Comment by aelallam** [comment] 2018-01-06 06:43
I fixed this issue by adding a `hideNavBar={false}` for each child screen.
