### ISSUE TITLE
Tabs flag for swiping not working

### ISSUE THREAD

**Issue by SourceCipher** [aksonov/react-native-router-flux#3163] opened 2018-08-08 21:48 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux 4.0.0-beta.40
- react-native 0.55.4

### Expected behaviour

When the flag swipeEnabled is set to true, user should be able to swipe through the tabs

I have my tabs layout like this:

```
 <Tabs key="tabbar" tabs={true} swipeEnabled={true} showLabel={false} hideNavBar style={{ marginTop: -50 }} type={ActionConst.RESET}>
   <Scene key="contacts" component={Contacts} hideNavBar type={ActionConst.RESET}/>
   <Scene key="chats" component={Chats} hideNavBar initial={true} type={ActionConst.RESET}/>
   <Scene key="profile" component={Profile} hideNavBar type={ActionConst.RESET}/>
 </Tabs>
```

The same goes for not be able to hide the tab Bar Component which is at the bottom by default.

### Actual behaviour

Swiping is not available. Only works switching via bottom nav

**Comment by SourceCipher** [comment] 2018-08-08 21:55
Ok I just fixed by doing this "cheat". To make tabs to swipe, make sure you have set `tabBarPosition='top'`. 

To disable the **tabBarComponent** you have to return null as a component. To do so just do `tabBarComponent={() => null}`

By adding these 2 to a Tabs component it will make your tabs swiping without even setting `swipeEnabled={true}`

**Comment by aksonov** [comment] 2018-08-10 08:00
It seems to be removed from React Navigation 2.x. Should we return it back? ;)
https://github.com/react-navigation/react-navigation/issues/4146

**Comment by SourceCipher** [comment] 2018-08-10 08:09
@aksonov I have been trying to make my app with this navigation to work perfectly but its struggling to do the job and its a shame as its a very good library, easy to use as well. 

But after the latest update a lot of features not working anymore. I implemented my custom header in navBar I think which works fine, but checking the current screens in different components is a mess as it will never return the current screen but the one is being mounted from. And the back button on the android is not working as well.

**Comment by aksonov** [comment] 2018-08-10 08:11
We are using our library on production, too pity that it doesn't work for you. You may create the ticket for every issue you have with reproducible fork of Example project. For Android issues please ask @daviscabral

**Comment by aksonov** [comment] 2018-08-10 08:29
Btw, `Actions.currentScene` really could be inaccurate now (because RNRF no longer maintains own navigation state), I will try to fix it now.

**Comment by SourceCipher** [comment] 2018-08-10 08:36
@aksonov Thanks for your help! Because I am using a custom header, all the logic goes there as well and without keeping a track in the header what screen is mounted is pretty hard to handle all the logic.

**Comment by aksonov** [comment] 2018-08-10 08:50
@SourceCipher Could you create new issue for this problem? It seems hard to fix, `onNavigationStateChange` is called _AFTER_ react components are mounted.

**Comment by daviscabral** [comment] 2018-08-10 15:10
I am also strugling with the onNavigateStateChange life cycle. Any chance for us to implement a side life cycle instead of route state? So people can subscribe to it instead.

**Comment by aksonov** [comment] 2018-08-10 15:12
Could you clarify?

**Comment by daviscabral** [comment] 2018-08-10 15:48
Of course. I meant about adding something like a `onNavigateStateWillChange` on our side - to allow some kind of preparation for the next component.

**Comment by aksonov** [comment] 2018-08-10 15:51
Any idea how? RNRF doesn’t manage state anymore (maybe 5.0 release will do, but it is a lot of work).

**Comment by daviscabral** [comment] 2018-08-10 16:02
I was actually thinking in something unconnected to state - to really move away from this idea a bit. 

Have you take a look at `NavigationEvents`? https://reactnavigation.org/docs/en/navigation-events.html#docsNav

Maybe allow users to connect whatever they want (with the new context API - I am noticing that it might be possible to postpone use of redux or mobx a bit in some cases).

**Comment by aksonov** [comment] 2018-08-10 16:04
Users can use `NavigationEvents` freely already.

**Comment by daviscabral** [comment] 2018-08-10 16:05
Yeah - that's true. I am overcomplicating with this idea - just shooting to see if we could end with something around it - but you are correct - let's keep things simple. ;-)

**Comment by SourceCipher** [comment] 2018-08-10 18:00
@aksonov  I implemented the current screen logic and all works fine.. The problem is still the long delay between the card press and the screen mount. It takes a while for the screen to appear for some reason

**Comment by daviscabral** [comment] 2018-09-02 23:48
@sourcecipher could you provide an example where I am able to see it? 

It seems that the lifecycle of the components now are all mounted at once right after loading the app.

**Comment by SourceCipher** [comment] 2018-09-03 12:39
@daviscabral Which should make screens switching super fast, but thats not the case. I have a custom header component and there is a profile icon. when you press it it simply calls this `onPress={() => Actions.profile()}`. Now once I press it, its not switched instantly the same way it would do If I press on the tabs

**Comment by daviscabral** [comment] 2018-09-03 15:42
Can you try last code from master? There was some updates related to `reset` and other stuff that might help on that.

**Comment by SourceCipher** [comment] 2018-09-03 17:05
@daviscabral  you mean v4.0.0?

**Comment by daviscabral** [comment] 2018-09-03 17:44
No - master as in master branch: 

```
yarn add aksonov/react-native-router-flux
```

**Comment by aksonov** [comment] 2018-09-05 12:00
`legacy` attribute must be used to make old behavior. However I don't see tab bar, maybe @daviscabral could help

**Comment by daviscabral** [comment] 2018-09-06 04:58
It was not intended :(

**Comment by aksonov** [comment] 2018-09-13 06:11
@daviscabral Could you try to fix legacy tabbar before new release?

**Comment by daviscabral** [comment] 2018-09-13 06:58
Sure - also fixing #3258 before it.

**Comment by daviscabral** [comment] 2018-09-13 15:00
@aksonov fixed on #3265.

**Closed** 2018-09-13 15:04 UTC
Labels: discussion

**Comment by rajkishoreandia** [comment] 2018-10-06 18:39
Can anybody help me how to refresh or reload the back stack scenes in react-native-router-flux?
Thanks

**Comment by wguillen3** [comment] 2019-04-27 13:44
` <Router>
          <Tabs key="root" tabs={true} legacy={true} swipeEnabled={true} tabBarPosition={'bottom'}>
            <Scene hideNavBar key="login" component={Login} title="Login"/>
            <Scene hideNavBar key="register" component={Register} title="Register"/>
            <Scene hideNavBar key="home" component={Home}/>
          </Tabs>
        </Router>`

legacy={true}
this works for me

**Comment by wguillen3** [comment] 2019-04-27 13:46
<Router>
       <Tabs key="root" tabs={true} legacy={true} swipeEnabled={true} tabBarPosition={'bottom'}>
            <Scene hideNavBar key="login" component={Login} title="Login"/>
            <Scene hideNavBar key="register" component={Register} title="Register"/>
            <Scene hideNavBar key="home" component={Home}/>
        </Tabs>
</Router>

legacy={true}
this works for me

**Comment by zomars** [comment] 2019-09-23 19:56
Some additional info, I can confirm this is working as described. But if you use a custom `tabBarComponent` and try to use `Action.jump(key)` in it, it won't trigger the sliding animation.
