### ISSUE TITLE
TabIcon would load twice when rendering every time

### ISSUE THREAD

**Issue by cicada1993** [aksonov/react-native-router-flux#2796] opened 2018-01-15 04:34 UTC
### Version
Tell us which versions you are using: 

    **"react": "16.0.0",**
    **"react-native": "0.51.0",**
    **"react-native-router-flux": "^4.0.0-beta.27",**
    **"react-native-swiper": "^1.5.13",**
    **"react-navigation": "^1.0.0-beta.23",**
    **"react-redux": "^5.0.6",**
    **"redux": "^3.7.2",**
 

### Logs of Proof
the page has 5 tabs but the tabicon render doubly 
![image](https://user-images.githubusercontent.com/31173307/34928188-d4954f3a-f9f6-11e7-8760-5e13c14ca646.png)

###Code Snippet
**TabIcon**
```
export const TabIcon = (param) => {
    console.log(param)
    const {focused, title, navigation: {state: {key}}} = param
    return getIcon(focused, key, title)
}
```
**Router**
```
const reducerCreate = params => {
    const defaultReducer = new Reducer(params)
    return (state, action) => {
        console.log('ACTION:', action)
        return defaultReducer(state, action)
    }
}

```
```
const DemoApp = () => {
    return (
        <Router createReducer={reducerCreate}>
            <Scene key="root">
                {/* Tab Container */}
                <Scene
                    key="tabbar" tabs={true} tabBarPosition="bottom"
                    navigationBarStyle={styles.navigationBar}
                    titleStyle={styles.title}
                    tabBarStyle={styles.tabbarContainer}
                    showLabel={false}>

                    <Scene icon={TabIcon} key={SCENE_HOME.key} component={HomeProvider} title={SCENE_HOME.title}/>

                    <Scene icon={TabIcon} key={SCENE_CLASSIFY.key} component={ClassifyPage} title={SCENE_CLASSIFY.title}/>

                    <Scene icon={TabIcon} key={SCENE_FOLLOW.key} component={FollowPage} title={SCENE_FOLLOW.title}/>

                    <Scene icon={TabIcon} key={SCENE_YUBA.key} component={YubaPage} title={SCENE_YUBA.title}/>

                    <Scene icon={TabIcon} key={SCENE_ME.key} component={MePage} title={SCENE_ME.title}/>
                </Scene>
            </Scene>
        </Router>
    )

}

```

**Comment by jaypeng2015** [comment] 2018-03-22 01:59
Same here. This was discussed in  https://github.com/aksonov/react-native-router-flux/issues/2576 but I think there are some misleading comments there.

**Comment by aksonov** [comment] 2018-08-08 15:14
Duplicate of #2576

**Closed by aksonov** 2018-08-08 15:14 UTC
