### ISSUE TITLE
How to get the Routing stack?

### ISSUE THREAD

**Issue by sds311** [aksonov/react-native-router-flux#2118] opened 2017-07-26 15:30 UTC
I want register the <Router>'s backAndroidHandler event , like Following Code:

<Router backAndroidHandler={
(navProps)=>{ console.log(navProps.navigationState); }
} />,

but , this function Not a bit of navProps , why not injection this parameters, so, how I get the navigationState in backAndroidHandler function,  how use the backAndroidHandler function at the difference Scenes show  to run the defference logic code?

**Comment by aksonov** [comment] 2017-07-27 18:54
duplicate of #2122

**Closed by aksonov** 2017-07-27 18:54 UTC
