### ISSUE TITLE
Don't allow to swipe back on Navigator

### ISSUE THREAD

**Issue by philolo1** [aksonov/react-native-router-flux#631] opened 2016-05-04 13:34 UTC
### Version
Tell us which versions you are using (react native 0.22 is required for v3!): 

- react-native-router-flux v3.2.6
- react-native v0.22.2

HI i have two scenes. I push the second scene with Action.myScene. In this second scene i have some swipe ability, this ability makes problem with being able to swipe back by the navigator, is it possible to disable to pop the navigator by swiping?

**Comment by sf577** [comment] 2016-05-04 13:43
duplicate of #359

**Closed** 2016-05-04 16:52 UTC
Labels: duplicate

**Comment by philolo1** [comment] 2016-05-05 02:22
It's not working for me, i thought I have to use <Scene panHandlers={null} />

**Comment by philolo1** [comment] 2016-05-05 02:24
I installed @3.22.23  @sf577  and i tried <Scene panHandlers={null} /> but i am still able to swipe back.

**Comment by sf577** [comment] 2016-05-05 08:23
What version of React Native are you using? panHandlers={null} is only supported in 0.24+ I believe.

**Comment by philolo1** [comment] 2016-05-05 10:00
ok that explains it. Could you update your package.json in the example,
this is pointing to react 22.2.

2016-05-05 17:23 GMT+09:00 sf577 <notifications@github.com>:

**Comment by sf577** [comment] 2016-05-05 10:56
yeah... its not quite that simple unfortunately. #525  #557
