### ISSUE TITLE
Question: Redux/Flux support

### ISSUE THREAD

**Issue by tristangodfrey** [aksonov/react-native-router-flux#121] opened 2016-01-13 11:41 UTC
From the documentation:

> All route actions can be hooked by adding handlers for Actions.onPush, Actions.onReplace, Actions.onPop in your store(s).

Could someone with a little more experience with this component maybe post a short example of how to implement this? And is there something like `Actions.route` to catch all router transitions?

The main reason I want to know this is because I'm trying to set up a custom navigation bar component on a router, and I get the title of the current route by calling `props.router.currentRoute.title`. Obviously when the route changes I need a way to pass this new state to my component.

Thanks in advance.

**Comment by aksonov** [comment] 2016-01-13 13:05
Just pass onPush/onPop param to Router with your handler

**Comment by aksonov** [comment] 2016-01-13 13:06
Looks like duplicate of #56

**Closed by aksonov** 2016-01-13 13:06 UTC

**Comment by tristangodfrey** [comment] 2016-01-13 16:38
Thanks for your reply @aksonov , for some reason `onPush` isn't firing when I change route via a tab bar.

Quick example:

```
<Route
  name="home"
  type="replace"
  >
  <Router
    footer={TabBar}
    daqweqwe={{
      title: "Sign out",
    }}
    onPush={onPush} //Not firing on tab change
    showNavigationBar={false}
    header={NavigationBar}
    style={styles.tabBar}>
    <Route
      name="dashboard"
      schema="tab"
      iconName="material|home"
      initial={true}
      title="Home"
      component={Screens.Dashboard} />
    <Route
      name="history"
      schema="tab"
      iconName="material|time-restore"
      title="History"
      component={Screens.History} />
    <Route
      name="about"
      iconName="material|help-outline"
      schema="tab"
      title="About"
      component={Screens.About} />
    <Route
      name="contact"
      schema="tab"
      title="Contact"
      iconName="material|email"
      component={Screens.Contact} />
    <Route
      name="info"
      schema="tab"
      title="Info"
      iconName="material|info-outline"
      component={Screens.Info} />
  </Router>
</Route>
```

Any idea why this is happening?

**Comment by aksonov** [comment] 2016-01-13 17:07
It is switch action, so it should be onSwitch

Pavel.

**Comment by paulbao** [comment] 2016-02-17 05:14
@aksonov onSwitch is not fired either, I've tested it on Example project.
`
                 <Route name="tabbar" onSwitch={()=>{
                  console.log('onSwitch')
                }}>
`

**Comment by willmcclellan** [comment] 2016-03-01 02:08
FYI the handler is actually called `onJump` and should be attached to the parent router. I think the documentation is either out of date or mis-referencing `onJump` with `onSwitch`
