### ISSUE TITLE
Error: There is no route defined for key undefined. 

### ISSUE THREAD

**Issue by arghya95** [aksonov/react-native-router-flux#3259] opened 2018-09-12 12:56 UTC
### Version
4.0.1

- react-native-router-flux v4.0.1
- react v16.2.0
- react-native v0.52.3

### Expected behaviour

Navigating between tabs without any error

### Actual behaviour

Error: There is no route defined for key undefined.
Must be one of: 'home','map','restaurant','news'

Here is my Code.

```
<Router>
<Scene key='root'>
          <Scene key="Login" title="Login Page" hideNavBar={true}  component={LoginPage} navigationBarStyle={{backgroundColor:'#005696'}} titleStyle={{color:'white'}} headerTintColor='#fff'/>
            <Tabs hideNavBar={true} key="tabs" lazy={true} tabs={true} animationEnabled={false} tabStyle={{borderWidth: 1, borderColor: 'rgba(0, 86, 150, 0.3)'}} activeBackgroundColor={'#005696'} labelStyle={{color: '#fff', paddingBottom: 12, fontSize: 15}} tabBarPosition="bottom" tabBarStyle={styles.tabBar}>

                <Scene key="home" initial={true}  hideNavBar={true} title="Home" component={HomeScreen} navigationBarStyle={{backgroundColor:'#005696'}} titleStyle={{color:'white'}} style={{color:'red'}} headerTintColor='#fff'/>

                <Scene key="map" hideNavBar={true} title="Map" component={MapScreen} navigationBarStyle={{backgroundColor:'#005696',}} titleStyle={{color:'white'}} headerTintColor='#fff'/>

                <Scene key="restaurant"  hideNavBar={true} title="Restaurant" component={RestaurantScreen} navigationBarStyle={{backgroundColor:'#005696'}} titleStyle={{color:'white'}} headerTintColor='#fff'/>

                <Scene key="news"  hideNavBar={true} title="News" component={NewsScreen} navigationBarStyle={{backgroundColor:'#005696'}} titleStyle={{color:'white'}} headerTintColor='#fff'/>

            </Tabs>

  </Scene>    
        </Router>
```

and I am using 
`Actions.replace('restaurant',{ mapdata: newArr});`
in Map Tab.

**Comment by daviscabral** [comment] 2018-09-12 14:05
Duplicate of #3258.

**Closed by daviscabral** 2018-09-12 14:05 UTC

**Comment by arghya95** [comment] 2018-09-13 12:27
Is there any solution for now to naviagte between tabs with props?

**Comment by daviscabral** [comment] 2018-09-14 01:57
@arghya95 while I check a permanent solution - could you try:

```js
Actions.replace('restaurant',{ mapdata: newArr}, 'tabs');
```

**Comment by danielsGit** [comment] 2019-04-01 16:12
Is this issue is resolved? I am having the same problem with version 4.0.6

**Comment by roots-ai** [comment] 2019-11-05 19:02
Any updates here?
