### ISSUE TITLE
Tab bar Badge count from redux store

### ISSUE THREAD

**Issue by haabnaseem** [aksonov/react-native-router-flux#944] opened 2016-07-20 07:46 UTC
How to show badge count from redux store ? i have implemented a counter in redux which updates the views, but tabbar badge icon is not updated. initial state of counter is 0, but when i click increment it does not get updated from tabbar badge count.

**Comment by cridenour** [comment] 2016-07-20 15:01
Closing as duplicate of #887 - there are some pointers there, feel free to continue the discussion though.

**Closed by cridenour** 2016-07-20 15:01 UTC
