### ISSUE TITLE
Drawer button and title alignment in Navbar v4

### ISSUE THREAD

**Issue by Shubham-Sinha** [aksonov/react-native-router-flux#2107] opened 2017-07-25 07:14 UTC
I followed the example code and my Routes.js file looks like below:
```
const Routes = () => (
   <Router createReducer={reducerCreate} getSceneStyle={getSceneStyle}>
      <Scene key="drawer" drawer contentComponent={NavigationDrawer}>
        <Scene key="root">
          <Scene key="Home" component={HomeScreen} title="Home" titleStyle={styles.container} initial hideNavBar></Scene>
          <Scene key="Login" component={LoginScreen} title="Login" hideNavBar></Scene>
          <Scene key="Register" back component={RegisterScreen} title="Register"></Scene>
          <Scene key="A" component={ComponentA} hideNavBar></Scene>
          <Scene key="B" component={ComponentB} title="Title B"></Scene>
        </Scene>
      </Scene>
    </Router>
)
```
Doing this I can use swipe gesture to open side menu drawer but 'Burger' image isn't available on the Navbar. Also the title of the Scene is left aligned. 
I need help in :
1. Implementing burger menu.
2. Aligning the title to center

**Comment by aksonov** [comment] 2017-07-25 07:18
Duplicate of #2092 ?

**Closed by aksonov** 2017-07-25 07:18 UTC
