### ISSUE TITLE
V4 Redux usage

### ISSUE THREAD

**Issue by ismailbaskin** [aksonov/react-native-router-flux#2619] opened 2017-11-13 21:17 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.23
- react-native v0.49.5

How can I implement redux for v4 ? 
https://github.com/aksonov/react-native-router-flux/blob/master/docs/v3/REDUX_FLUX.md#step-1

**Comment by aksonov** [comment] 2017-11-15 10:26
Duplicate of #2115

**Closed by aksonov** 2017-11-15 10:26 UTC
