### ISSUE TITLE
V4 Documentation

### ISSUE THREAD

**Issue by GuillaumeMunsch** [aksonov/react-native-router-flux#2322] opened 2017-09-01 12:37 UTC
Hi.

I'm wondering if there is already somewhere (because I couldn't find any) complete documentation of the v4. I guess not since it still is in beta but I've been trying to migrate from my v3 to the v4 and I just couldn't find out how.
My current routing is quite complex, with a lot of scenes and right now it's kind of a maze so I'm looking to simply restart my routing from a clean sheet with the new version (v4) but I couldn't find any guide of complete documentation on it.

Do I have to know how `react-navigation` works to use RNRF's v4 or there is a complete documentation on the way that'll be released in the next few weeks/months ?

Thanks in advance :)

**Comment by aksonov** [comment] 2017-09-01 12:39
Just check API for v4: https://github.com/aksonov/react-native-router-flux/blob/master/docs/API.md
You don't need to know anything about `react-navigation`.

**Comment by GuillaumeMunsch** [comment] 2017-09-01 12:44
I found that one actually but it is currently missing some parts right ?

I can't find anything on the `Modal`, the `Stack` and other available imports (`Lightbox`, `Drawer`, `Reducer`, ...).
Also some props are currently missing right ? Like, as used in the `Example` project, the `Router` can have props like `createReducer`. Are these on the way ?

By the way, thanks for your quick answer :)

**Comment by aksonov** [comment] 2017-09-01 12:56
Duplicate of #2285 (check some answers there), documentation of it is in progress - mostly we need to copy it from v3 docs. Feel free to improve it as well.

**Closed by aksonov** 2017-09-01 12:56 UTC

**Comment by mcabs3** [comment] 2017-09-01 12:58
@GuillaumeMunsch most of the components you are mentioning are just `<Scene>` components with the different boolean attributes already applied for you. For Example `<Tabs>` is the same as `<Scene tab={true} />`. `<Stack>` is a grouping `<Scene>` that doesn't have a `component` prop, as it contains children `<Scene>`s.
