### ISSUE TITLE
Unable to use openDrawer() in component js file

### ISSUE THREAD

**Issue by shivangbtech** [aksonov/react-native-router-flux#540] opened 2016-04-18 09:14 UTC
I am unable to use openDrawer() in DrawerScreen.js. Here is my code, How can I pass reference of drawer to other component file.

Update:
```
'use strict';

var React = require('react-native');
var { View,
      StyleSheet,
      TouchableHighlight,
      } = React;

var DrawerLayout = require('react-native-drawer-layout');
var DrawerScreen = require('./DrawerScreen');
var DrawerMenu = require('./DrawerMenu');

var DrawerLayoutExample = React.createClass({

  render: function() {
    var navigationView = (
      <View >
           <DrawerMenu/>
      </View>
    );

    return (
      <DrawerLayout
        onDrawerSlide={(e) => this.setState({drawerSlideOutput: JSON.stringify(e.nativeEvent)})}
        onDrawerStateChanged={(e) => this.setState({drawerStateChangedOutput: JSON.stringify(e)})}
        drawerWidth={200}
        ref={(drawer) => { return this.drawer = drawer  }}
        keyboardDismissMode="on-drag"
        renderNavigationView={() => navigationView}>
        <View style={styles.container}>
        <DrawerScreen ></DrawerScreen>
        </View>
      </DrawerLayout>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'column',
  },
 });

module.exports = DrawerLayoutExample;

```
DrawerScreen.js
```
'use strict';
var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Dimensions,
  Image,
  TouchableHighlight,
  TextInput,
} = React;

var deviceWidth = Dimensions.get('window').width;

var DrawerScreen = React.createClass({


  render: function() {
    return (

        <View style={styles.container}>

          <Text style={styles.welcome}>Content!</Text>

          <TouchableHighlight onPress={() => this.state.openDrawer()}>
            <Text>Open drawer</Text>
          </TouchableHighlight>
          <TextInput style={styles.inputField} />
        </View>
    );
  },

});

var styles = StyleSheet.create({
   container: {
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
          flexDirection: 'column',
    },
    inputField: {
      backgroundColor: '#F2F2F2',
      height: 40,
    },
});

module.exports = DrawerScreen;
```

**Comment by caledhwa** [comment] 2016-04-18 14:09
How does “this.drawer” get bound in DrawerScreen??? I think you need in your DrawerScreen component:

static contextTypes = { drawer: PropTypes.object.isRequired };

Then you can add to your render(): 

const { drawer } = this.context;

And finally you can call (in the render somewhere): this.drawer.closeDrawer()

I am assuming you have a “closeDrawer” on Drawer layout… 

Also, instead of opening issues for help, please join and visit us on Gitter instead: https://gitter.im/aksonov/react-native-router-flux?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

On April 18, 2016 at 2:14:45 AM, shivangbtech (notifications@github.com) wrote:

I am unable to use openDrawer() in DrawerScreen.js. Here is my code, How can I pass reference of drawer to other component file.


` render: function() {
    var navigationView = (
      <View style={[{backgroundColor: '#fff'}, {flex: 1}]}>
           <View style={[{backgroundColor: '#246dd5'}, {height: (SCREEN_HEIGHT*30)/100}]}>
                <Text>Hello there!</Text>
           </View>

           <ListView
                dataSource={this.state.dataSource}
                renderRow={this._renderRow}
           />
           <TouchableHighlight onPress={() => this.drawer.closeDrawer()}>
                <Text>Close drawer</Text>
           </TouchableHighlight>
      </View>
    );

    return (
      <DrawerLayout
        onDrawerSlide={(e) => this.setState({drawerSlideOutput: JSON.stringify(e.nativeEvent)})}
        onDrawerStateChanged={(e) => this.setState({drawerStateChangedOutput: JSON.stringify(e)})}
        drawerWidth={200}
        ref={(drawer) => { return this.drawer = drawer  }}
        keyboardDismissMode="on-drag"
        renderNavigationView={() => navigationView}>

        <View style={styles.container}>
        <DrawerScreen ></DrawerScreen>
        </View>
      </DrawerLayout>
    );
  }
});`




DrawerScreen.js

'use strict';
var React = require('react-native');
var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Dimensions,
  Image,
  TouchableHighlight,
  TextInput,
} = React;

var deviceWidth = Dimensions.get('window').width;

var DrawerScreen = React.createClass({


  render: function() {
    return (

        <View style={styles.container}>

          <Text style={styles.welcome}>Content!</Text>

          <TouchableHighlight onPress={() => this.drawer.openDrawer()}>
            <Text>Open drawer</Text>
          </TouchableHighlight>
          <TextInput style={styles.inputField} />
        </View>
    );
  },

});

var styles = StyleSheet.create({
   container: {
      alignItems: 'center',
      justifyContent: 'center',
      flex: 1,
          flexDirection: 'column',
    },
    inputField: {
      backgroundColor: '#F2F2F2',
      height: 40,
    },
});

module.exports = DrawerScreen;

**Comment by shivangbtech** [comment] 2016-04-19 05:26
I am unable to understand the solution, I have updated my code in above post for your simplicity, Please take a look on that and guide me.

**Comment by jeroenbourgois** [comment] 2016-04-19 13:20
Can you check the example in the readme again? Key is to bind your drawer to the contextType of react, that way it will be passed and accessible within your component.

**Comment by aksonov** [comment] 2016-04-20 09:33
Seems duplicate of #524

**Closed** 2016-04-20 09:33 UTC
