### ISSUE TITLE
react-addons-pure-render-mixin not found

### ISSUE THREAD

**Issue by Milambeer** [aksonov/react-native-router-flux#1780] opened 2017-04-10 14:37 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.38.0
- react-native v0.42.3

### Expected behaviour

Launch app

### Actual behaviour

The development server returned response error code: 500

URL: http://10.0.2.2:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Body:
{"from":"c:\\Users\\Alexis\\projects\\rememberapp\\node_modules\\react-native-router-flux\\src\\DefaultRenderer.js","to":"react-addons-pure-render-mixin","message":"Unable to resolve module `react-addons-pure-render-mixin` from `c:\\Users\\Alexis\\projects\\rememberapp\\node_modules\\react-native-router-flux\\src\\DefaultRenderer.js`: Module does not exist in the module map or in these directories:\n  c:\\Users\\Alexis\\projects\\rememberapp\\node_modules\\react-native-router-flux\\node_modules\n,   c:\\Users\\Alexis\\projects\\rememberapp\\node_modules\n\nThis might be related to https://github.com/facebook/react-native/issues/4968\nTo resolve try the following:\n  1. Clear watchman watches: `watchman watch-del-all`.\n  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.\n  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.","name":"UnableToResolveError","type":"UnableToResolveError","errors":[{}]}
onResponse
    DevServerHelper.java:332
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818

### Steps to reproduce

1. npm install
2. react-native start
3.

**Comment by beiming** [comment] 2017-04-11 03:32
`npm install --save react-native-router-flux` to fix, just now.

**Comment by jnbt** [comment] 2017-04-11 08:15
I think this is a duplicate of  #1761

**Closed** 2017-07-08 05:00 UTC
