### ISSUE TITLE
Android transitions crash

### ISSUE THREAD

**Issue by rtrompier** [aksonov/react-native-router-flux#443] opened 2016-03-31 15:29 UTC
Hello,
First of all, thank you for your work.

Transitions seem to be break Android application while on IOS not.
The page change is very long and ended up closing the app.
The problem is also present on the Example app

### Versions
- react-native-router-flux v3.2.6
- react-native v0.14.8

### Steps to reproduce

1. Launch Exemple app on android device or emulator
2. Click on "Go to register page" and come back to the HomePage
3. Recommencer jusqu'a que l'application plante

Thanks

**Comment by aksonov** [comment] 2016-03-31 15:30
Duplicate of #355

**Closed by aksonov** 2016-03-31 15:30 UTC
