### ISSUE TITLE
How to reset back stack?

### ISSUE THREAD

**Issue by rajsuvariya** [aksonov/react-native-router-flux#2098] opened 2017-07-24 08:15 UTC
In v3 to clear the back stack I was using Actions.Scene({ type: 'reset' }). But apparently it's not working in v4.

**Comment by rajsuvariya** [comment] 2017-07-24 10:32
I was able to achieve it using Actions.reset("Scene") but the animation looks too bad. Actually, it shows every screen being closed.
Can I have the option to remove this animation while clearing back stack

**Comment by aksonov** [comment] 2017-07-24 12:12
Duplicate of https://github.com/react-community/react-navigation/issues/1493

**Closed by aksonov** 2017-07-24 12:12 UTC

**Comment by karanwadhwa** [comment] 2017-10-04 11:58
'replace' works fine to clear the back stack

**Comment by karanwadhwa** [comment] 2017-10-04 12:00
`'replace'` Pops the current scene from the stack and pushes the new scene to the navigation stack. *No transition will occur.
