### ISSUE TITLE
Inactive tabs are not unmounted

### ISSUE THREAD

**Issue by chetstone** [aksonov/react-native-router-flux#577] opened 2016-04-23 14:48 UTC
### Version
- react-native-router-flux v3.2.7
- react-native v0.22.2
iOS

### Expected behaviour
When a tab is inactive it should be unmounted and/or new props should not be passed to it.

### Actual behaviour
A surprise when I changed my implementation from TabBarIOS to this component--- all tabs are always active. This caused the performance issue I mentioned in Issue #520. In my main tab, say TAB A, I have a component that the user interacts with frequently, a counter button. In TAB B I have a history of all the events that happened in TAB A. The history list is implemented with [react-native-tableview reactModuleForCell](https://github.com/aksonov/react-native-tableview#editable-complex-components), which is a little expensive. It works fine to rerender when the user clicks TAB B, but if it also rerenders every time the user does something on TAB A, it slows everything down. This does not happen with TabBarIOS.

I thought I could use componentShouldUpdate() on TAB B, checking its NavigationState prop to see if it is active, but unfortunately the TabBar component somehow lies to its children, changing NavigationState to tell each of them that IT is the active scene. I ended up subscribing to a flux store in TAB B that holds the latest router action. I send the action to the store in `reducerCreate`. If my app used redux I probably could have used that as well.

**Comment by cridenour** [comment] 2016-04-23 14:54
Duplicate of #521 which is being worked on upstream in React Native.

**Closed by cridenour** 2016-04-23 14:54 UTC

**Comment by ciriac** [comment] 2016-12-19 15:31
@cridenour Any idea if this has been fixed? Thanks.

**Comment by cridenour** [comment] 2016-12-19 17:11
@ciriac Unfortunately I haven't been able to keep up with upstream changes recently so I can't say either way.
