### ISSUE TITLE
Root scene been reset on keyboard appears

### ISSUE THREAD

**Issue by macanhajc** [aksonov/react-native-router-flux#2826] opened 2018-01-23 16:56 UTC
### Version
- "react-native-router-flux": "^4.0.0-beta.27",
- "react-native": "0.50.1",

I have a group of scenes in a tab with a tabBarComponent, when i go to one scene inside the tab and go to another scene with is not in the tab scene, if i open the keyboard and tap something, my current scene is forwarded and sent to my initial in stackLogin

    const scenes = Actions.create(
        <Scene key="root">

            <Scene hideNavBar key="stackLogin">
                <Scene component={Inicio} key="inicio" initial={true} />
                <Scene component={Login} key="login" />
                <Scene component={Registro} key="registro" />
                <Scene component={ConclusaoRegistro} key="conclusaoRegistro" />
            </Scene>

            <Scene key="sliderProduto"
                direction="horizontal"
                component={SliderProduto}
                hideNavBar
            />

            <Scene
                key="tabFooter"
                tabs={true}
                lazy={true}
                swipeEnabled={false}
                tabBarComponent={MenuRodape}
                tabBarPosition="bottom"
                animationEnabled={false}
            >

                <Scene hideNavBar key="home" component={Home} />
                <Scene hideNavBar key="pesquisa" component={Pesquisa} />
                <Scene hideNavBar key="carrinho" component={Carrinho} />
                <Scene hideNavBar key="pessoa" component={Pessoa} />
                <Scene hideNavBar key="produto" component={Produto} lazy={true} />

            </Scene>

            <Scene hideNavBar hideTabBar key="verificaProduto" component={VerificaProduto} />

        </Scene>
    );

    export default class routes extends Component {
        render() {
            return (
                <Root>
                    <Router scenes={scenes} />
                </Root>
            )
        };
    }

**Comment by wallace7souza** [comment] 2018-01-30 19:55
This is happening with me. On IOS it's ok but on android it's reloading the state when a textInput get focus and the keyboard appears.

**Comment by macanhajc** [comment] 2018-01-31 11:59
I fix it using `type={ActionConst.RESET}` on the Scene where it happens, but i'm not sure if this is the right thing to do and doing this i loose my stack and i cant use pop.

`<Scene hideNavBar key="verificaProduto" component={VerificaProduto} type={ActionConst.RESET} />`

**Comment by HessiPard** [comment] 2018-06-06 08:55
Maybe duplicate of [#2817](https://github.com/aksonov/react-native-router-flux/issues/2817)

**Comment by bmikaili** [comment] 2018-06-06 12:15
Sadly calling drawerClose() before Actions.screen() didn't work.

**Closed** 2018-08-08 15:05 UTC

**Comment by roden1999** [comment] 2018-10-05 01:06
I have the same problem. When I press my input the keyboard will show and disappear after 1 seconds then go back to my initial route scene. How do I fix it.?

**Comment by bmikaili** [comment] 2018-10-05 05:12
I fixed it by not using router-flux and just using regular routing. Rewrote my entire routing.

**Comment by HessiPard** [comment] 2019-03-07 16:40
> Sadly calling drawerClose() before Actions.screen() didn't work.

Use 4.0.0-beta.31.
