### ISSUE TITLE
[help wanted] How to auto jump new route.

### ISSUE THREAD

**Issue by iugo** [aksonov/react-native-router-flux#300] opened 2016-03-09 02:04 UTC
```
componentDidMount() {
  // jump new route
}
```

In ./Example : 
When `Actions.register()` in `./Example.js`, it can work. But it can not work when `Actions.register()` in `./components/Launch.js`.

<img width="361" alt="2016-03-09 15 38 57" src="https://cloud.githubusercontent.com/assets/499364/13628450/193f2b1a-e60d-11e5-92a8-695ccf6b76ac.png">

**Comment by aksonov** [comment] 2016-03-09 10:32
Please use search before posting. Duplicate of #253.

**Closed by aksonov** 2016-03-09 10:32 UTC
