### ISSUE TITLE
Custom function on tab press

### ISSUE THREAD

**Issue by perlovka-studio** [aksonov/react-native-router-flux#2271] opened 2017-08-20 19:15 UTC
### Version
- react-native-router-flux v4.0.0-beta.18
- react-native v0.46.1

I'm trying to create something like Instagram. When tab is active and you press on it's icon, it refreshes.
`<Scene key = "tabBar" tabs>`
`    <Scene key = "news" onPress = { () => {`
`        if (this.state.active[0]) { //if this tab is active`
`            refreshNews(); //fetching to get new data`
`        } else {`
`            this.setState({active: [true, false, false, false]});`
`            Actions.news(); // just open this tab`
`        }`
`    }}>`
`        ...`
`    </Scene>`
`    ....`
`</Scene>`

### Expected behaviour
In previous version (3.37.0 for example) everithing worked fine.
### Actual behaviour
In current version onPress function is not performed.

So do I need to downgrade the version or are there any other solutions?

**Comment by aksonov** [comment] 2017-08-21 10:00
Unfortunately v4 tabbar is breaking change (because it is based on react-navigation TabNavigator now). It looks like duplicate of https://github.com/react-community/react-navigation/issues/314, please check maxmcd's workaround from there. I think we could integrate it somehow into RNRF, need to think about it. PR is welcome.

**Comment by aksonov** [comment] 2017-08-21 10:01
Btw, you may use `onEnter` handler for tabs if you need to do some actions when tab is selected.

**Comment by aksonov** [comment] 2017-08-23 08:37
Closing this ticket because `onEnter` should be enough.

**Closed by aksonov** 2017-08-23 08:37 UTC
Labels: help wanted
