### ISSUE TITLE
popTo: Cannot read property 'toString' of undefined.

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2167] opened 2017-08-02 16:19 UTC
I'm using `mobx` to set which screen should I pop to when I finish a process.

![image](https://user-images.githubusercontent.com/246373/28883406-b228ba58-7784-11e7-8e29-e0de950df499.png)

When I console what I'm passing to `popTo` it gives me the correct screen `key`.
Used to work on `beta12` and below.

## EDIT

Even with defined string it doesn't work: `Actions.popTo('home');`

## EDIT2

I found that this validation on line 206 on `navigationStore.js` is the cause of the issue:

```
if(data.toString()!=='[object Object]'){
return{data:data};
}
```

Commenting it just worked fine. Should I submit a PR?

**Comment by aksonov** [comment] 2017-08-02 16:49
I fixed it today, please check master

**Comment by luco** [comment] 2017-08-02 16:50
@aksonov Thanks!

**Comment by aksonov** [comment] 2017-08-02 19:50
Duplicate of #2163

**Closed by aksonov** 2017-08-02 19:50 UTC
