### ISSUE TITLE
Actions.refresh renderRightButton has no effect

### ISSUE THREAD

**Issue by jamesholcomb** [aksonov/react-native-router-flux#3218] opened 2018-08-27 02:52 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.1 (v3 is not supported)
- react-native v0.56.0

### Expected behaviour
The navbar refreshes with the new right button component

### Actual behaviour
No effect

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.

````
  static onEnter = () => {
    const { wrappedInstance } = Actions.refs.profile

    // this works
    Actions.refresh({
      rightTitle: "Logout",
      onRight: wrappedInstance.onLogout
    })

   // this has no effect
   Actions.refresh({
      renderRightButton: () => <MoreButton onPress={() => alert('hi')} />
   })
  }
````

**Comment by jamesholcomb** [comment] 2018-08-27 19:36
Here is how I worked around it

````
        <Scene
          back
          key={routes.PROFILE}
          component={ProfileScene}
          renderRightButton={
            <MoreButton
              onPress={() => Actions.refs.profile.wrappedInstance.onMorePress()}
            />
          }
          title="Profile"
        />
````

**Comment by pierol** [comment] 2018-08-28 20:39
I made an example code to show you what i mean go here: https://github.com/pierol/rnrf-example it's an EXPO example try to open it in a ios simulator. Make login inside the app with these credentials: pierol and pw: giulia09. You have to swtch the version of react-native-router-flux from 4.0.0.beta.27 and 4.0.1 to see the two different behaviours. There is a console log in the DayList componenetWillMount method this component is part of the first Scene. After the Login is successfully i will make an Actions.choorHour() call to return to the first Scene, the one with the Daylist component. Only using 4.0.0.beta.27 will reload the component DayList when i return to the main scene from the Login form.

**Comment by daviscabral** [comment] 2018-08-29 06:11
Thank you for the update about the workaround. This seems to be sort of a duplicate of #3188. I'll keep it marked as bug and work on both in the same PR.

**Comment by aksonov** [comment] 2018-09-05 11:41
@jamesholcomb It looks like a hack and probably just not supported by React Navigation 2.x (its SET_PARAMS action). Instead you should define one renderRightButton that changes its content depending from navigation state. `Actions.refresh` should be used just to update navigational state (i.e. pass values not functions)

**Closed by aksonov** 2018-09-05 11:41 UTC
Labels: backwards-incompatible, bug

**Comment by jamesholcomb** [comment] 2018-09-05 17:33
> Actions.refresh should be used just to update navigational state (i.e. pass values not functions)

I am attempting to upgrade a 3.X project to 4.0.  `Actions.refresh` is used throughout the app to wire up navbar buttons to their scene handlers based on data/conditions that are determined within the scene.

The example does not seem to demonstrate how to go about this and the migration guide does not mention it.

Can you elaborate or point to an example?

**Comment by waqas19921** [comment] 2019-12-26 05:49
For `react-navigation` version `3.X` use following example
```
class Companies extends Component {

    componentDidMount(){
        this.props.navigation.setParams({
          right: () => (
              <MaterialIcons
                name={'mail'}
                size={48}
                color={'black'} />
          )
        })
     } 

    render(){
      ...
    }
}
```

**Comment by waqas19921** [comment] 2019-12-26 05:50
For `react-navigation` version `4.X` use following example
```
class Companies extends Component {

    componentDidMount(){
        this.props.navigation.setParams({
          headerRight: () => (
              <MaterialIcons
                name={'mail'}
                size={48}
                color={'black'} />
          )
        })
     } 

    render(){
      ...
    }
}
```
