### ISSUE TITLE
All tabs loaded at once on using lazy property too.

### ISSUE THREAD

**Issue by priyankverma** [aksonov/react-native-router-flux#3013] opened 2018-04-26 05:59 UTC
Hello,
I am using:
    "react-native": "0.53.0",
    "react-native-router-flux": "^3.41.0"
All tabs are Loaded at once, although I am using lazy property, but then too the same problem

### Expected behaviour
It should load only the current active tab

### Actual behaviour
It loads all the tabs at once.

Can't understand this behaviour.

**Comment by HiteshGunwant** [comment] 2018-04-27 10:15
pls check with your code ,working fine at end
 end ,@aksonov pls close this point

**Comment by digitaldavenyc** [comment] 2018-05-16 02:45
@priyankverma duplicate of #2846

**Closed** 2018-06-06 14:05 UTC
