### ISSUE TITLE
Disable  gesture back action  

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2006] opened 2017-07-11 01:05 UTC
In V4 it would be good there was an option to disable the gesture back button for a specific scene. For example, I have my user login scene and then my home scene once a user login he is taken to the home scene but then he can gesture back to the login.

**Comment by alexchia** [comment] 2017-07-11 06:30
you can put panHandlers={null} in a parent/root Scene to disable this behavior.

**Comment by AlmogRnD** [comment] 2017-07-11 06:43
I just tested panHandlers={null} and it does not work, @aksonov can you reopen this.

**Comment by tendolukwago** [comment] 2017-08-11 12:55
Having this issue as well. @aksonov can you reopen?

**Comment by aksonov** [comment] 2017-08-11 13:01
Fork & reproduce it with Example project.

**Comment by abeltje1** [comment] 2017-08-12 18:08
I've also tried panHandlers={null} but it's not working. On another note: is it possible to only disable certain scenes within a parent scene? (i.e. I have 3 child-scenes and want only two of them to have the swipe-back)?

**Comment by abeltje1** [comment] 2017-08-12 18:20
Nevermind, It was a mistake on my end: everything works great, sorry!

**Comment by themakerman** [comment] 2017-08-13 16:57
@abeltje1 how did you solved it? Can you please help me out? Here is my code. <Router>
      <Scene key="root" panHandlers={null}>
          <Scene key="splash" component={SplashScreen} initial />
          <Scene key="Screen1" component={Screen1} />
          <Scene key="Screen2" component={Screen2} />
      </Scene>
    </Router>

I dont user to go from Screen1 back to SplashScreen. How can i do that?

**Comment by abeltje1** [comment] 2017-08-13 16:59
You mean with swipe right? or just in general no back-button?

**Comment by themakerman** [comment] 2017-08-13 17:47
@abeltje1 In general no back button at all. Back button should be only at Screen 2. So actual navigation will be between screen 1 and screen2. Splashscreen will be in its own zone.

panHandlers={null} doesn't solves the issue.

```
<Router>
      <Scene key="root">
          <Scene key="splash" component={SplashScreen} initial />
          <Scene key="Screen1" component={Screen1} panHandlers={null} />
          <Scene key="Screen2" component={Screen2} />
      </Scene>
    </Router>
```
I used to achieve this in previous version of RNRF using Scene buckets. But in this version i cannot write nested scenes.

**Comment by abeltje1** [comment] 2017-08-13 17:51
panHandler={null} is for touchevents. If you want to disable the back button you should use the back property on the scene, or if you want to hide the navbar altogether you should use hideNavBar

**Comment by themakerman** [comment] 2017-08-13 18:27
@abeltje1 if i use hideNavBar i can still go back to the splash screen which i don't want. back property is of no help. Can you give me any more pointers?
<Scene key="Screen1" component={Screen1} />

**Comment by abeltje1** [comment] 2017-08-13 18:34
I'll try, though I'm confused a lot of times with RNRF myself - just started developing with RN and Redux and it's a little much, so excuse me if I'm wrong. 

Let me ask a few questions to understand better what's going on, okay?

1: When in screen 1, can you still swipe from the left side of the screen to go to the splash screen?
2: If you use hideNavBar do you still see a back button?

I tried it myself and with hideNavBar there is no back button left. Secondly I also tried panHandlers={null} and that disables the swipe. To me it looks like this piece of code below should disable going back altogether. can you confirm this does not work and if that's the case: can you tell me which back option still works (back button in header OR swipe OR both)?

```
<Router>
      <Scene key="root">
          <Scene key="splash" component={SplashScreen} initial />
          <Scene key="Screen1" component={Screen1} panHandlers={null} hideNavBar />
          <Scene key="Screen2" component={Screen2} />
      </Scene>
</Router>
```

cheers

**Comment by themakerman** [comment] 2017-08-15 09:32
@abeltje1 Are you using the beta version? 
For me type="reset" prop worked like a charm. panHandlers are not working for me.
```
<Router>
      <Scene key="root">
          <Scene key="splash" component={SplashScreen} initial />
          <Scene key="Screen1" component={Screen1} type="reset" hideNavBar />
          <Scene key="Screen2" component={Screen2} />
      </Scene>
</Router>
```

**Comment by abeltje1** [comment] 2017-08-15 12:10
Works like a charm indeed (even though panHandlers worked for me too). do you perhaps know how to disable the drawer but not the swipe left? @themakerman

**Comment by aksonov** [comment] 2017-08-16 09:54
Sorry, it seems not supported yet by react-navigation (disable gestures for drawer) https://github.com/react-community/react-navigation/issues/390

**Closed by aksonov** 2017-08-16 09:54 UTC

**Comment by haythamakl** [comment] 2018-02-16 07:20
type={ActionConst.RESET} in Scene

**Comment by SourceCipher** [comment] 2018-06-13 22:47
@haythamakl solution works, but dont forget to import **ActionConst** from the **react-native-router-flux**

**Comment by yeomann** [comment] 2018-06-19 18:28
carp:( nor type="rest" nor type={ActionConst.RESET} working for me. come on:(

<img width="293" alt="screen shot 2018-06-19 at 21 27 22" src="https://user-images.githubusercontent.com/5970751/41616800-936ccc8c-7407-11e8-88f0-f08a26f90ad6.png">

**Comment by jituumaria** [comment] 2018-12-10 12:23
> @abeltje1 how did you solved it? Can you please help me out? Here is my code.
> 
> ```
>     <Scene key="root" panHandlers={null}>
>          <Scene key="splash" component={SplashScreen} initial />
>          <Scene key="Screen1" component={Screen1} />
>          <Scene key="Screen2" component={Screen2} />
>      </Scene>
>    </Router>
> ```
> I dont user to go from Screen1 back to SplashScreen. How can i do that?



you can use 

<Scene
            key="your-key"
            component={your-component}
            title="your-title"
            type="replace"
           />

**Comment by rodrigofbm** [comment] 2019-01-11 21:15
Nothing work. Can someone help?

**Comment by rodrigofbm** [comment] 2019-01-11 21:34
@yeomann Yeah! Work's, thanks por sharing!

**Comment by chirag773** [comment] 2019-01-12 19:09
> what do you mean mate? @rodrigofbm both v3 and v4 works now. mind sharing your implementation? I am using type={ActionConst.RESET} in Scenes and it's been working since.

I'm also facing the same problem

**Comment by sdv1812** [comment] 2019-01-23 06:20
> > what do you mean mate? @rodrigofbm both v3 and v4 works now. mind sharing your implementation? I am using type={ActionConst.RESET} in Scenes and it's been working since.
> 
> I'm also facing the same problem

@chirag773  What problem are you facing? You can provide the prop type={ActionConst.RESET} to the scene from which you don't want to go back. You can also use Actions.reset('Screen1') in the SplashScreen component (from the example above).

**Comment by FaizalMalik** [comment] 2019-03-06 14:30
@aksonov  I am also facing the same issue 

````
<RouterWithRedux>
                    <Scene key='root'>
                        <Scene
                            component={Login}
                            initial={!token}
                            hideNavBar={true}
                            key='Login'
                            title='Login'
                        />
                        <Drawer 
                  hideNavBar
              key="drawer"
              contentComponent={LeftSideMenu}
              drawerImage={MenuIcon}
              drawerWidth={300}
                               >
                        <Scene
                                component={Home}
                                hideNavBar={false}
                                key='Home'
                                title='Home'
                                type={ActionConst.RESET} 
                            />
                            
                        </Drawer>    
                    </Scene>
                </RouterWithRedux>
````

I have given  type={ActionConst.RESET}  in Home Scene, Still after login when i press back , It take User Back to Login screen. 

I have two screens - Login and Home. after successful login , do not take user back to Login screen .

Can some one help me ?

**Comment by jituumaria** [comment] 2019-03-06 15:03
Use--   Actions.your screen kry();

**Comment by surbhitrao** [comment] 2020-04-21 17:14
This is what worked for me:

[https://stackoverflow.com/a/61349171/5950360](https://stackoverflow.com/a/61349171/5950360)
