### ISSUE TITLE
Scenes seems to be recreated on every dispatched redux action 

### ISSUE THREAD

**Issue by itinance** [aksonov/react-native-router-flux#685] opened 2016-05-16 11:26 UTC
### Version

- react-native-router-flux v3.22.23"
- react-native 0.22

When using router-flux together with redux, it seems that the scenes are recreated on every action that was dispatched.

![screen shot 2016-05-16 at 13 09 50](https://cloud.githubusercontent.com/assets/1758597/15288164/bca0fe9c-1b68-11e6-8ea3-c8862335863c.png)

Console.log will be flooded with "Key $SceneName is already defined".

### Steps to reproduce

I cloned the example application and prepared it for usage with redux: [https://github.com/itinance/react-native-router-flux/tree/master/ExampleRedux](https://github.com/itinance/react-native-router-flux/tree/master/ExampleRedux)

I added two reducers "increment" and "decrement" and added this simple counter functionality into the launch screen.

Everytime one click on the button "increment", the increment action will being dispatched and the console is flooded with "Key launch is already defined", "Key login is already defined" and so on for every scene.

Also, as already reported in another [issue](https://github.com/aksonov/react-native-router-flux/issues/681), the state will never updated in the scene, even if dispatcher can log the correct state into the console.

**Comment by aksonov** [comment] 2016-05-16 11:31
Omg, #525 again? Why people don't check existing issues first? I've put 0.22 version even into title of the project, but it didn't help, people are creating and creating new issues with non-supported versions of React Native...

**Comment by itinance** [comment] 2016-05-16 11:33
Holy... i interpreted this as a "minimum version", not the exact required version. Thx man

**Comment by itinance** [comment] 2016-05-16 11:34
But, this example is based on 0.22, the issue remains (i wrote it wrong in my opener comment)

**Comment by itinance** [comment] 2016-05-16 11:35
https://github.com/itinance/react-native-router-flux/blob/master/ExampleRedux/package.json#L10

**Comment by aksonov** [comment] 2016-06-08 07:33
@itinance Looks like you put Router inside some other React component that calls re-rendering. If issue still exist with latest version, please reproduce it with Example project. Closing this ticket for now.

**Closed by aksonov** 2016-06-08 07:33 UTC
Labels: bug
