### ISSUE TITLE
Remote debugging experience with android device

### ISSUE THREAD

**Issue by vinaynb** [aksonov/react-native-router-flux#1177] opened 2016-09-16 02:53 UTC
### Version

Tell us which versions you are using: 
- react-native-router-flux v3.35.0
- react-native v0.31.0
### Expected behaviour

Normal animations as they when remote debugging and dev mode are turned off
### Actual behaviour

When enabling the above two features for degbugging, the push and back or for that matter any transitions between scenes are painfully slow (each transition takes about 6~7 seconds at the best). Its a horrible experience when debugging your js with such slow transitions. Imagine debugging a scene 4 touches down the line. I know there are a lot of issues around this and you need those two bits to be turned off to see the actual performance but i wanted to ask how do you guys go about debugging stuff when using this router.

Device I am running the app on is Moto g 1st gen with android 5.0 btw.
### Steps to reproduce

1.Enable js debugging from developer menu
2.Enable remote debugging 
3.Transition from one scene to another

**Comment by dannycochran** [comment] 2016-10-04 00:33
I think this is a duplicate of #199

**Comment by vinaynb** [comment] 2016-10-04 05:21
@dannycochran i followed most of the techniques advised in  #199 to improve perf on android and it did improve to acceptable levels, but the core issue now for me is when i need to debug js using breakpoints in chrome remote debugger. Transitions are very slow when remote debug is on. If the screen you are trying to debug is 3-4 levels down the path then navigating to that screen is a real pain in this case.

**Comment by damathryx** [comment] 2017-06-02 13:23
still a problem...

**Closed** 2017-07-08 04:59 UTC
