### ISSUE TITLE
actions[type] is not a function

### ISSUE THREAD

**Issue by pengyanb** [aksonov/react-native-router-flux#2070] opened 2017-07-19 09:43 UTC
I am having issue with version 4.0.0-beta.11 (I used Version 3.38.0 with my previous project, things were all working fine). 

Anyway, here is the basic structure:
```javascript
          <Provider store={store}>
                <Router wrapBy={connect()}>
                    <Scene key="root">
                        <Scene key="MenuScene" 
                            component={MenuScene} 
                            title="Menu" 
                            hideNavBar={true} 
                            initial={true}
                            type={ActionConst.RESET}>
                        </Scene>
                        <Scene key="GameScene"
                            component={GameScene}
                            title="Game"
                            hideNavBar={true}
                            type={ActionConst.RESET}>
                        </Scene>
                    </Scene>
                </Router>
            </Provider>
```

The initial scene looks like this: 
```javascript
class MenuScene extends React.Component{
    render(){
        return(
            <View>
                <StatusBar hidden={true}></StatusBar>
                <Text>This is MenuScene</Text>
                <TouchableOpacity
                    onPress={()=>{
                        console.log("Actions", Actions);
                        Actions.GameScene();
                    }}><Text>Go to Game Scene</Text></TouchableOpacity>
            </View>
        );
    }
}
```

Clicking on the TouchableOpacity gives me an "actions[type] is not a function" error. 

![screen shot 2017-07-19 at 21 37 57](https://user-images.githubusercontent.com/6076799/28360785-9e07e1e4-6cca-11e7-8c67-55eed39d87be.png)

I did a console.log to inspect the "Actions", here is what I get in console:
![screen shot 2017-07-19 at 21 40 17](https://user-images.githubusercontent.com/6076799/28360925-147f3cf0-6ccb-11e7-990d-fa7d14373eaa.png)

Anyone can see why I am getting the error? Thanks.

**Comment by igorarkhipenko** [comment] 2017-07-19 09:45
`type="reset"` should help

**Comment by quarryman** [comment] 2017-07-19 11:22
might be duplicate of closed one
https://github.com/aksonov/react-native-router-flux/issues/2017

**Comment by aksonov** [comment] 2017-07-19 12:57
Please check master now, I've added backward compatibility to use constants.

**Closed** 2017-07-19 20:02 UTC

**Comment by pengyanb** [comment] 2017-07-19 21:33
@aksonov It worked after I use 'reset' as parameter last night. I Will pull from master tonight. Thanks for the help.
