### ISSUE TITLE
How to trigger "Replace" from Router Actions? (instead of push,pop)

### ISSUE THREAD

**Issue by VansonLeung** [aksonov/react-native-router-flux#12] opened 2015-10-04 10:40 UTC
How do I trigger nav.replace ? Is it available in the current source code?

**Comment by aksonov** [comment] 2015-10-04 10:43
Pop & push? 

Pavel.

**Comment by VansonLeung** [comment] 2015-10-04 11:26
If I do Pop + Push... there will be 2 outcomes for me

1. When current page is the 1st page:
        Actions.pop();    >   will trigger this.props.onExit() instead
        Actions.LoginPage();   > will push nav to this 2nd page
Result: cannot replace  1st with 2nd, instead just "Push" has run properly

2. When current page is the 3rd page:
        Actions.pop();    >   will trigger this.refs.nav.popToRoute(routes[routes.length - 1 - num]);
        Actions.LoginPage();   > will push nav to this 4th page
Result: pop & push has run simultaneously, should theoretically return correct results, but as their push & pop animations clash together, the navigator returns blank white page instead...

**Comment by aksonov** [comment] 2015-10-04 11:30
Ok, I will add replace action soon.

Pavel.

**Comment by VansonLeung** [comment] 2015-10-04 12:55
:D  Appreciate & thanks very much for your quick feedback.

**Comment by VansonLeung** [comment] 2015-10-04 12:56
:D  Appreciate & thanks very much for your quick feedback.

**Comment by VansonLeung** [comment] 2015-10-04 13:07
Moreover, I tried to use "custom" action tags but don't know how to trigger those "custom" tags.
This part is not documented yet. Is this part not done yet?

**Comment by Mokto** [comment] 2015-10-04 14:39
Hi, to nav.replace you can do Actions.reset(ROUTE_NAME);

Is it ok for you ?

**Comment by VansonLeung** [comment] 2015-10-04 15:04
It did the job to clean the whole array of pages in the navigator.
Sadly it is an overkill for my case

**Comment by aksonov** [comment] 2015-10-05 12:58
I've added 'replace' action to the 0.3.0 version. Also I've added some notes about 'custom' actions within README.

**Comment by VansonLeung** [comment] 2015-10-05 16:12
Thank you, Cheers!

**Comment by JoaoCnh** [comment] 2015-10-08 14:24
If I do Actions.replace({name:ACTION_NAME, title: MY_TITLE})

the title doesn't get filled and after navigating for a while, let's say

this happens:

Actions.replace({name:ACTION_NAME, title: MY_TITLE})

then

Actions.push(SOME ROUTE)

then Actions.pop

then

 Actions.replace({name: OTHER_ACTION_NAME, title: MY_ANOTHER_TITLE}) 

and the title is the same one as in SOME ROUTE title. 

I really hope you can undestand what I'm trying to say. It's hard to explain well.

Am I using it wrong?

**Comment by aksonov** [comment] 2015-10-08 14:43
I understand you but i can't reproduce it. Could you please check current store-tests.js and add your ones which will fail (but should pass in your opinion) ?

**Comment by aksonov** [comment] 2015-10-12 06:26
Closing it for now, will re-open once 'failed' unit tests will be provided.

**Closed by aksonov** 2015-10-12 06:26 UTC
