### ISSUE TITLE
please update to react-navigationV2,thx

### ISSUE THREAD

**Issue by godot007** [aksonov/react-native-router-flux#3108] opened 2018-07-02 11:14 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
- react-native v0.?.?

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.
2.
3.

**Comment by aksonov** [comment] 2018-07-09 12:52
Duplicate of #3068

**Closed by aksonov** 2018-07-09 12:52 UTC
