### ISSUE TITLE
React-Native-Vector-Icons for React-Native-Router-Flux TabBar

### ISSUE THREAD

**Issue by TAM604** [aksonov/react-native-router-flux#2139] opened 2017-07-30 02:41 UTC
Hello,

I am currently using versions:

-react-native: 0.46.4
-react-native-router-flux: ^4.0.0-beta.14
-react-native-vector-icons": ^4.2.0
-mdi: ^2.0.46

Admittedly, I am still very new to coding (let alone to React Native) and I am just trying to create a home screen with tabs at the bottom using react-native-router-flux. Now I was able to create a tab bar, but now I am wondering how do I properly call the tab icons and how to incorporate tab icons (specifically from react-native-vector-icons' Ionicons and/or Material Designs Icons).

Here is the example of my code that I am using:

import React, { Component } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Router, Scene, TabIcon } from 'react-native-router-flux';
import { Icon } from 'react-native-vector-icons/Ionicons';

import Community from '../Community/Community';
import Messenger from '../Messenger/Messenger';
import User from '../User/User';

export default class Home extends Component {
    render() {
        return(
            <Router>
                <Scene key={'root'}
                        tabs={true}
                        style={styles.tabBar}
                        icon={TabIcon}
                        renderBackButton={null}
                    >
                    <Scene 
                        key={'Community'}
                        component={Community}
                        icon={TabIcon}
                        hideNavBar={true}
                    />
                    <Scene 
                        key={'Messenger'}
                        component={Messenger}
                        icon={TabIcon}
                        hideNavBar={true}
                    />
                    <Scene 
                        key={'User'}
                        component={User}
                        icon={TabIcon}
                        hideNavBar={true}
                    />
                </Scene>
        </Router>
        );
    }
}

const styles = StyleSheet.create ({
    container: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#FFF'
    },
    tabBar: {
        borderTopWidth: 0.5,
        borderColor: 'gray',
        backgroundColor: '#f5f5f5',
        opacity: 1
    }
})

If anyone can provide any information, I would greatly appreciate it.

Thank you very much

Tam

**Comment by aksonov** [comment] 2017-07-30 07:32
Duplicate of #2129. RNRF just uses react-navigation TabBar. Check Example for this repository. You may check more Examples from react-navigation repo.

With latest master repo it should work well.

**Closed by aksonov** 2017-07-30 07:32 UTC
