### ISSUE TITLE
Call Component function from onEnter/onExit

### ISSUE THREAD

**Issue by johneisenheim** [aksonov/react-native-router-flux#2361] opened 2017-09-09 16:32 UTC
### Version

- react-native-router-flux v4.0.0-beta.21 (v3 is not supported)
- react-native v0.47.2

Hi there!
First of all, thanks for this awesome router.
Is there a way to call a component method in onEnter/onExit callback?
For example:
```
<Scene key="tab1" icon={LocationIcon} component={LocationsView} hideNavBar={true}>
```
Is possibile call a `LocationView` method from onEnter/onExit method specified in Scene or a sort of ``onFocus`` event?

Thank you!

**Comment by aksonov** [comment] 2017-09-10 06:12
Duplicate of #2298

**Closed by aksonov** 2017-09-10 06:12 UTC
