### ISSUE TITLE
How connect with redux RNRF v4

### ISSUE THREAD

**Issue by DavidPineda** [aksonov/react-native-router-flux#2851] opened 2018-02-01 16:12 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.28
- react-native v0.52.1

### Expected behaviour

Updating the version of RN to 0.52.1 I also had to update the version of RNRF to 4, however my existing code broke and does not connect with redux as before.

This is my code that worked with version 3 of RNRF

import React from 'react'
import { Scene, Router } from 'react-native-router-flux'
import NavigationDrawer from './NavigationDrawer'
import { connect } from 'react-redux'

const RouterWithRedux = connect()(Router)

const NavigationRouter = () =>
  <RouterWithRedux>
    <Scene key='drawer' component={NavigationDrawer} open={false}>
      <Scene key='root'>
        ...
      </Scene>
    </Scene>
  </RouterWithRedux>

Esto conectaba con el estado y podia almacenar la escena actual

### Actual behaviour

It does not connect with the state.

### Steps to reproduce

1. update rn version
2. update rnrf version

**Comment by coolmic** [comment] 2018-02-02 16:14
Same error here, I upgraded from 
4.0.0-beta.23 to 4.0.0-beta.28 .

Before, it works with 

```javascript
const mapStateToProps = state => ({ state: state.nav });
const ReduxRouter = connect(mapStateToProps)(Router);
export default ReduxRouter;
```

With the last version, I have this weird error : 

> This navigator has both navigation and container props, so it is unclear if it should own its own state. Remove props: "uriPrefix" if the navigator should get its state from the navigation prop. If the navigator should maintain its own state, do not pass a navigation prop.

For some reason, createNavigationContainer/NavigationContainer/_validateProps trigger an error because it receive a { uriPrefix: undefined } in the props.

If I remove the mapStateToProps, I have no error, but the router does not dispatch actions, and don't react to state change.

**Comment by rovnyart** [comment] 2018-02-13 13:11
same error,  4.0.0-beta.28
react-redux v.5.0.6

Not connecting to state at all, no actions dispatched, no errors occured.

**Comment by rikur** [comment] 2018-02-18 07:23
+1

**Comment by luizguilhermefr** [comment] 2018-03-02 23:16
+1

**Comment by bialasik** [comment] 2018-03-07 07:50
+1

**Comment by gastonmorixe** [comment] 2018-03-07 08:38
+1

**Comment by kanekotic** [comment] 2018-03-12 08:54
+1

**Comment by remoteportal** [comment] 2018-03-18 18:18
+1

**Comment by fbaskara** [comment] 2018-03-25 20:40
+1

**Comment by aksonov** [comment] 2018-08-09 06:26
Could someone change Example accordingly and reproduce this issue with latest version (4.0.0-beta.42) ?

**Comment by kanekotic** [comment] 2018-08-09 06:29
I can try to do this. If its ok to wait till the weekend.

**Comment by aksonov** [comment] 2018-08-09 14:21
Okey, I just checked and RNRF beta.43 should work well with Redux. It also includes ReduxExample folder with very simple redux demo (it just 'loads' data). However simple `Redux.connect` will be not enough to support management of external nav state because react-navigation 2.x changed redux integration (comparing to react-navigation 1.x).  You still can do that using this docs:
https://reactnavigation.org/docs/en/redux-integration.html
`Actions.create(...)` creates AppNavigator you need for redux integration.

You still can use `createReducer` param to control your navigation state

**Comment by aksonov** [comment] 2018-08-10 12:39
I've just updated ReduxExample for full Redux integration, please use version 4.0.1

**Comment by daviscabral** [comment] 2018-08-23 08:37
Hey guys - any update with the Redux testing here? Can I close this issue? Thank you.

**Comment by daviscabral** [comment] 2018-08-24 10:46
I believe we can consider this done. Please open a new issue referring this one in case something new pops up.

**Closed by daviscabral** 2018-08-24 10:46 UTC
Labels: question
