### ISSUE TITLE
getting error on type="replace"

### ISSUE THREAD

**Issue by mtahir08** [aksonov/react-native-router-flux#2854] opened 2018-02-02 08:59 UTC
- react-native-router-flux ^4.0.0-beta.28
- react-native 0.50.3
I am using router like this. 
                        <Scene
                            key="name"
                            component={ComponentName}
                            hideNavBar={true}
                            type="replace"
                        />
and calling Actions.name() 

As it will replace current screen  but getting error 
undefined is not an object(evaluating "resetAction.actions.map")
![image](https://user-images.githubusercontent.com/8261297/35723483-3da0819c-081c-11e8-879a-f3d8ac2e37ab.png)
but if I use with type="push" it works fine.

**Comment by Blapi** [comment] 2018-02-02 10:12
Duplicate of ~5 existing issues.

`react-native-router-flux: 4.0.0-beta.27` if you want to make it work.

**Closed by Blapi** 2018-02-02 10:12 UTC
