### ISSUE TITLE
Android transitions not working v4-beta branch

### ISSUE THREAD

**Issue by JesusTSeger** [aksonov/react-native-router-flux#2278] opened 2017-08-22 15:46 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported)
"4.0.0-beta.18"
- react-native v0.?.?
"0.47.1 ",
- testing on Samsung Galaxy S6

### Expected behaviour
Android transitions are not working in v4-beta branch. 

### Actual behaviour
Even in the example demo, when ran on an android device, all transitions are pop-ups from the bottom.  Same issue occuring in our app after upgrading.  I know other transitions were supported in v3 so is this just one of the current drawbacks of the beta v4 branch?  If this isn't currently in the process of getting fixed then I would be happy to add a note about this to docs.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.  Git clone example app
2. Run on Android
3. Notice all transitions are pop-ups

**Comment by aksonov** [comment] 2017-08-22 15:49
Duplicate of #2177. Feel free to add note. However you may add custom transitions with latest master - check Example with 'fade' transition for some screens.

**Closed** 2017-08-22 15:49 UTC
