### ISSUE TITLE
Keep previously mounted scene active in selected tab

### ISSUE THREAD

**Issue by getnashty** [aksonov/react-native-router-flux#2587] opened 2017-11-02 20:48 UTC
### Expected behaviour
```
<Scene key="tab_lobby" title="find" initial>
   <Scene key="tab_1" component={myCmp1} />
    <Scene key="tab_2" component={myCmp2} />
</Scene>
<Scene key="tab_other" title="example 2" component={myCmp3} />
```

1. `tab_lobby` loads, because it is `initial`, and `tab_1` is displaying `myCmp1`;
2. User presses a button to navigate (push) to tab_2.
3. User selects `tab_other` from the tab bar.
4. User selects `tab_lobby`:

**Expected**:  on step 4, tab_2 is visible, as it was the most recently visible content on that tab.
**Actual**: tab_2 is visible for a moment as it pops out, and tab_1 is displayed.

Is this by design, or is there a way to achieve the desired behavior?

**Comment by aksonov** [comment] 2018-01-04 15:24
I can't reproduce it. Please change Example project to reproduce it. Closing it for now, feel free to re-open.

**Closed by aksonov** 2018-01-04 15:24 UTC
