### ISSUE TITLE
Minimize android app from initial screen not working

### ISSUE THREAD

**Issue by vishnuc** [aksonov/react-native-router-flux#2494] opened 2017-10-11 17:41 UTC
I have two scenes like below

```
render() {
    return <Router> 
      <Scene key="root">
 	      <Scene key="Feed" component={Feed}   initial={true}  hideNavBar={true} />
 	      <Scene key="Refer"   headerTitle={Refer} gesturesEnabled={true} hideNavBar={true} component={Refer}   />
        </Scene>
    </Router>;
  }
}
```

When I am in **Refer** page and When I press back button , Its working fine and navigating to **Feed** page , I want app to minimize if I press back again in Feed page , but its not working

**Comment by aksonov** [comment] 2017-10-17 10:53
Duplicate of #2487

**Closed by aksonov** 2017-10-17 10:53 UTC
