### ISSUE TITLE
Back icon does not show title

### ISSUE THREAD

**Issue by AlexDM0** [aksonov/react-native-router-flux#380] opened 2016-03-23 15:57 UTC
Hi,

I've cloned your project, ran npm install and ran the example. In the gifs you see Login next to the back arrow when the login2 page is accessed but it does not seem to work in the example. Is something broken or is it a configuration thing?

Regards

**Comment by aksonov** [comment] 2016-03-23 15:58
Duplicate of #368

**Closed by aksonov** 2016-03-23 15:58 UTC
