### ISSUE TITLE
Navigating when changing redux state

### ISSUE THREAD

**Issue by geniuscd** [aksonov/react-native-router-flux#2374] opened 2017-09-12 13:40 UTC
I'm testing both react navigation (till now I found one drawback only on Modals screens where a workaround must implemented) and react native router flux v4 beta 22. (using redux for both)

I like the idea that in _react navigation_ we can navigate to a screen from a reducer when changing the state of the route, it will simply navigate to another screen.
in _RNRF_, at least in the examples that i saw, we must call the ACTIONS from within the component (view) in order to navigate. for simple apps thats ok. But for larger apps its advisable that the state handles the screen navigation.

any thought?

*discussion*

**Comment by aksonov** [comment] 2017-09-13 05:47
Duplicate of https://github.com/aksonov/react-native-router-flux/issues/2115

**Closed by aksonov** 2017-09-13 05:47 UTC

**Comment by geniuscd** [comment] 2017-09-13 07:18
Thank you for your reply.  I already read #2115 and didn't understand the fact that i need to call ACTION.... in the reducer? for now it's working but is it the correct way to do it?

`case 'user_login_success': Actions.profile(); return state;`

**Comment by aksonov** [comment] 2017-09-13 07:21
It is possible but it is not fully 'redux' style. So with v4 you could do the same as with react-navigation - integrate your reducer with navigation reducer and pass own dispatch/state into RNRF.

**Comment by aksonov** [comment] 2017-09-13 07:21
You should refer to mentioned demo.

**Comment by geniuscd** [comment] 2017-09-13 07:55
@aksonov I tried to implement from this demo [link](https://github.com/rasmniel/rnrfSample/blob/master/src/route-reducer.js) but i was getting an error in the getStateForAction. I guess because it was returning ` defaultReducer(state, action);` instead of `return { ...state, PARAMS }` 
I will try to integrate what you said above and see what will happen.

in the reducer `case ActionConst.FOCUS:` is only called if and only if `Action.PARAMS` is called from a view.

**Comment by ssomnoremac** [comment] 2017-09-14 19:19
@geniuscd , yeah I got the same. Did you get around the error?

**Comment by geniuscd** [comment] 2017-09-15 07:13
@ssomnoremac yes :P i used react-navigation

**Comment by jordenchang55** [comment] 2017-09-15 07:50
I also got the error and fixed it.
```javascript
// it is important to load reducers AFTER actions.create (so no import here)
const reducers = require('./reducers').default;
```
You should make sure your implementation import the reducer by correct order. When I changed the above line of code to  the correct place, and it worked.

**Comment by ssomnoremac** [comment] 2017-09-15 15:47
@jordenchang55 that got me around the error, thanks. My `App.js` was not configured to the example; however, using the exact same [route-reducer](https://github.com/aksonov/rnrfSample/blob/master/src/route-reducer.js) and the following, none of the router actions (FOCUS, PUSH, etc) are seen using master RNRF:

```

const navigator = Actions.create(
    <Stack ...
)
const reducers = require('./reducers').default;

const ReduxReducer = connect((state) => ({ state: state.route }))(Router);

const middleware = [thunk];
const store = compose(
    applyMiddleware(...middleware)
)(createStore)(reducers);

...
                <Provider store={store}>
                    <View style={{flex:1, backgroundColor: "#ccc"}}>
                        <ReduxReducer navigator={navigator} />
                    </View>
                </Provider>
```

**Comment by jordenchang55** [comment] 2017-09-15 21:37
@ssomnoremac I compared our code, and found that changing your store resolves the problem.

```javascript
// Your code
const store = compose(applyMiddleware(...middlewares))(createStore)(reducers);
// My code
const store = createStore(
  reducers,
  compose(
    applyMiddleware(...middlewares)
  )
);
```

**Comment by ssomnoremac** [comment] 2017-09-16 02:38
hmm, strange, that didn't fix it for me. It must mean I have something else setup differently. I'm going to have a closer look. I won't give up on this! Thanks for your help.
