### ISSUE TITLE
Passing parameters via Action does not work

### ISSUE THREAD

**Issue by OFranke** [aksonov/react-native-router-flux#778] opened 2016-06-04 06:59 UTC
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.16
- react-native v0.26.1

### Expected behaviour
I want to pass parameters via Actions. This is what I am doing:

     Actions.CompanyProfile({companyName: "company_name"});

I want to receive companyName in the CompanyProfile constructor like this: 

class CompanyProfile extends React.Component {
  constructor(props){
    super(props);
    alert(this.props.companyName); //this should alert "company_name"
  }
}

### Actual behaviour

  alert(this.props.companyName) is undefined.

###
Note that the container I am calling the action from and CompanyProfile are both connected to redux store. I already tried disconnecting CompanyProfile, but that also did not work. 

Am I missing something here?

**Comment by shiv86** [comment] 2016-06-04 09:15
How have you defined your scenes ? Typically it looks like:

```
        return <Router createReducer={reducerCreate} sceneStyle={{backgroundColor:'#F7F7F7'} }>
            <Scene key="main" >
              <Scene key="mainContainer" component={MainContainer} />
              <Scene key="firstContainer" component={FirstContainer} />
              <Scene key="secondContainer" component={SecondContainer} />
            </Scene>  

        </Router>;
```

and you called Action.<key>({attribute: value}). So in the case above if I wanted to call firstContainer I would call `Action.firstContainer(companyName: "company_name"{})`. Note the value after Action. refers to the key name that you define not the actual component.

**Comment by OFranke** [comment] 2016-06-04 09:27
<Provider store={store}>
            <Router hideNavBar={true}
            footer={TabBar}>
                <Scene key="root">
                    <Scene key="TabBar" tabs={true} default="TagSearchView">
                        <Scene        key="TagSearchView"
                        title="TagSearchView"
                        icon={TabIcon}
                        iconName={"home"}
                        hideNavBar={true}
                        component={TagSearchView}
                        initial={true}
                        />
                        <Scene        key="TagSearchResults"
                        title="TagSearchResults"
                        component={TagSearchResults}
                        hideTabBar={false}
                        />
                        <Scene        key="TodayinMap"
                        title="TodayinMap"
                        component={TodayinMap}
                        />
                        <Scene        key="CompanyProfile"
                        title="CompanyProfile"
                        component={CompanyProfile}
                        icon={TabIcon}
                        iconName={"home"}
                        />
                    </Scene>
                </Scene>  
            </Router>
        </Provider>


Yep, my route should be set up as needed. It is actually calling the component, just not passing the props. But what do you mean with this format (companyName: "company_name"{}) ? Did I do anything wrong with the parameters?

**Comment by shiv86** [comment] 2016-06-04 09:32
My bad  ({companyName: "company_name"}) should have been within the brace. Yeh not sure why its coming as undefined .

**Comment by OFranke** [comment] 2016-06-06 11:24
I found the problem. 
If I move the Scene CompanyProfile outside of the TabBar, I am receiving the props as expected. 
Is there a possibility to to pass parameters to Scenes which are part of the TabBar?

I thought about something like

    Actions.TabBar.CompanyProfile({companyName: "company")}; 

but that does not seem to work.

**Comment by normenster** [comment] 2016-06-06 13:45
I can confirm that putting a <scene> into tabbar and calling Action.Scene(payload) from somewhere to pass vars to that scene doesn't work, although the scene is being displayed and loaded. But props remains in an old state.

**Comment by aksonov** [comment] 2016-06-06 14:05
It is not currently implemented - jump action doesn't pass props. You may submit PR to implement that.

**Comment by OFranke** [comment] 2016-06-07 05:36
I've had a look at the code, I am way to unexperienced yet to understand what's happening in Reducer.js, so I am trying to work around this for now. 
Thanks aksonov!

**Comment by aksonov** [comment] 2016-06-08 07:42
Looks like duplicate of #563

**Closed by aksonov** 2016-06-08 07:42 UTC
