### ISSUE TITLE
Attempt to present <RCTModalHostViewController... which is already presenting - and increasing warning

### ISSUE THREAD

**Issue by vvusts** [aksonov/react-native-router-flux#2563] opened 2017-10-30 13:45 UTC
Hi people,

I need urgent help if possible.
I am hitting some serious performance issues and I think that I maybe setup RNRF wrong.
Can somebody check my setup and tell me if I am getting problems from it and what to do to fix this:

```
<RouterWithRedux>
          <Scene key="modal" component={Modal} >
            <Scene key="root">
              <Scene key="splashScreen" component={SplashScreen} hideNavBar initial />
              <Scene key="homeScreen" component={HomeScreen} type={ActionConst.RESET} hideNavBar />
              <Scene key="productDetails" component={ProductDetails}/>
              <Scene key="wizard" direction="vertical" hideNavBar >
                <Scene key="wizardRoot"  component={WizardRoot} panHandlers={null}/>
                <Scene key="completeScreen" component={CompleteScreen} panHandlers={null}/>
              </Scene>
            </Scene>
          </Scene>
        </RouterWithRedux>
```

As you can see my app flow is **Splash > Home > From home I open product details > From product details I open Wizard as modal > In wizard modal I navigate from one component to another and close it (closing code is: Actions.homeScreen();)**
In console I get this warning:
`Warning: Attempt to present <RCTModalHostViewController: 0x15bf75500>  on <UIViewController: 0x153e081e0> which is already presenting <RCTModalHostViewController: 0x15bf7b800>`
And this warning increase.
As I close and open product details screen more and more this warning is always increased by 1.
So oppening it 10 times result each time: 1 warning, 2 warnings ... 10 warnings.

**Comment by raynor85** [comment] 2017-11-07 11:26
There isn't enough information to see where the problem is honestly, but my suggestion is to be sure to dismiss everything in your components when you hit the back button. I had the same problem when the keyboard was involved. I was able to remove the warning using Keyboard.dismiss() when tapping on the back button. It is probably not what is happening int your case, but I thought it was worth give you a hint.

**Comment by aksonov** [comment] 2017-11-10 18:14
Please reproduce the issue with Example project. Closing this ticket for now.

**Closed by aksonov** 2017-11-10 18:14 UTC
Labels: help wanted

**Comment by mienaikoe** [comment] 2017-11-13 21:36
I had this error too. I was rendering more than one <Modal /> element in the same root node. After adding code to unmount the first one before opening the second one, the problem went away.

**Comment by raynor85** [comment] 2017-11-13 23:20
Should be related to https://github.com/facebook/react-native/issues/10471

**Comment by Achilles0509** [comment] 2021-04-16 02:47
> I had this error too. I was rendering more than one `<Modal />` element in the same root node. After adding code to unmount the first one before opening the second one, the problem went away.

Can you add code block, please?
