### ISSUE TITLE
Allow push the same scene into navigation stack multiple

### ISSUE THREAD

**Issue by wangshangming** [aksonov/react-native-router-flux#3263] opened 2018-09-13 03:15 UTC
### Version
- react-native-router-flux v4.0.1
- react v16.4.1
- react-native v0.57.0

### Expected behaviour
Allow  push the same scene into navigation stack multiple which was supported @4.0.0-beta.31

### Actual behaviour
Actions.push called just like Actions.refresh

### Steps to reproduce
As i have a demand to select a district(country -> city -> area), i provide a scene named "distictSelect" which accept an array of location datas to display a list of items for user to select. Once i call Actions.distictSelect by passing the data of countries, i am suppose to calculate the array of cities and call Actions.distictSelect again to start an new page to provide a city selections after user selected his/her country and same as the area. In that case i think it is necessary to allow push the same scene into navigation stack muliple.

**Comment by daviscabral** [comment] 2018-09-13 06:45
Duplicate of #3176. This was already fixed on #3190 but the code was not released under a new version yet. To get the fix, you will have to install the code from master. 

I recommend to wait - `4.0.2` should be out today or tomorrow.

**Closed by daviscabral** 2018-09-13 06:45 UTC
