### ISSUE TITLE
Replace scene but use push/pop animation

### ISSUE THREAD

**Issue by James2516** [aksonov/react-native-router-flux#2476] opened 2017-10-08 12:21 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.3

Is there a way to replace the scene (don't keep it in memory), but still use the push/pop transition animation?

Also what's the point of wrapping a series of scenes in `Stack`? Wrapping it around `Scene` and calling `push`/`pop` seems to have the same effect.

**Comment by luco** [comment] 2017-10-09 01:12
Duplicate of #2236.
Not possible yet.

**Closed** 2017-10-17 10:55 UTC
