### ISSUE TITLE
Demo seems to be broken

### ISSUE THREAD

**Issue by siemiatj** [aksonov/react-native-router-flux#145] opened 2016-01-25 07:38 UTC
I tried running the example app and it does not quite look as I would expect it to : 

![screen shot 2016-01-24 at 11 37 20 pm](https://cloud.githubusercontent.com/assets/513460/12545032/9971c6f4-c2f3-11e5-961b-fead4fde118b.png)

**Comment by thachp** [comment] 2016-01-25 08:57
What is not working? Can you provide repro(s)?

**Comment by aksonov** [comment] 2016-01-25 14:43
Cannot reproduce, closing it for now

**Closed by aksonov** 2016-01-25 14:43 UTC
