### ISSUE TITLE
tests failing due to non transpiled code in node_modules

### ISSUE THREAD

**Issue by sattaman** [aksonov/react-native-router-flux#628] opened 2016-05-03 14:47 UTC
## Version

react-native-router-flux v3.22.0
react-native v0.22

## Expected behaviour

Tests run correctly 

## Actual Behaviour

When running tests, any imports of react-native-router-flux are breaking as throwing errors, 'unexpected import' . This is due to node_modules not being transpiled by babel. Looking through other packages in my node_modules, it seems the others are pre-transpiled.

I am following the code outlined in the [enzyme guide for react native](https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md): 

```
"scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "mocha --require react-native-mock/mock.js --compilers js:babel-core/register --recursive test/*.js"
  }
```

My own code is being transpiled correctly. [A guide](http://jamesknelson.com/writing-npm-packages-with-es6-using-the-babel-6-cli/) I have found have suggests that libraries should be transpiled, so I thought I'd see what your view was, and if you could recommend a solution.

**Comment by cgreening** [comment] 2016-05-05 14:05
https://github.com/aksonov/react-native-router-flux/issues/613

**Comment by charpeni** [comment] 2016-05-09 17:11
Duplicate of #613.

**Closed by charpeni** 2016-05-09 17:11 UTC

**Comment by sathyakumarseshachalam** [comment] 2016-05-18 15:18
@cridenour : I see this issue as closed. But I am not able to clearly see a resolution. Do you have a recommendation / steps to fix the issue

@sattaman : Were you able to resolve the issue ?

**Comment by sattaman** [comment] 2016-05-18 15:28
@sathyakumarseshachalam I was able to get this project transpiling 

http://stackoverflow.com/questions/37251534/how-to-test-project-when-3rd-party-modules-used-arent-transpiled

I have also moved my references to this project into my container components, which has allowed me to test my inner ones, 

My current error thrown by this component is due to NavigationExperimental not being mocked, I noticed aksonov has an issue open regarding mocks for this. I also noticed that someone has PR'd mocks although not looked yet.

**Comment by hellogerard** [comment] 2016-06-17 14:20
I'll chime in here, perhaps unnecessarily.

I too ran into this issue. The solutions in that StackOverflow post (which I believe are derivations of the [real solution](https://github.com/facebook/react-native/issues/5392) from the author of Enzyme) work great for other RN modules in general, but I still ran into RNRF issues, specifically issues with PNG images and the new `react-native-experimental-navigation` module.

In the end, I found it easier to use `mockery`:

```js
const mockery = require('mockery');
mockery.enable({
    warnOnReplace: false,
    warnOnUnregistered: false
});
mockery.registerMock('react-native-router-flux', {Actions:{}});
```

**Comment by casenjo** [comment] 2016-08-08 21:06
I got this error after adding RNRF to my project:
`SyntaxError: ../node_modules/react-native-router-flux/src/menu_burger.png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
`

I have a setup.js file in my tests folder that set up everything needed to test in our project. Using the approach that @hellogerard used was great and it fixed my issues. Are there any downsides to using it though?

**Comment by Twitchkidd** [comment] 2016-08-08 21:07
I got that error, uninstalled my app and reinstalled it on the next build, and it went away

**Comment by casenjo** [comment] 2016-08-08 21:14
@Twitchkidd did you get the error during runtime or automated testing? I'm able to run the project and it works great, but for the automated testing I get it

**Comment by Twitchkidd** [comment] 2016-08-08 21:16
Oops, sorry, at runtime
