### ISSUE TITLE
Change transition direction

### ISSUE THREAD

**Issue by nica0012** [aksonov/react-native-router-flux#3289] opened 2018-09-22 22:03 UTC
How can I change the transition direction without having to install react-navigation?

There seems to be nothing in the docs for this... There is a lot of discussion about the transitionConfig in the issues but that is about it. This should be more clear in the docs.

Cheers.

**Comment by daviscabral** [comment] 2018-09-23 03:08
`react-navigation` is part of the lib - you MUST have it installed... What I mean is that it is automatically installed - even `react-navigation-stack` - that is now a dependency of `react-navigation` v2.

So if you check examples, both the `react-navigation` one and the `expo` show how to use it - but about changing direction, you will have to really check `react-navigation` docs or stack-overflow. I believe this was already answered here. 

In case you want to help improving the docs, PRs are welcome.

Duplicate of #3227.

**Closed by daviscabral** 2018-09-23 03:08 UTC
Labels: for stack overflow, question
