### ISSUE TITLE
After Install react-native-router-flux it's give me error 

### ISSUE THREAD

**Issue by ashikjs** [aksonov/react-native-router-flux#1815] opened 2017-04-24 16:51 UTC
I was get same error post but I am understand what i can do or What i have to do now, Please help me.

Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: C:\Users\ashik\Desktop\react_apps\Friends\node_modules\react-native-router-flux\node_modules\react-native\p
ackage.json collides with C:\Users\ashik\Desktop\react_apps\Friends\node_modules\react-native\package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: C:\Users\ashik\Desktop\react_apps\Friends\node_modules\react-native-router-flux\node_modules\react-native\p
ackage.json collides with C:\Users\ashik\Desktop\react_apps\Friends\node_modules\react-native\package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (C:/Users/ashik/Desktop/react_apps/Friends/node_modules/react-native/packager/src/no
de-haste/DependencyGraph/HasteMap.js:159:13)
    at p.getName.then.name (C:/Users/ashik/Desktop/react_apps/Friends/node_modules/react-native/packager/src/node-ha
ste/DependencyGraph/HasteMap.js:134:31)

C:\Users\ashik\Desktop\react_apps\Friends>Failed to build DependencyGraph: @providesModule naming collision:
'Failed' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ashik\Desktop\react_apps\Friends>  Duplicate module name: react-native
'Duplicate' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\ashik\Desktop\react_apps\Friends>  Paths: C:\Users\ashik\Desktop\react_apps\Friends\node_modules\react-nati
ve-router-flux\node_modules\react-
'Paths:' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MattyK14** [comment] 2017-04-24 17:48
This is, ironically, a duplicate of #1803

**Comment by ashikjs** [comment] 2017-04-24 17:57
@MattyK14 as you thing is it duplicate but I was not understand those solution and not solve those solution of my error or problem thes why I was make this issue . 
By the way i got this solution from make a in  stackoverflow  . [This is Solution](http://stackoverflow.com/questions/43594226/failed-to-build-dependencygraph-and-failed-to-build-dependencygraph/43594385)

**Closed** 2017-04-24 17:58 UTC

**Comment by MattyK14** [comment] 2017-04-24 18:11
Exact same solution as in #1803
