### ISSUE TITLE
Styling the NavBar

### ISSUE THREAD

**Issue by rowellx68** [aksonov/react-native-router-flux#47] opened 2015-12-09 22:11 UTC
I can't seem to find an example for defining the style for the NavBar?

**Comment by aksonov** [comment] 2015-12-10 06:55
My fault, will do documentation later (or someone else could do, it would be really great) For any missed docs, refer to exNavigator docs - Router just passes all params to ExNavigator component. As I can see you could use navigationBarStyle param.

**Comment by aksonov** [comment] 2015-12-10 06:56
Looks like exNavigator lacks documentation as well :)
https://github.com/exponentjs/ex-navigator/issues/18

**Comment by joshuarotenberg** [comment] 2015-12-13 13:46
:+1:

**Comment by aksonov** [comment] 2015-12-13 20:54
Does navigationBarStyle work for you?

**Comment by aksonov** [comment] 2015-12-14 16:22
Added rightButtonStyle, backButtonBarStyle, rightButtonTextStyle as well as renderLeftButton, renderRightButton and renderBackButton to customize nav bar.

**Comment by emrosenf** [comment] 2015-12-14 22:52
navigationBarStyle as a property of <Schema> is not working properly. It looks like the property is not passed to the <ExNavigator> . It would be good to make the other ExNavigator properties available too, for sake of completeness:  titleStyle, barButtonTextStyle, barButtonIconStyle

**Comment by aksonov** [comment] 2015-12-15 08:57
navigationBarStyle is property for Router, not for Route. All Router's properties are passed to ExNavigator, you may check sources, it should work out of the box.

**Comment by emrosenf** [comment] 2015-12-15 09:27
There's definitely something funky happening. Try using these Schemas with the example:

                <Schema name="modal" navigationBarStyle={{backgroundColor: 'green'}} sceneConfig={Navigator.SceneConfigs.FloatFromBottom}/>
                <Schema name="default" navigationBarStyle={{backgroundColor: 'brown'}} sceneConfig={Navigator.SceneConfigs.FloatFromRight}/>
                <Schema navigationBarStyle={{backgroundColor: 'blue'}}  name="withoutAnimation"/>
                <Schema navigationBarStyle={{backgroundColor: 'red'}}  name="tab" type="switch" icon={TabIcon} />


Then go to the tab controller and switch to different tabs. How many of them are have red bars?

**Comment by emrosenf** [comment] 2015-12-15 09:28
Nevermind, I misread what you had written. I see that the property goes with `Router`, not `Schema`. Sorry.

**Comment by rowellx68** [comment] 2015-12-15 11:23
@aksonov tested it and I got it to work. I'll try and modify the example and do a simple writeup

**Comment by joshuarotenberg** [comment] 2015-12-21 13:07
I have a couple navbar styling requests, if you don't mind.

![screen shot 2015-12-21 at 8 01 08 am](https://cloud.githubusercontent.com/assets/6411014/11931296/47f60970-a7b9-11e5-9c01-3aebf23411de.png)

How can I change the statusBar to white? Also, any way to kill the borderbottom of the navbar? Can I just remove it or make it the same color as the nav. 

![screen shot 2015-12-21 at 8 05 02 am](https://cloud.githubusercontent.com/assets/6411014/11931316/92f55ca0-a7b9-11e5-8101-3acbb2f0292d.png)

I would also like to remove the word "home" from the leftText and change all the text in Navbar to white. 

Thanks in advance.

**Comment by igin** [comment] 2015-12-28 18:35
Hmm ... I liked how this was done in react-native-redux-router ... there you could pass your own navbar component to every route. Would this be very hard to implement?

**Comment by andreasbhansen** [comment] 2015-12-29 08:52
@igin You should be able to pass a navbar component into ```header={}``` on each router, at least: https://github.com/aksonov/react-native-router-flux#router

**Comment by igin** [comment] 2015-12-29 13:07
@andreasbhansen Yes I think you are right ... It will take a bit of redesign on my side but it should work. Are the routes passed to this header view as props? (sorry that may be off topic for this issue)

**Comment by aksonov** [comment] 2016-01-04 11:56
Now 2.0 version passed pure Router instance as router prop.

**Comment by joelcloralt** [comment] 2016-01-13 04:04
@joshuarotenberg were you able to set the back button style to white? I'm passing `backButtonBarStyle` as a prop to the route and the router and it doesn't do anything on either.

**Comment by aksonov** [comment] 2016-01-13 08:18
@joelcloralt PR #118 have to fix it, please check

**Comment by joelcloralt** [comment] 2016-01-13 08:39
I can confirm this works. The key thing to notice is that the icon takes `tintColor` and the text takes `color` as styles. So for anyone else wanting to customize the NavBar Colors here is what I have:

Until next release, modify ExRouter.js with this commit: https://github.com/aksonov/react-native-router-flux/commit/b5b9b2f8a85285695869e0d21595293304f793fc

```
<Router navigationBarStyle={styles.navBar} titleStyle={styles.navBarTitle} barButtonTextStyle={styles.barButtonTextStyle} barButtonIconStyle={styles.barButtonIconStyle}>
 //some routes...<Route .... /> 
</Router>
```
And styles:
```
navBar: {
	backgroundColor:'#0D47A1',
},
navBarTitle:{
	color:'#FFFFFF'
},
barButtonTextStyle:{
	color:'#FFFFFF'
},
barButtonIconStyle:{
	tintColor:'rgb(255,255,255)'
},
```

**Comment by aksonov** [comment] 2016-01-13 13:06
I believe i could close it now.

**Closed by aksonov** 2016-01-13 13:06 UTC

**Comment by alirezavalizade** [comment] 2016-08-05 14:36
how to change color of clock and wifi status and i dont know what is that name... :)
<img width="372" alt="screen shot 2016-08-05 at 6 57 46 pm" src="https://cloud.githubusercontent.com/assets/14992757/17439956/ab21e458-5b3f-11e6-8770-13fa2d6ac670.png">

```
  <Scene key="app" navigationBarStyle={{backgroundColor: '#1e2226'}}  titleStyle={{color : "#FFF"}}>
    <Scene  key="welcome" component={LauchContainer} title="Welcome" />
    <Scene key="counter" component={CounterContainer} title="dsfdsfdsf" />
  </Scene>
```

**Comment by joshuarotenberg** [comment] 2016-08-05 14:40
@alirezavalizade: you can make that change in xCode http://stackoverflow.com/a/35287747

**Comment by alirezavalizade** [comment] 2016-08-06 09:47
how to change color of Backbutton in react native router flux ?

<img width="369" alt="screen shot 2016-08-06 at 2 19 20 am" src="https://cloud.githubusercontent.com/assets/14992757/17456054/46fa43fc-5be0-11e6-87b3-d87226138cf0.png">

Im try `backButtonBarStyle` but not working...i cant find any solution.tnx for your helps

```
<Scene key="app"  navigationBarStyle={{backgroundColor: '#1e2226',borderBottomColor:"#1e2226"}}  titleStyle={{color : "#FFF"}}>
    <Scene  key="welcome" component={LauchContainer} title="Welcome" />
    <Scene key="ProductDetail"  backButtonBarStyle={{color : "#FFF"}} component={ProductDetail} />
  </Scene>
```

**Comment by berkayk** [comment] 2016-08-22 16:14
Use `barButtonTextStyle` and `barButtonIconStyle` such as the following styles.

```
barButtonTextStyle: {
    color:'#F16B6F'
},
barButtonIconStyle: {
    tintColor:'#F16B6F'
},
```

**Comment by fostertime** [comment] 2016-09-02 16:42
@berkayk that didn't work for me. I had to use backButtonTextStyle in order to change the text color.

**Comment by jhabdas** [comment] 2016-09-23 21:59
Be sure you're looking at the `API_CONFIGURATION.md` specific to your installed release, e.g.

https://github.com/aksonov/react-native-router-flux/blob/3.30.1/docs/API_CONFIGURATION.md

**Comment by robtg4** [comment] 2016-10-06 02:22
@joelcloralt any way of exchanging the default back button icon with one of your own?

**Comment by jhabdas** [comment] 2016-10-06 21:50
@robtg4 depends on your version. check API docs

**Comment by OscarBastardo** [comment] 2016-10-25 16:13
hello, is there any way to style (resize, specifically) the navigationBarBackgroundImage?

**Comment by MattyK14** [comment] 2016-12-07 16:40
Is there any way to change the color of the menu button?

**Comment by jhabdas** [comment] 2016-12-07 16:47
See API docs [as mentioned above](https://github.com/aksonov/react-native-router-flux/issues/47#issuecomment-249312606)

**Comment by MattyK14** [comment] 2016-12-07 16:53
You can change the image yes, but there seems to be no way of just changing the color from the default blue. `barButtonIconStyle={{ tintColor: '#fff' }}` only changes the chevron back button.

**Comment by colorfulberry** [comment] 2016-12-08 02:03
Can i only remove the back button?

**Comment by thienanle** [comment] 2016-12-13 05:29
It seems if I define `navigationBarStyle` based on state and the state changes, the bar does not update. If I add a key to `<Router>` and update the key then I can force a change, but this feels dirty. Is there a better way to achieve this?

**Comment by HubMahesh** [comment] 2017-03-03 00:00
Hi there,
"Navbar items"

I want image in title not text. so, when i add image using navigationBarTitleImage property, it is going to top left corner. and tried more to get in center using navigationBarTitleImageStyle property, image is fixed but right and left icons are not visible or miss it's original place.

so, cam i get the proper solution please.

**Comment by fourteen** [comment] 2017-03-03 00:38
@HubMahesh can you post the code you used for navigationBarTitleImage?

**Comment by Nygma297** [comment] 2017-03-28 10:12
```
import React from 'react'
import { Actions, Scene, StyleSheet } from 'react-native-router-flux'

const scenes = Actions.create(

	<Scene key="app" navigationBarStyle={{ backgroundColor: '#db342e' }}>
		<Scene key="drawer" component={NavigationDrawerComponentWrapper} open={false} >
			<Scene key="requiredBecauseOfDrawer">
                            <Scene key . . . />
                            //Scenes
			</Scene>
		</Scene>
	</Scene>
)
```

Can't color the navBar Please Someone help out!

**Comment by brownmagik352** [comment] 2017-04-10 03:27
So to be clear if i have some text as my right button on the navbar, I can't change its color, correct?
Why does barButtonIconStyle work but barButtonTextStyle not work?

I attached the image and here is my code:

Router 
        sceneStyle={styles.sceneStyle} 
        backButtonTextStyle={styles.backButtonTextStyle} 
        barButtonIconStyle={styles.barButtonIconStyle}

const styles = {
    sceneStyle: {
        paddingTop: 65
    },
    backButtonTextStyle: {
        color: '#2227b7'
    },
    barButtonIconStyle: {
        tintColor: '#2227b7'
    }
};
![screen shot 2017-04-09 at 8 24 58 pm](https://cloud.githubusercontent.com/assets/2787765/24844927/ea5105ec-1d62-11e7-82df-b2c97c77d44c.png)

**Comment by sicdigital** [comment] 2017-04-14 20:28
@brownmagik352 -- What you're looking for is the prop `rightButtonTextStyle` that will do it.

**Comment by brownmagik352** [comment] 2017-04-18 02:47
@sicdigital thanks for the tip!

so `barButtonIconStyle` & `rightButtonTextStyle` got me what I was looking for:

![screen shot 2017-04-17 at 7 46 26 pm](https://cloud.githubusercontent.com/assets/2787765/25112524/abbefca4-23a6-11e7-8b0c-b6f5b10c3151.png)
![screen shot 2017-04-17 at 7 46 38 pm](https://cloud.githubusercontent.com/assets/2787765/25112526/ad3ca572-23a6-11e7-86b6-48a520e2b3aa.png)

**Comment by alexTitakoff** [comment] 2017-06-21 08:27
Hello, guys!

Is it possible set styles for NavBar into Component of called Scene, no in an attribute of Scene Tag in Router Tag?

**Comment by rajsuvariya** [comment] 2017-07-25 12:56
@aksonov Is it possible to change the font in the nav bar title. I already tried 
```
  <Router titleStyle={{ color: 'red', fontFamily: "pfencoresanspro_book" }} headerTitleStyle={{ color: 'blue', fontFamily: "pfencoresanspro_book" }}>
```
But it isn't working

**Comment by aksonov** [comment] 2017-07-25 13:03
`titleStyle` definitely works for me with v4. If it doesn't work please create separate issue for v4 version and give me link to cloned & modified Example so I can reproduce issue.

**Comment by rajsuvariya** [comment] 2017-07-25 13:23
Looks like issue with React Native as mentioned here.
https://github.com/react-community/react-navigation/issues/542#issuecomment-283663786

**Comment by aksonov** [comment] 2017-07-25 13:27
No, it works well on my project. Probably you didn't import your fonts properly via XCode

**Comment by rajsuvariya** [comment] 2017-07-25 13:37
I was able to fix it using fontWeight: "100" as mentioned in the comment.

**Comment by golestanirad** [comment] 2017-08-15 01:00
I am using react-native-router-flux 4.0.0-beta.17 for my learning project. I need to customize the header. for instance the background color, the title alignment, etc. where can I find a comprehensive document?

**Comment by golestanirad** [comment] 2017-08-15 01:05
@sicdigital   hi there, where can I find a comprehensive document about all props?

**Comment by dcgray85** [comment] 2017-09-18 14:55
Is there a way to disable dynamic text in the header?  When the user allows dynamic text, I can disable this in the Scenes, but I can't in the header.  I would expect `allowFontScaling={false}` to be able to be applied to the header text.

![image](https://user-images.githubusercontent.com/7595504/30548206-8d485a9a-9c5f-11e7-81f4-069af7243514.png)

**Comment by Friis1978** [comment] 2018-02-14 14:26
Just to clarify everything. 
I have styled everything in the header this way:

<Router 
            navigationBarStyle={styles.navBar} 
            titleStyle={styles.navBarTitle}
            barButtonTextStyle={styles.barButtonTextStyle}
            barButtonIconStyle={styles.barButtonIconStyle}
            sceneStyle={styles.routerScene}
            rightButtonStyle={styles.rightButton}
            rightButtonTextStyle={styles.rightButtonText}
            tintColor='white'
            headerBackTitle={'Tilbage'}
        >

and the styles:

const styles = {
    navBar: {
        backgroundColor: '#ff8c00',
        height: 70
    },
    navBarTitle: {
        color: '#FFFFFF',
        fontSize: 20
    },
    barButtonTextStyle: {
        color: 'red'
    },
    barButtonIconStyle: {
        tintColor: 'white'
    },
    routerScene: {
        paddingTop: 80,
    },
    rightButton: {
        marginTop: 5,
        marginRight: 5,
        backgroundColor: 'white',
        borderRadius: 5,
        borderWidth: 1,
        borderColor: '#00b8ff'
    },
    rightButtonText: {
        color: '#00b8ff'

    }
`};

<img width="438" alt="screenshot 2018-02-14 15 24 32" src="https://user-images.githubusercontent.com/36473387/36209165-4f0c8e66-119b-11e8-89fc-c13963f7bc89.png">
` 
This is how it looks

**Comment by CeamKrier** [comment] 2019-07-18 18:37
I got it to work with the following props:

![image](https://user-images.githubusercontent.com/18554425/61482766-0e3b2a80-a9a4-11e9-97d5-fd461e106249.png)

![image](https://user-images.githubusercontent.com/18554425/61482808-2a3ecc00-a9a4-11e9-9df9-7d379ae45a4d.png)

**Comment by emiliodacosta** [comment] 2019-12-17 18:19
> Were you able to fix this??

**Comment by emiliodacosta** [comment] 2019-12-17 18:20
> > ![screen shot 2015-12-21 at 8 01 08 am](https://cloud.githubusercontent.com/assets/6411014/11931296/47f60970-a7b9-11e5-9c01-3aebf23411de.png)
> > Any way to kill the borderbottom of the navbar? Can I just remove it or make it the same color as the nav.
> 
> Were you able to fix this?

also looking for the prop that will allow me to change the color of the bottom border
