### ISSUE TITLE
question about back button in example app

### ISSUE THREAD

**Issue by oneroman** [aksonov/react-native-router-flux#3347] opened 2018-11-06 18:15 UTC
Hi there,

I just installed [your demo app](https://github.com/aksonov/react-native-router-flux/tree/master/examples/react-native) on Android and it seems it uses
`
 "react-native-router-flux": "^4.0.4",
`
and when I stay on first screen and hit back button then nothing happens (I am not able to quit the app). is it exactly how it suppose to work?

**Comment by aksonov** [comment] 2018-11-06 19:34
It is not good and should be fixed for sure. Unfortunately I don’t have enough time to work on it, PR is welcome!

**Comment by aksonov** [comment] 2018-11-10 17:36
Duplicate of #3337

**Closed by aksonov** 2018-11-10 17:36 UTC
Labels: bug, help wanted

**Comment by saibharani** [comment] 2018-12-14 07:10
if anyone else has the same problem i have a temporary workaround for this problem. Add the following code to the class where you declare your router. That way you can have a way to exit app by using back button in Android
`import {BackHandler} from 'react-native'
  componentDidMount(){
  BackHandler.addEventListener('hardwareBackPress', function() {
  if (Actions.currentScene == 'scarlet')
    BackHandler.exitApp()
});
  }

componentWillUnmount(){
  BackHandler.removeEventListener('hardwareBackPress', function() {
    if (Actions.currentScene == 'your home screen name')
      BackHandler.exitApp()
  })
}`
and remember to change 'your home screen name' to the home screen key of your app.
