### ISSUE TITLE
Failed at the react-native-router-flux@4.0.0-beta.7 postinstall script 'opencollective postinstall'.

### ISSUE THREAD

**Issue by AlmogRnD** [aksonov/react-native-router-flux#2008] opened 2017-07-11 01:34 UTC
Can't install the package 

~/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp(branch:development*) » npm i react-native-router-flux --save                            Almog@Almogs-MacBook-Pro

> react-native-router-flux@4.0.0-beta.7 postinstall /Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-router-flux
> opencollective postinstall

sh: opencollective: command not found
npm WARN enoent ENOENT: no such file or directory, open '/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-drawer-layout/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-drawer-layout-polyfill/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-tab-view/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-navigation/package.json'
npm WARN react-native-elements@0.13.0 requires a peer of react-native-vector-icons@~4.1.1 but none was installed.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/Almog/.nvm/versions/node/v6.9.5/bin/node" "/Users/Almog/.nvm/versions/node/v6.9.5/bin/npm" "i" "react-native-router-flux" "--save"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! react-native-router-flux@4.0.0-beta.7 postinstall: `opencollective postinstall`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-native-router-flux@4.0.0-beta.7 postinstall script 'opencollective postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-native-router-flux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     opencollective postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-native-router-flux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-native-router-flux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/npm-debug.log
------------------------------------------------------------

**Comment by AlmogRnD** [comment] 2017-07-11 01:35
beta v6 works - npm i react-native-router-flux@4.0.0-beta.6 --save

**Comment by aksonov** [comment] 2017-07-11 06:32
@xdamman Could you look at it?

**Comment by aksonov** [comment] 2017-07-11 08:09
@AlmogRnD Please try yarn `yarn add react-native-router-flux@4.0.0-beta.7`
@xdamman may fix it for npm, for next beta, I guess...

**Comment by AlmogRnD** [comment] 2017-07-11 09:10
@aksonov thanks, Yarn works

**Comment by xdamman** [comment] 2017-07-11 16:56
Thanks for bringing my attention to this. What node version are you using? On a Mac?
I cannot reproduce it yet.
This is what I see ![](https://cl.ly/0t3p2S3y3s1z/Screen%20Shot%202017-07-11%20at%206.19.07%20PM.png)

**Comment by aksonov** [comment] 2017-07-11 16:56
Mac, npm 4.2.0

**Comment by xdamman** [comment] 2017-07-11 16:59
and actually all the answers to my questions where in the log above ¯\_(ツ)_/¯
node v6.9.5
npm v3.10.10

Still digging into this.

**Comment by xdamman** [comment] 2017-07-11 17:03
works for me with node v6.95 and npm v.3.10.10 🤔
and `opencollective` is not in my PATH. Not sure what else I can try...

**Comment by xdamman** [comment] 2017-07-11 17:08
So basically, this means that somehow it didn't link `./node_modules/.bin/opencollective` to `./node_modules/opencollective/dist/bin/opencollective.js` OR that it doesn't add automatically `./node_modules/.bin/` to the PATH when running npm install.

**Comment by aksonov** [comment] 2017-07-12 17:09
@xdamman Could we just run ./node_modules/.bin/opencollective instead to avoid that?

**Comment by xdamman** [comment] 2017-07-12 17:32
Does it work for you locally when you change the postinstall script to that command? (I couldn't reproduce the issue so cannot test)

**Comment by aksonov** [comment] 2017-07-12 17:44
@xdamman Yes, it works. I've just submitted it to PR #2015

**Comment by xdamman** [comment] 2017-07-12 18:16
Good to know that it solved the issue. That's weird that somehow npm is not considering ./node_modules/.bin as a source of executable files in your setup (but it does in mine). Curious if others have the same issue. 

Thanks for spending the time to figure this out 👍

**Comment by aksonov** [comment] 2017-07-13 06:00
Should be fixed with v4 beta.8

**Closed by aksonov** 2017-07-13 06:00 UTC

**Comment by OrangeFlavoredColdCoffee** [comment] 2018-07-30 11:11
<img width="638" alt="image" src="https://user-images.githubusercontent.com/15223345/43394164-4f8ecc82-942c-11e8-90c0-fbfa22e394fc.png">

**Comment by apoterenko** [comment] 2018-09-11 13:35
![image](https://user-images.githubusercontent.com/12325691/45363644-b217b500-b5e0-11e8-88e1-7d3a03c9c913.png)

**Comment by apoterenko** [comment] 2018-09-11 13:37
~Two days ago that was working fine.

**Comment by daviscabral** [comment] 2018-09-11 21:04
Thank you for reporting - but beta versions are not supported. 

You can use `resolutions` in your `package.json` to lock the `opencollective` version to one that might work in your environment.
