### ISSUE TITLE
how to change android animation direction

### ISSUE THREAD

**Issue by scriptfans** [aksonov/react-native-router-flux#2177] opened 2017-08-03 08:09 UTC
### Version

- react-native-router-flux v4.0.0-beta.14
- react-native v0.46.4

### Expected behaviour
 the new scene should be animated horizontal.

### Actual behaviour
on Android, It's animated from bottom to top, but there is no problem with iOS, how to change it use horizontal direction? thanks.

![untitled](https://user-images.githubusercontent.com/359790/28912194-de1b5e22-7865-11e7-9d88-ae1c260979a5.gif)

**Comment by aksonov** [comment] 2017-08-03 08:19
You should use 'modal' prop for container Scene for bottom to top animation

**Comment by scriptfans** [comment] 2017-08-03 08:28
@aksonov but I want to use left-right animation, It now always from bottom to top on android. this is my code:
`
<Router getSceneStyle={getSceneStyle}>

        <Scene hideNavBar>

          <Scene key="launch" component={Launch} type='reset' initial />

          <Scene key="login" component={Login} type='reset' />

          <Scene key="sign_up" component={Registration} />

          <Scene key="home" component={Home} />
        </Scene>
      </Router>
`

**Comment by aksonov** [comment] 2017-08-03 08:30
Oh I misunderstood then. It is really strange, could you check pure react-navigation demos on Android? RNRF uses react-navigation internally. Could you reproduce this issue on Example project from this repo?

**Comment by scriptfans** [comment] 2017-08-03 08:34
thanks for reply, there is no problem with iOS:
![untitled](https://user-images.githubusercontent.com/359790/28913105-7325f010-7869-11e7-92a2-e5a77ab7fa80.gif)
I will test the demo code on Android, thanks.

**Comment by scriptfans** [comment] 2017-08-03 09:11
@aksonov Demo code has the same problem on android:

![untitled](https://user-images.githubusercontent.com/359790/28914547-a5e9583e-786e-11e7-8601-0ec931a11b9d.gif)

so is it a bug?

**Comment by aksonov** [comment] 2017-08-03 09:13
Yes, it is a bug. Let's find where is it - within RNRF or within react-navigation.  Try this intro: https://reactnavigation.org/docs/intro/

**Comment by aksonov** [comment] 2017-08-03 09:14
Ops, looks like it is not bug but a "feature"  - I see the same behaviour at that tutorial for Android!

**Comment by scriptfans** [comment] 2017-08-03 09:22
omg.

**Comment by aksonov** [comment] 2017-08-03 09:34
https://github.com/react-community/react-navigation/issues/1400

**Comment by aksonov** [comment] 2017-08-07 11:30
It is default android behaviour, closing the ticket.

**Closed by aksonov** 2017-08-07 11:30 UTC

**Comment by Devansh-Sanghvi** [comment] 2017-10-27 09:02
i am facing the same, is it possible for us to change transition animation

**Comment by Blapi** [comment] 2017-12-07 16:22
@Devansh-Sanghvi  check #2628

**Comment by sogangCSmaster** [comment] 2020-04-05 13:30
> You an use your custom transition effects like as follow:
> 
> ```
> import StackViewStyleInterpolator from 'react-navigation-stack';
> 
> <Scene
> key='main'
> hideNavBar
> transitionConfig={transitionConfig}
> >
> 
> ...more scenes
> 
> </Scene>
> 
> const MyTransitionSpec = ({
>     duration: 1000,
>     // easing: Easing.bezier(0.2833, 0.99, 0.31833, 0.99),
>     // timing: Animated.timing,
> });
> 
> const transitionConfig = () => ({
>     transitionSpec: MyTransitionSpec,
>     // screenInterpolator: StackViewStyleInterpolator.forFadeFromBottomAndroid,
>     screenInterpolator: sceneProps => {
>         const { layout, position, scene } = sceneProps;
>         const { index } = scene;
>         const width = layout.initWidth;
> 
>         //right to left by replacing bottom scene
>         // return {
>         //     transform: [{
>         //         translateX: position.interpolate({
>         //             inputRange: [index - 1, index, index + 1],
>         //             outputRange: [width, 0, -width],
>         //         }),
>         //     }]
>         // };
> 
>         const inputRange = [index - 1, index, index + 1];
> 
>         const opacity = position.interpolate({
>             inputRange,
>             outputRange: ([0, 1, 0]),
>         });
> 
>         const translateX = position.interpolate({
>             inputRange,
>             outputRange: ([width, 0, 0]),
>         });
> 
>         return {
>             opacity,
>             transform: [
>                 { translateX }
>             ],
>         };
> 
>         //from center to corners
>         // const inputRange = [index - 1, index, index + 1];
>         // const opacity = position.interpolate({
>         //     inputRange,
>         //     outputRange: [0.8, 1, 1],
>         // });
> 
>         // const scaleY = position.interpolate({
>         //     inputRange,
>         //     outputRange: ([0.8, 1, 1]),
>         // });
> 
>         // return {
>         //     opacity,
>         //     transform: [
>         //         { scaleY }
>         //     ]
>         // };
>     }
> });
> ```

This does not work..using RNRF v4.2.0
