### ISSUE TITLE
Session to Login Screen Redirect

### ISSUE THREAD

**Issue by stevefox** [aksonov/react-native-router-flux#253] opened 2016-02-25 14:26 UTC
I am building a session screen and found I haven't been able to get the redirect to work before the first render. If I put `Actions.RouteLogin()` in `componentDidMount`, it also does not redirect. If I do anything that triggers the view to re-render, or if I put it in an `onPress` handler, then it works fine. Is that why you suggest within `setTimeout` in #228? The route type currently is `replace` if that's relevant.

Here's the simplified example.
```javascript
    render: function() {
            Actions.RouteLogin();
        return (
                <View>
                <Tex>Test</Text>
                </View>
        );
  }
```

**Comment by aksonov** [comment] 2016-02-25 16:28
Yes, you need to run action in next cycle, even with standalone navigator you have to do it. Duplicate of #228.

**Closed by aksonov** 2016-02-25 16:28 UTC

**Comment by xinranw** [comment] 2016-03-03 02:53
Sorry, wanted to follow up on this question. I tried the above implementation but seems the redirect function, in this case `Actions.RouteLogin()` gets called twice, with the result being the `RouteLogin` view being displayed twice. Any idea why that's happening/
