### ISSUE TITLE
com.facebook.react.modules.core.JavascriptException: undefined is not an object (evaluating 'e.children[e.index].sceneKey')

### ISSUE THREAD

**Issue by jpapillon** [aksonov/react-native-router-flux#1175] opened 2016-09-15 16:50 UTC
I noticed a crash in my app which would through this exception:
com.facebook.react.modules.core.JavascriptException: undefined is not an object (evaluating 'e.children[e.index].sceneKey')

I haven't found steps to reproduce (since it doesn't happen often) but I found where it could come from in this library:
1. https://github.com/aksonov/react-native-router-flux/blob/master/src/Reducer.js#L151
2. https://github.com/aksonov/react-native-router-flux/blob/master/src/Reducer.js#L228
3. https://github.com/aksonov/react-native-router-flux/blob/master/src/Reducer.js#L241

Shouldn't there be a check to make sure we have an actual child for `state.children[state.index]`?

I'm using these version:
- react-native-router-flux v3.35.0
- react-native v0.32.0

**Comment by taliasegev** [comment] 2017-01-02 16:38
Hi,
I happened to me too - 
Fatal Exception: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'e.children[e.index].sceneKey')

Please update us if there is a fix for this subjetct. I'm using 
"react-native-router-flux": "^3.37.0"

Thanks,

Talia

**Comment by dmwallace** [comment] 2017-06-29 11:03
I'm getting the same error.  It seems to be caused by triggering a scene change action on startup (e.g. showing a nag screen) before the scene object exists.  I have delayed the call until the router's onComponentDidMount function.  The only workaround I've found is delay the scene change using setTimeout

**Closed** 2017-07-08 04:59 UTC
