### ISSUE TITLE
Module AppRegistry is not a registered callable module

### ISSUE THREAD

**Issue by sriraman** [aksonov/react-native-router-flux#217] opened 2016-02-17 05:07 UTC
I'm getting the following error

`React-Native: Module AppRegistry is not a registered callable module`

when I'm trying to run the example code. I installed all the dependencies. I have searched in google and tried the available fixes like `./gradlew clean` and build etc., But, those fixes didn't help. 

This might be a silly mistake. Since I'm new to react native, I couldn't fix it. Can anyone help me? If you need any other details, let me know.

**Comment by liangmicha** [comment] 2016-03-14 07:29
@sriraman  were you able to figure this out? I'm running into the same issue.

**Comment by TeodorKolev** [comment] 2016-03-14 12:51
same here

**Comment by adrienthiery** [comment] 2016-03-14 20:55
I don't know if it helps, but this happened on my project and the only thing that fixed it is to delete the whole folder, reclone and reinstall all npm packages...

**Comment by aksonov** [comment] 2016-03-16 21:55
Cannot reproduce it, please check latest 3.0 release, closing it for now (because ticket was for 2.x)

**Closed by aksonov** 2016-03-16 21:55 UTC
