### ISSUE TITLE
app can not exit in initial page

### ISSUE THREAD

**Issue by Maxitk** [aksonov/react-native-router-flux#2612] opened 2017-11-10 09:52 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.23 (v3 is not supported)
- react-native v0.44.3

### Expected behaviour
exit app at initial page when I perform backpress

### Actual behaviour
nothing happened

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1.I have the same code in v3,but it works
2.when I upgrade to the newest version,it has this problem
: I have added <Router> and backAndroidHandler func,when I perform backpress,it does't call,what's the problem?
3.another thing is when I add <Router>,the initial page will render twice,and show warns on  debugging

thanks,and i love this guy(router-flux) so much

**Comment by aksonov** [comment] 2017-11-10 09:54
Duplicate of #2413

**Closed by aksonov** 2017-11-10 09:54 UTC

**Comment by Maxitk** [comment] 2017-11-10 09:57
has it solved in current version?
