### ISSUE TITLE
Tab screens have no sliding animation

### ISSUE THREAD

**Issue by SourceCipher** [aksonov/react-native-router-flux#3170] opened 2018-08-11 10:47 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux4 .0.0-beta.40
- react-native 0.55.4

### Expected behaviour

Calling the tab screen from the tabs component (or any other) with the `Actions.jump('key')` should slide to that screen with the sliding animation

### Actual behaviour

Instead of sliding with the animation it will instantly jump to the screen. Even if im on the initial screen with the tabs and press on my custom header profile button, it will jump to the tab without animation. And then pressing on another icon to go back to the middle tab by Actions.pop('key') will slide back to the initial tab with the animation.

### Code

My scene structure:
```
 <Scene key="tabbar" tabs={true} tabBarPosition='top' tabBarComponent={() => null} hideNavBar >
   <Tabs key="contacts" component={Contacts} hideNavBar />
   <Tabs key="chats" component={Chats} hideNavBar initial={true} />
   <Tabs key="profile" component={Profile} hideNavBar />
</Scene>
```

Calling from my custom header ` onPress={() => Actions.jump('_profile')}` will switch to the profile tab without any animation

**Comment by daviscabral** [comment] 2018-09-01 22:36
Could you update to the most recent version and see if it works with your app and fix this issue?

**Comment by aksonov** [comment] 2018-09-05 11:48
@daviscabral  Just verified that it works (latest master, `github:aksonv/react-native-router-flux#master`) with addition of `legacy` attribute to `Tabs`. But I don't see tab bar anymore, is it intended?

**Comment by aksonov** [comment] 2018-09-05 12:01
Duplicate of #3163

**Closed by aksonov** 2018-09-05 12:01 UTC
Labels: needs response from author

**Comment by daviscabral** [comment] 2018-09-06 04:54
@aksonov not sure if I understand - it is not showing the tab bar at all?

**Comment by daviscabral** [comment] 2018-09-06 04:58
I got it now - it was not the intention.

**Comment by mog3n** [comment] 2018-09-12 05:16
@SourceCipher @aksonov were you able to get it working? I have the same problem as you- when a call Actions.jump('key'), it does not seem to animate (transition left/right) to the appropriate tab.

`<Scene
                    tabs
                    legacy
                    showLabel={false}
                    swipeEnabled={true}
                    tabBarPosition="top"
                    hideTabBar
                    key="main"
                    >

                    <Scene title="messages" icon={Icon}>
                        <Scene initial component={Chats} key="chat"/>

                        <Scene
                            key="chatDetail"
                            component={ChatScreen} 
                            />
                    </Scene>

                    <Scene key="home" title="home" icon={Icon} initial component={Home} />

                    <Scene title="me" icon={Icon}>
                        <Scene
                            key="profile"
                            initial
                            component={Profile}
                        />
                        <Scene
                            key="editBio"
                            component={EditBio}
                        />
                    </Scene>

                </Scene>`

In the Scene `home`, I'm able to swipe left and right (using my finger) to transition between screens, but when I call the function `Actions.jump('messages')`, it does not show the sliding transition. Is there something wrong with my code?

**Comment by aksonov** [comment] 2018-09-12 05:54
@daviscabral Could you fix tabbar for legacy before releasing of new version?

**Comment by aksonov** [comment] 2018-09-12 06:03
@mog3n You have to use latest master and `legacy` param for `tabs` scene. But now it works without `tabbar`...
