### ISSUE TITLE
ActionSheets

### ISSUE THREAD

**Issue by wootwoot1234** [aksonov/react-native-router-flux#679] opened 2016-05-15 17:03 UTC
I read in the readme that PR with alternatives to ActionSheets are welcome.  What did you all have in mind?  Why aren't ActionSheets supported?  Happy to lend a hand.

**Comment by charpeni** [comment] 2016-05-16 17:53
Thank you for asking.

cc @aksonov.

**Comment by aksonov** [comment] 2016-05-17 07:37
@wootwoot1234 You may check existing Modal, TabBar and do the same for ActionSheet.

**Comment by yulinho** [comment] 2016-05-19 11:54
no actionSheet in 3.x ?

**Comment by sibeliusseraphini** [comment] 2016-05-28 14:08
You can use this https://github.com/exponentjs/react-native-action-sheet

**Comment by sibeliusseraphini** [comment] 2016-05-28 14:11
@aksonov ActionSheets should not be a responsability of this package

**Comment by rturk** [comment] 2016-05-28 17:48
@sibeliusseraphini this makes sense. My App uses both RNRF and Expoent's react-native-action-sheet with no issues. Benefit of this setup is that is compatible with Both IOS and Android.

@wootwoot1234 PR's are still welcome, although I'm not sure if this will be a duplicated effort considering that Expoentjs/react-native-action-sheet works with RNRF

**Comment by wootwoot1234** [comment] 2016-05-28 22:03
@rturk I was under the impression it didn't work.  @aksonov why does it say it doesn't work in the readme?  Glad to hear it does.

**Comment by aksonov** [comment] 2016-05-30 16:30
Maybe here is some misunderstanding. Sure any component will work with RNRF, but it would be great to have something like Actions.sheet({...}) and see actionsheet, without wrapping anything like exponent's requires. version 2 allowed such easy usage, v3 doesn't.

**Comment by wootwoot1234** [comment] 2016-05-30 16:37
Ok, yeah.  There was some misunderstanding on my part.  Can you update the readme so that's clearer?  I would say something like:

"No built in Action Sheet like v2.  If you want to use Action Sheets you'll need to use a 3rd party module."

**Comment by sibeliusseraphini** [comment] 2016-05-30 16:47
@wootwoot1234 please submit a PR to update the readme, please also add a link to react-native-action-sheet there.

I think we can close this issue cc @rturk

**Closed** 2016-06-06 10:06 UTC
Labels: discussion, enhancement, question

**Comment by MovingGifts** [comment] 2016-09-11 20:18
@rturk Can you briefly show how you got react-native-action-sheet to work with RNRF? When trying to integrate react-native-action-sheet with RNRF, I get errors, on PropTypes not being defined, and it goes away when I add PropTypes to the react-native imports, but another error on func, "Cannot read property 'func' of undefined"

I followed their docs, and when it comes to the part where you wrap your app:
```
render() {
    return (
      <ActionSheet ref={component => this._actionSheetRef = component}>
        // Render the rest of your app here.
      </ActionSheet>
    );
  }
```
I wrapped the Router with all its scenes like this:
```
render() {
    return (
      <ActionSheet ref={component => this._actionSheetRef = component}>
        // Render the rest of your app here.
       <Router createReducer={reducerCreate} getSceneStyle={getSceneStyle}>
         // all scenes here
       </Router>
      </ActionSheet>
    );
  }
```
But still getting the issue "Cannot read property 'func' of undefined" in the actual component where I am trying to use the action sheet. The component uses exactly the react-native-action-sheet method of integration their documentation showed. I think the issue is related to an incorrect integration by me with RNRF wrapping the app part.

Can you please share how you integrated it correctly?
