### ISSUE TITLE
Animation?

### ISSUE THREAD

**Issue by cwahlfeldt** [aksonov/react-native-router-flux#2135] opened 2017-07-28 19:47 UTC
### Version
- react-native-router-flux v4.0.0-beta.14

I cant seem to stop animations or use any of the old props such as duration={0}. How do I customize animation or get rid of animation in v4?

**Comment by aksonov** [comment] 2017-07-29 10:11
Duplicate of #2042

**Closed by aksonov** 2017-07-29 10:11 UTC

**Comment by aksonov** [comment] 2017-08-21 13:01
Please check latest master, it supports `duration={0}` for stack container (check Example project, 'Register' stack)
