### ISSUE TITLE
undefined is not an object (evaluating 'route.routeName')

### ISSUE THREAD

**Issue by Shariaty** [aksonov/react-native-router-flux#2720] opened 2017-12-19 11:44 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.24 (v3 is not supported)
- react-native v0.51.0

### get this error when using Drawer in my app.js
undefined is not an object (evaluating 'route.routeName') !!?

![capture](https://user-images.githubusercontent.com/21170564/34155324-26a58800-e4ce-11e7-8a1f-997b1fe7aaa3.JPG)

My App.js is simple and it is a fresh react native installation only with router flux, and error happens when i use **contentComponent** in Drawer

```
import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View} from 'react-native';
import {Router , Scene }  from 'react-native-router-flux';
import Home from './src/components/Home';
import About from './src/components/About';
import SideMenu from './src/components/SideMenu';
import splashScreen from './src/components/splashScreen';

export default class App extends Component {
  render() {
    return (
      <Router>
          <scene hideNavBar>
              <Scene key="root">
                    <Scene key="drawer" drawer contentComponent={SideMenu}>
                      <Scene key="Home" component={Home} title="HomePage" initial/>
                      <Scene key="About" component={About} title="Second Page"/>
                    </Scene>
              </Scene>
          </scene>
      </Router>
    );
  }
}
 
```

it made me crazy !! any one has facing this issue !!?

**Comment by Blapi** [comment] 2017-12-19 11:52
You've got a typo in your code (you wrote `scene` with a lowercase S at a point.

Still, it's a duplicate of #2718 and it looks like the error is from react-navigation.

**Closed by Blapi** 2017-12-19 11:52 UTC

**Comment by shubham81407** [comment] 2017-12-20 04:00
I have the same issue with this code:-
react-native-router-flux: 4.0.0-beta.22
react-native: 0.49.3
```
<Router
    backAndroidHandler={() => Actions.pop()}
    sceneStyle={styles.sceneStyle}
  >
    <Scene key="root">
      <Scene
        key="scene1"
        component={Scene1}
        title="Scene 1"
        navigationBarStyle={styles.navigationBarStyle}
        navBarButtonColor={styles.navBarButtonColor}
        titleStyle={styles.titleStyle}
        initial
      />
      <Drawer
        hideNavBar
        key="dashboard"
        drawerImage={Images.menuIcon}
        contentComponent={Navigation}
        drawerWidth={styles.drawerWidth}
      >
        <Scene
          key="dashboard"
          component={Dashboard}
          title={strings.dashboard}
          navigationBarStyle={styles.navigationBarStyle}
          navBarButtonColor={styles.navBarButtonColor}
          titleStyle={styles.titleStyle}
          renderRightButton={renderNotificationButton}
        />
      </Drawer>
    </Scene>
  </Router>

```

**Comment by vibhavagarwal5** [comment] 2017-12-28 15:38
try this drawer component 
                       <Drawer
                        hideNavBar
                        key='drawer'
                        contentComponent={DrawerContent}
                        drawerWidth={250}
                        drawerOpenRoute = 'DrawerOpen' //maybe these 3 are missing so the problem
                    	drawerCloseRoute = 'DrawerClose'
                    	drawerToggleRoute = 'DrawerToggle'>

**Comment by AKMaS** [comment] 2017-12-29 07:47
@vibhavagarwal5    thanks,it works for me.is it a bug or?

**Comment by vibhavagarwal5** [comment] 2017-12-29 07:54
Its not a bug @AKMaS but a lack of documentation in this repo and the example given!
