### ISSUE TITLE
Is there anyway for passing props from drawer to nested scene?

### ISSUE THREAD

**Issue by whalswo7777** [aksonov/react-native-router-flux#3132] opened 2018-07-17 20:28 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.31 (v3 is not supported)
- react-native v0.55.2

### Expected behaviour
![image](https://user-images.githubusercontent.com/29480583/42843361-b4a089de-89c4-11e8-9ebe-6cf26e6a0c4d.png)

Actually, I want to passing props("Recent_Measurement") from drawer(in this case, "main_tab") to its nested scence ("measure_tab"). 
However, whenever I try to pass props to nested scene, it cannot recognize.

For reference, below figure is about my router-flux structure.
![image](https://user-images.githubusercontent.com/29480583/42843545-3f57aab2-89c5-11e8-8c2f-49a6b4427533.png)

**Comment by aksonov** [comment] 2018-08-08 15:37
Duplicate of #2309

**Closed by aksonov** 2018-08-08 15:37 UTC
Labels: help wanted

**Comment by abdullateef97** [comment] 2019-07-11 22:13
@aksonov is there a way aroud this yet
