### ISSUE TITLE
Actions.login() doesn't work if login Scene has type='replace'

### ISSUE THREAD

**Issue by bosung90** [aksonov/react-native-router-flux#491] opened 2016-04-10 23:01 UTC
### Version
- react-native-router-flux v3.2.8
- react-native v0.23.1

### Expected behaviour
```<Scene key='login' component={LoginContainer} title='Login' panHandlers={null} type='replace'/>```
Calling Actions.login() should switch scene to `LoginContainer`

### Actual behaviour
```<Scene key='login' component={LoginContainer} title='Login' panHandlers={null} type='replace'/>```
Calling Actions.login() does **not** switch scene to `LoginContainer`

### Steps to reproduce

1. Ensure your Scene key='login'
2. Ensure your Scene type='replace'
3. Call Actions.login() from some other Scene (For example, splash)

**Comment by sylvainbaronnet** [comment] 2016-04-11 19:55
same issue with react-native v0.24.0-rc3

**Comment by paulbao** [comment] 2016-04-12 07:25
I have the same issue and tried to reproduce it on Example app. However, I cannot reproduce it on the Example app which is so wired...

**Comment by aksonov** [comment] 2016-04-12 07:37
Example app has replace action, could you check it?

**Comment by timzaak** [comment] 2016-04-12 15:36
I have tried Example app with react-native v0.24.0-rc4. there is something odd. It does not work correctly.
the NavBar changes correctly, But the component in the Scene does not change.

**Comment by sylvainbaronnet** [comment] 2016-04-12 15:40
Yes looks like the scene is loaded behind the current one

**Comment by codyhazelwood** [comment] 2016-04-12 17:48
I see this same issue.  It also seems to affect `type="reset"`.  Also here: #474

**Comment by evollu** [comment] 2016-04-13 17:07
I'm using Switch to get around the problem and it works correctly with v0.24.0-rc3.

**Comment by sylvainbaronnet** [comment] 2016-04-13 18:08
I guess the problem is in the reducer, here : https://github.com/aksonov/react-native-router-flux/blob/master/src/Reducer.js#L77

**Comment by sylvainbaronnet** [comment] 2016-04-13 19:58
I made some test and I can confirm that the scene is loaded correctly but displayed under the current one

**Comment by sylvainbaronnet** [comment] 2016-04-13 20:28
I think it's a problem with RN component `<NavigationCard/>` that use this style by default :
```
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
```

if I remove it my replace scene appear but then next one don't. I guess RN really need to support z-index now...

**Comment by aksonov** [comment] 2016-04-13 20:49
#525! Also duplicate of #474

**Closed by aksonov** 2016-04-13 20:49 UTC

**Comment by herby** [comment] 2016-04-20 21:58
I've got same problem - replace not working, component gets created, render is called, but blank screen is shown. Used 23, now 24, so that may be an issue. Will wait until version 3 will wortk fine.

**Comment by ruettiger** [comment] 2016-04-24 05:27
I got the same problem.

**Comment by aksonov** [comment] 2016-04-24 06:14
@ruettiger #525 ?
