### ISSUE TITLE
Redux state change in drawerchild

### ISSUE THREAD

**Issue by worms618** [aksonov/react-native-router-flux#2180] opened 2017-08-03 14:23 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.0-beta.14 (v3 is not supported)
- react-native v0.46.4
- Redux v3.7.2
- React-Redux v5.0.5

### Expected behaviour
When state changes, the child that is dispatching the actions, should rerender with the new redux state.

### Actual behaviour
When state changes, the top child will be rendered and apears on the screen.

### Steps to reproduce
1. Make a drawer with child scenes.
2. Dispatch redux-action on non-top child.

**Comment by aksonov** [comment] 2017-08-03 14:25
Please check pure react-navigation first. RNRF just creates react-navigation structures and pass state to it.

**Comment by bartaveld** [comment] 2017-08-03 14:28
I have the same problem and as far as I know (because I checked) there is noting stated in the RNRF documentation.

**Comment by aksonov** [comment] 2017-08-03 14:31
Stated what? About react navigation usage? Please fork & modify Example or create own project so I could reproduce issue. I can't work with code snippets or English wordings to reproduce issues.

**Comment by bartaveld** [comment] 2017-08-03 14:32
Stated as in: 'They are saying nothing about it'

**Comment by aksonov** [comment] 2017-08-03 14:34
I don't understand. RNRF is wrapper around react-navigation, so first I need to determine where the error is.

**Comment by aksonov** [comment] 2017-08-03 14:35
And I need reproducible iOS project. Example of 'good' issue that I solved:
https://github.com/aksonov/react-native-router-flux/issues/2115

**Comment by bartaveld** [comment] 2017-08-03 14:40
I'm working on it

**Comment by bartaveld** [comment] 2017-08-04 08:59
It's an issue in react-navigation I tested it

**Comment by aksonov** [comment] 2017-08-07 09:12
Have you created issue there? I guess you could use Actions.refresh to refresh screen if necessary. Closing this ticket for now

**Closed by aksonov** 2017-08-07 09:12 UTC
