### ISSUE TITLE
Navigation bar disappeared

### ISSUE THREAD

**Issue by paulxtiseo** [aksonov/react-native-router-flux#255] opened 2016-02-25 18:11 UTC
I recently upgraded my modules on an app I am building, and I can't display a navbar on one container where I was able to before. Here's the routes:

```
<Router name="root">
  <Route 
    name="launch"
    component={Launch} 
    initial={true}
    hideNavBar={true}
    sceneConfig={Navigator.SceneConfigs.FloatFromLeft}/>
  <Route 
    name="activityFeed" 
    component={ActivityFeed}
    title="Activity Feed"
    hideNavBar={false}
    sceneConfig={Navigator.SceneConfigs.FloatFromLeft}/>
</Router>
```

The activity feed scene is not displaying the navbar at all. Before the upgrade, it did. (I upgrade today from v2.2.4 to current.)

Any ideas on where to start looking?

**Comment by chetstone** [comment] 2016-02-26 19:37
I saw something similar, when I was trying to use the example from @nyura123's [PR](https://github.com/aksonov/react-native-tableview/pull/76)  for [react-native-tableview](https://github.com/nyura123/react-native-tableview/tree/2b39e7a1bd6fe7eef6880a3575d782d93ffe700e/examples/TableViewDemo). `hideNavBar={true}` was not working in the editing routes "Example with editing mode" and "Custom Editing Example". It should hide the main navbar and allow the route-specific navbar to be seen but did not. This seems to be fixed in 2.3.5. 

But now there is another regression: With 2.3.5 and clicking on any of the other (non-editing) routes, the Back button is missing from the navbar. This works fine in 2.1.8, and in 2.2.4, the back button is there but does not work.

**Comment by aksonov** [comment] 2016-02-26 19:57
@chetstone You are right, latest changes broke 'back' button functionality, didn't found the reason yet, reverted to old solution...

**Comment by paulxtiseo** [comment] 2016-02-26 20:00
Well, good to know I am maybe not the only one. :)

Another thing I noticed in trying to superficially debug, the repo's readme.md example shows a nested router (`<Router footer={TabBar} showNavigationBar={false}...`) with a `showNavigationBar` attribute? How does it differ from the `hideNavBar` one? The configuration table above it does not document it.

**Comment by aksonov** [comment] 2016-02-26 20:02
It should be the same as hideNavBar, i believe

**Comment by paulxtiseo** [comment] 2016-02-26 20:04
But, probably inversed? Meaning (showNavigationBar = true) === (hideNavBar = false)?

If so, that did not seem to alter the fact the the navbar is absent from my ActivityFeed screen.

**Comment by aksonov** [comment] 2016-02-26 20:11
Check latest version (2.3.6), if it doesn't work, please check demo, it hides/show navbar within tabbar.

**Comment by paulxtiseo** [comment] 2016-02-26 21:07
Yes, it works now.

**Comment by ws3li** [comment] 2016-02-26 23:07
Is the back button fixed yet? I still see the back button not being rendered properly. Thanks

**Comment by lrettig** [comment] 2016-02-27 00:22
same!

**Comment by lrettig** [comment] 2016-02-27 00:27
just tested, the back button issue first appeared in 2.3.4

**Comment by sulinixl** [comment] 2016-02-27 09:22
In the same case, NavigationBar disappeared in 2.2.7, and after upgrade RNRF to 2.3.6, NavigationBar appeared, but the back button disappeared again.

```js
var React = require('react-native');
var RNRF = require('react-native-router-flux');
var {Text, View, TouchableOpacity} = React;
var {Router, Route, Actions} = RNRF;
var Home = React.createClass({
    render(){
        return (
            <View style={{flex:1, alignItems: 'center', justifyContent: 'center'}}>
                <TouchableOpacity onPress={()=>{Actions.search();}}><Text>Hello world</Text></TouchableOpacity>
            </View>
        );
    }
});
var Search = React.createClass({
    render(){
        return (
            <View style={{flex:1, alignItems: 'center', justifyContent: 'center'}}>
                <Text>Search world</Text>
            </View>
        );
    }
});
var Launcher = React.createClass({
    render(){
        return (
            <Router name="root">
                <Route name="home" component={Home} initial={true} hideNavBar={true}/>
                <Route name="search" component={Search} hideNavBar={false}/>
            </Router>
        );
    }
});
module.exports = Launcher;
```
Above is an example, I hope it can help some.

**Comment by sulinixl** [comment] 2016-02-27 10:02
Maybe during routes switch, the NavBar doesn't change at all.
Check the code below, when route switch to search, **NavBar title is still 'Home Page', not 'Search **Page'.
```js
var React = require('react-native');
var RNRF = require('react-native-router-flux');
var {Text, View, TouchableOpacity} = React;
var {Router, Route, Schema, Actions} = RNRF;
var Home = React.createClass({
    render(){
        return (
            <View style={{flex:1, alignItems: 'center', justifyContent: 'center'}}>
                <TouchableOpacity onPress={()=>{Actions.search();}}><Text>Hello world</Text></TouchableOpacity>
            </View>
        );
    }
});
var Search = React.createClass({
    render(){
        return (
            <View style={{flex:1, alignItems: 'center', justifyContent: 'center'}}>
                <Text>Search world</Text>
            </View>
        );
    }
});
var Launcher = React.createClass({
    render(){
        return (
            <Router name="root">
                <Schema name="default" sceneConfig={React.Navigator.SceneConfigs.FloatFromRight}/>
                <Route name="home" title="Home Page" component={Home} initial={true}/>
                <Route name="search" title="Search Page" component={Search}/>
            </Router>
        );
    }
});
module.exports = Launcher;
```

**Comment by joshuarotenberg** [comment] 2016-02-28 13:52
:+1: my navbar is gone with the latest update also

**Comment by aksonov** [comment] 2016-02-29 11:26
Please check 2.3.7

**Comment by joshuarotenberg** [comment] 2016-02-29 13:27
@aksonov This appears to be fixed. THank You!

**Comment by sulinixl** [comment] 2016-02-29 14:40
Fixed, tks~

**Comment by aksonov** [comment] 2016-02-29 18:04
Added customization of nav bar again (2.3.7 is like 'reverted' version), please check 2.3.8, hope i didn't break it again ;)

**Comment by paulxtiseo** [comment] 2016-03-01 01:13
Updated. Works for me.

**Comment by sulinixl** [comment] 2016-03-01 04:07
2.3.8 works fine.

**Closed** 2016-03-01 09:18 UTC
