### ISSUE TITLE
[NAVBAR] NavBarTitleImage not centred with backButtonImage on Android

### ISSUE THREAD

**Issue by arribbar** [aksonov/react-native-router-flux#2505] opened 2017-10-13 14:20 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.?.? (v3 is not supported) v4.0.0-beta22
- react-native v0.47.1

### Expected behaviour
- NavBarTitleImage is always centred

### Actual behaviour
- It works perfectly on iOS but not on Android
- NavBarTitleImage is centred but when backButtonImage is displayed, NavBarTitleImage is moved on the right
- Using renderNavTitle does the same

![image](https://user-images.githubusercontent.com/5455462/31550718-84da106a-b032-11e7-9e90-316f15389056.png)

![image](https://user-images.githubusercontent.com/5455462/31550059-56bdc5ca-b030-11e7-8e67-28835f3ca33f.png)

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Create a navBarTitleImage
2. Go to a scene with back button
3. NavBarTitleImage is not centred

**Comment by aksonov** [comment] 2017-10-17 10:46
Please check latest master and PR #2491 (I've just merged it). Unfortunately I'm working on ios app only.

**Comment by aksonov** [comment] 2017-10-17 11:03
Duplicate of #2467

**Closed by aksonov** 2017-10-17 11:03 UTC
