### ISSUE TITLE
Disable open gesture for drawer.

### ISSUE THREAD

**Issue by antofa** [aksonov/react-native-router-flux#2347] opened 2017-09-07 14:27 UTC
### Version
- react-native-router-flux v4.0.0-beta.21
- react-native v0.48.0

### Expected behaviour

Drawer can't be open by gesture.

### Steps to reproduce
Is it possible to disable opening drawer by user gesture (allow open only by click on specific  button in navbar)?  I can't find how to do this in repository docs. Is there any workaround?

For android official component offers to use drawerLockMode (https://facebook.github.io/react-native/docs/drawerlayoutandroid.html#drawerlockmode)

**Comment by mcabs3** [comment] 2017-09-07 16:11
This project uses the [DrawerNavigator](https://reactnavigation.org/docs/navigators/drawer) from react-navigation. It looks like they don't have anything in their docs to support the behavior you are looking for.

**Comment by aksonov** [comment] 2017-09-10 06:05
It is not supported yet by react-navigation.

**Comment by hungdev** [comment] 2017-09-18 07:26
@aksonov 
https://github.com/react-community/react-navigation/pull/793

**Comment by pgonzalez-santiago** [comment] 2017-09-21 10:38
Any news regarding this? I wold like to disable gesture in some scenes.

**Comment by GuillaumeMunsch** [comment] 2017-10-02 13:33
If I'm not wrong this issue https://github.com/react-community/react-navigation/pull/1377 offers the possibility to do so in `react-navigation` and it has been merged to `master` 11 days ago and a new release of this package (`1.0.0-beta.13`) has been published to `npm` 5 days ago so I imagine this is in the new release.

Documentation has been updated here as well https://github.com/react-community/react-navigation/blob/17c910fb5d69e02ef4015dfbf6a83d07019f4d03/docs/api/navigators/DrawerNavigator.md#drawerlockmode

**Comment by Alexandersch** [comment] 2017-10-25 15:46
As a temporary workaround, this still works for me:

` 
static navigationOptions = (props) => {
    return ({
      drawerLockMode: 'locked-closed'
    })
  }
`

**Comment by GuillaumeMunsch** [comment] 2017-10-26 09:49
This is a workaround using plain `react-navigation` right ? This isn't using the API of RNRF

**Comment by omeraplak** [comment] 2017-10-26 10:43
@Alexandersch 
Hello,
Can you more explain how we can use?

**Comment by Alexandersch** [comment] 2017-10-26 10:47
@GuillaumeMunsch
Yes this is from react-navigation. But this still works.

@omeraplak
I've added this snippet to my Scene component class. No need to import stuff react-navigation. Because RNRF is using the react-navigation API in the background.

**Comment by Alexandersch** [comment] 2017-10-26 11:52
A better option would be to move the "drawerless" scenes outside of the drawer. At least in my case. Like so:

```
<Scene key='root' >

    <Drawer hideNavBar key="drawer" contentComponent={DrawerSideMenu} drawerIcon={HamburgerMenu}  >

        {/* THESE DO HAVE DRAWER MENU, BECAUSE THEY ARE INSIDE THE DRAWER */} 
        <Scene key="home" initial={true} component={Screens.HomeScreen} title="Webshop Home"  />
        <Scene key="categories" component={Screens.CategoriesScreen} title="Catalog" />
        <Scene key="cart" component={Screens.CartScreen} title="Shopping Cart" />
        <Scene key="login" component={Screens.LoginScreen} title="Login" />

    </Drawer>

    {/* THESE HAVE NO DRAWER MENU, ONLY BACK BUTTON */}   
    <Scene hideNavBar key="splash" initial={true} component={Screens.SplashScreen} title="Splash" />
    <Scene key="subCategories" back={true} component={Screens.SubCategoriesScreen}  />  
    <Scene key="products" back={true} component={Screens.CategoryProductsScreen} />
    <Scene key="product" back={true} component={Screens.ProductDetailScreen} />

</Scene>
```

Also, don't try to add nested stacknavigators inside the drawer. It will mess up things...

**Comment by tonygriv** [comment] 2017-12-22 13:24
Any updates about this?

**Comment by ital0** [comment] 2017-12-29 14:23
Also having the same issue.
Tried solution provided by @Alexandersch, but I can't disable swipe gesture :( probably I've did something wrong.

**Comment by aksonov** [comment] 2018-01-05 10:54
Interesting, now RNRF passed drawerLockMode to react-navigation correctly, but I don't see it works. I used 'locked-closed' but still can open drawer with the back gesture...

**Comment by YoranRoels** [comment] 2018-01-08 13:08
Worked for me by passing drawerLockMode={'locked-closed'} to the Drawer's child component (Tabs in my case).
Credits: https://github.com/aksonov/react-native-router-flux/issues/2566#issuecomment-355879991

**Comment by BenFausch** [comment] 2018-01-23 17:23
@YoranRoels you saved me! I see it working in a nexus 5 android emulator.

**Comment by gupta-ji6** [comment] 2018-06-04 11:06
Try this: 

```
const AppNavigator = StackNavigator(
  {
    // Drawer: { screen: Drawer },
    Register: {
      screen: Register,
      navigationOptions: ({ navigation }) => ({
        drawerLockMode: "locked-closed",
      })
    },
    TabHome: { screen: TabHome },
    Album: { screen: Album },
    offlineContent: { screen: offlineContent },
    changePassword: { screen: changePassword },
    Player: {screen: Player},
  },
  {
    initialRouteName: "TabHome",
    // header: null
  }
);
```

**Comment by gupta-ji6** [comment] 2018-06-04 11:06
```const AppNavigator = StackNavigator(  {    // Drawer: { screen: Drawer },    Register: {      screen: Register,      navigationOptions: ({ navigation }) => ({        drawerLockMode: "locked-closed",      })    },    TabHome: { screen: TabHome },    Album: { screen: Album },    offlineContent: { screen: offlineContent },    changePassword: { screen: changePassword },    Player: {screen: Player},  },  {    initialRouteName: "TabHome",    // header: null  });```

**Comment by aksonov** [comment] 2018-08-08 15:30
Please try to reproduce it with Example project and latest version 4.0.0-beta.40. Feel free to open if the issue still exists

**Closed by aksonov** 2018-08-08 15:30 UTC
Labels: bug, enhancement

**Comment by edoantonioco** [comment] 2018-12-19 01:50
This issue is a hard to fix for me.
First to all, I need to have the <Stack key="root" hideNavBar={false}> inside the <Drawer> tags because othewise props wont work properly. But having that Stack between the Drawer and the Scenes makes the `drawerLockMode` to not work at all.

So the way to fix a bug opens another bug

**Comment by munkhorgil** [comment] 2019-02-12 06:33
Anyone solved this issue?

**Comment by edoantonioco** [comment] 2019-02-13 16:54
> I have exact same architecture of router with you @edoantonioco, Did you find any solution?

Not at all. All we can do is to expect RNRF to support react navigation 3.0 and maybe there it might get fixed https://github.com/aksonov/react-native-router-flux/issues/3393

**Comment by edoantonioco** [comment] 2019-03-19 02:18
drawerLockMode="locked-closed" in child scenes (for the purpose of disabling drawer for specific screens like login) still doesnt work in 4.1.0-beta.2 (which is based in react navigation v3)

**Comment by edoantonioco** [comment] 2019-03-19 02:25
Tried 4.1.0-beta.2 (which is based in react navigation v3). Situation hasnt changed.

**Comment by LuisBonsembiante** [comment] 2019-04-04 18:49
the same error is happen yet
