### ISSUE TITLE
Tabs Dynamic / Conditional Scene rendering

### ISSUE THREAD

**Issue by tasharofi** [aksonov/react-native-router-flux#2715] opened 2017-12-19 03:37 UTC
- react-native-router-flux "^4.0.0-beta.22"
- react-native 0.50.3

### Expected behaviour
I need to dynamically render the tabs scene...for example user A does not have permission to access some app features which is on scene A so based on the user permission level the scene A wont be rendered for user A...

Is there any way to hide / not render some specific scene of Tabs ?

**Comment by as123456py** [comment] 2017-12-19 05:16
Duplicate of #2349
hope to be useful

**Closed** 2017-12-19 09:38 UTC

**Comment by lelup** [comment] 2018-02-08 04:01
you can duplicate and control tabbar when you click button loggin:

       <Scene key='upPortal' lazy={true} tabs={true} hideNavBar={true}  >
               <Scene key='index' title='index' hideNavBar={true} >
                    //other scene
               </Scene>
               <Scene key='project'  title='project'  hideNavBar={true} >
                   //other scene
               </Scene>
                 <Scene key='business'   title='business' hideNavBar={true} >
                        //other scene
                 </Scene>
               <Scene key='custom' title='custom'  hideNavBar={true} >
                       //other scene
               </Scene>
               <Scene key="myhome" title="myhome" hideNavBar={true} >
                   //other scene
                </Scene>
       </Scene>
        
        <Scene key='upPortal2' lazy={true} tabs={true} hideNavBar={true}  >
               <Scene key='index' title='index' hideNavBar={true} >
                    //other scene
               </Scene>
               <Scene key='project'  title='project'  hideNavBar={true} >
                   //other scene
               </Scene>
               <Scene key='custom' title='custom'  hideNavBar={true} >
                       //other scene
               </Scene>
               <Scene key="myhome" title="myhome" hideNavBar={true} >
                   //other scene
                </Scene>
       </Scene>
....
_checkTabbar() {
if (condition) {
Action.upPortal();
}
Action.upPortal2();
}
