### ISSUE TITLE
Duplicate versions of react-native being installed

### ISSUE THREAD

**Issue by brandon-dewitt** [aksonov/react-native-router-flux#1803] opened 2017-04-20 15:36 UTC
react-native-router-flux v3.38.1
react-native v0.42.3

yarn install is causing react-native v0.42.3 and react-native v0.41.1 to be installed

Should react and react-native be installed as a peerDependency for react-native-router-flux?

To repro:

react-native init {projectName}  --version=0.42.3
cd {projectName}
yarn add react-native-router-flux
npm start

You should see
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /Users/bdewitt/sandbox/break/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/bdewitt/sandbox/break/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /Users/bdewitt/sandbox/break/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/bdewitt/sandbox/break/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/bdewitt/sandbox/break/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/bdewitt/sandbox/break/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

yarn add react-native-router-flux@3.38.0

Should succeed

**Comment by SRandazzo** [comment] 2017-04-20 15:38
Came here to post the same issue, looks like it was accidentally added to the dependencies in this commit: https://github.com/aksonov/react-native-router-flux/commit/34e2d7ac7eb09489c2fd7f19844bd38e27e969fc

I believe It should be listed as a peerDependency instead

**Comment by MattyK14** [comment] 2017-04-20 18:00
I've been tearing my hair out over this issue, glad to come across the root of the problem

**Comment by lahaxearnaud** [comment] 2017-04-20 19:29
Same issue

**Comment by TimothePearce** [comment] 2017-04-20 21:08
Same here, please update the package

**Comment by n8stowell82** [comment] 2017-04-20 22:02
yeah this has been destroying my day as well.  as a quick work around, you can just go delete the dupe of react-native out of the node_modules folder within react-native-router-flux.  Ugly, but will at least get you up and running for the time being

**Comment by diegorodriguesvieira** [comment] 2017-04-21 02:07
+1

**Comment by sil218** [comment] 2017-04-21 05:54
reinstall 3.38.0 for now
npm install --save react-native-router-flux@3.38.0

**Comment by shettyrahul8june** [comment] 2017-04-21 06:27
It's not related to yarn I believe. Because even if I install it with npm I get the same issue. I deleted my node_modules folder and cleared the npm cache, but the issue was persistent. Currently, I went ahead with a workaround which I read on a GitHub issue where I have to delete the **node_modules/react-native-router-flux/node_modules/react-native** package. I hope they fix this issue soon.

**Comment by Tonacatecuhtli** [comment] 2017-04-21 07:09
same here

**Comment by lahaxearnaud** [comment] 2017-04-21 08:01
Waiting for the fix I rollback to the react-native-router-flux@3.30.1

**Comment by joalisson** [comment] 2017-04-21 08:16
same here

**Comment by otech47** [comment] 2017-04-21 13:11
Got wrecked by this too. Fixed with the rollback to 3.38.0

```
watchman watch-del-all
rm -rf node_modules && npm install
npm uninstall react-native-router-flux
npm install --save react-native-router-flux@3.38.0
rm -fr $TMPDIR/react-*
npm cache clean
npm start -- --reset-cache
```

**Comment by uncledent** [comment] 2017-04-21 17:18
Same by me, had to remove the react-native directory inside react-native-router-flux manually to make things work.

**Comment by nonotest** [comment] 2017-04-21 19:54
yep, either rollback or remove the folder manually, thanks for the workarounds

**Comment by jasan-s** [comment] 2017-04-23 00:36
Hope the problem is resolved in next release.

**Comment by minhcasi** [comment] 2017-04-25 08:55
same issue, please help to fix

**Comment by wcandillon** [comment] 2017-04-26 07:17
Rolling back to 3.38.0 fixed the issue for me, thanks a lot guys!

**Comment by lrnlyra** [comment] 2017-04-26 09:23
Same here, back to 3.38.0 fixed it. Thank you!

**Comment by davidhenley** [comment] 2017-04-26 16:59
+1

**Comment by jamesjara** [comment] 2017-04-27 07:20
thanks!

**Comment by QuantumInformation** [comment] 2017-04-27 10:15
I'll get the champagne ready!

**Comment by jaimecorrea** [comment] 2017-04-27 19:03
Same issue, solved rolling back to 3.38.0

**Comment by prtkkmrsngh** [comment] 2017-04-28 08:20
Rolling back to **v0.38.0** or just deleting the react-native folder inside **react-native-router-flux/node_modules/** will work for now.

**Comment by eneskaya** [comment] 2017-04-28 12:06
Posting the above for convenience copy & paste 😄 

```
watchman watch-del-all && rm -rf node_modules && npm install && npm uninstall react-native-router-flux && npm install --save react-native-router-flux@3.38.0 && rm -fr $TMPDIR/react-* && npm cache clean && npm start -- --reset-cache 
```

**Comment by fewspider** [comment] 2017-04-29 07:04
stuck just now，thanks

**Comment by philjoseph** [comment] 2017-05-04 13:58
+1

**Comment by aolowude** [comment] 2017-05-04 16:52
What worked for me was this sequence:

watchman watch-del-all
rm -rf node_modules && npm install
npm uninstall react-native-router-flux
npm install --save react-native-router-flux@3.38.0
rm -fr $TMPDIR/react-*
npm cache clean
npm install --save react@16.0.0-alpha.6
npm start -- --reset-cache

**Comment by harshattray** [comment] 2017-05-09 05:46
Tried all the above steps and the errors went away but the router doesnt and scenes donot render the components. Double checked if they are being fetched properly and they are . Not sure why

**Comment by geecurve** [comment] 2017-05-10 02:06
Tried command line's fix and this worked to get my build working without errors but when i run my unit tests with jest its complaining it can not find the node_module folders in the react-native-router-flux folder. Looks like jest is still getting a reference to these folders :(
Does anyone know where Jest reference's this from ?

**Comment by prtkkmrsngh** [comment] 2017-05-10 09:20
@geecurve got the same error and nothing `npm cache clean`, `yarn cache clean`, even `rm -rf node_modules` got it working. What I find out that original project directory was dead so created new one with small case. Executed `yarn install` and project was ready to build and test.

**Comment by MattyK14** [comment] 2017-05-10 12:57
@prtkkmrsngh did you delete the react-native folder inside of /node_modules/react-native-router-flux? Or revert to 3.38.0?

**Comment by prtkkmrsngh** [comment] 2017-05-10 13:02
@MattyK14  revert to 3.38.0 and upgraded RN to 0.44

**Comment by nazaslater** [comment] 2017-05-11 16:41
Please guys, 
how to a can resolver this error?

![image](https://cloud.githubusercontent.com/assets/1568961/25961055/47a966b2-364f-11e7-92ed-e2144efc63a1.png)


react-native-router-flux@3.38.1
  ├── lodash.isequal@4.5.0
  ├── UNMET PEER DEPENDENCY react@15.5.4
  ├── react-addons-pure-render-mixin@15.5.2
  ├─┬ react-dom@15.5.4
  │ └── prop-types@15.5.9
  ├─┬ react-native@0.41.2
  │ └─┬ jest-haste-map@18.0.0
  │   ├─┬ fb-watchman@1.9.2
  │   │ └── bser@1.0.2
  │   └── multimatch@2.1.0
  ├─┬ react-native-experimental-navigation@0.26.12
  │ └── clamp@1.0.1
  └── react-static-container@1.0.1

**Comment by Tonacatecuhtli** [comment] 2017-05-11 16:53
fix your version to "react-native-router-flux": "3.38.0", you have 3.38.1

**Comment by nazaslater** [comment] 2017-05-11 19:34
Thanks @Tonacatecuhtli

**Comment by the-simian** [comment] 2017-05-20 07:20
Its been a month, any chance of making the tiny fix that can end this bug?

**Comment by abdurrahmanekr** [comment] 2017-05-20 07:29
@aksonov please fix issue. 3.39.2

**Comment by vitorebatista** [comment] 2017-05-21 15:16
😥

**Closed** 2017-05-26 14:29 UTC

**Comment by watadarkstar** [comment] 2017-05-27 20:51
@abdurrahmanekr @asokol Can we push this into npm its still showing 3.39.1 https://www.npmjs.com/package/react-native-router-flux

**Comment by Silvercast** [comment] 2017-05-28 14:01
it's 3.39.2 now
