### ISSUE TITLE
Strange behavior for drawerOpen

### ISSUE THREAD

**Issue by soulwu** [aksonov/react-native-router-flux#2058] opened 2017-07-18 09:38 UTC
I put a scene with drawer under scene with tabs. But after drag open the drawer and close it, a new screen of the drawer's children was pushed in by mistake.

my Router and Scene config like below
```js
<Router createReducer={reducerCreator}>
  <Scene key="lightbox" lightbox>
    <Scene key="modal" modal>
      <Scene key="root" hideNavBar>
        <Scene key="detail" back title="FundDetail">
          <Scene key="_detail" component={DetailScreen} />
        </Scene>
        <Scene key="welcome" component={WelcomeScreen} initial />
        <Scene key="tabbar" tabs hideNavBar gesturesEnabled={false}>
          <Scene key="profile" component={ProfileScreen} hideNavBar />
          <Scene key="home" drawer contentComponent={LeftDrawer} hideNavBar>
            <Scene key="_home" component={HomeScreen} hideNavBar />
          </Scene>
        </Scene>
      </Scene>
      <Scene key="login" component={LoginScreen} title="login" leftTitle="cancel" onLeft={Actions.pop} />
    </Scene>
  </Scene>
</Router>
```

![drawer](https://user-images.githubusercontent.com/1633638/28310682-d3f5bfd8-6bdf-11e7-9350-0ff6f228040c.gif)

**Comment by soulwu** [comment] 2017-07-18 09:41
I print the state diff in reducer, I think the problem could be the second DrawerOpen action, also maybe a bug for react-navigation?
![image](https://user-images.githubusercontent.com/1633638/28310808-3070ad2c-6be0-11e7-96e0-224a0746b457.png)

**Comment by aksonov** [comment] 2017-07-18 10:58
Drawer should be parent for tabs, check Example project.

**Comment by soulwu** [comment] 2017-07-18 12:50
@aksonov Drawer must be parent for tabs? But how can I make Drawer only enabled while user switch to Home tab?

**Comment by aksonov** [comment] 2017-07-18 18:34
Maybe it is issue of ReactNavigation. Please create pure React Navigation project and check. Also you may try to reproduce the issue with Example project from this component.

**Comment by aksonov** [comment] 2017-07-25 12:35
Closing it because didn't receive cloned and modified Example to reproduce.

**Closed by aksonov** 2017-07-25 12:35 UTC
Labels: needs response from author
