### ISSUE TITLE
[v3.26.1] Drawer Button don't display

### ISSUE THREAD

**Issue by mnadbader** [aksonov/react-native-router-flux#710] opened 2016-05-20 14:29 UTC
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

- react-native-router-flux v3.26.1
- react-native v0.26.0

### Actual behaviour

The drawer button didn't display. I have made the nav bar style transparent and i see the button but i can't press it because he is overrided by the title.

### Steps to reproduce

1.Make scenes with drawer

**Comment by mnadbader** [comment] 2016-05-20 14:58
I'm debugging the package and i have deleted the heade style position:'absolute', and i founded that the navbar is duplicated. See attached pic.
And we can see that the title hide a part of the drawer image.

![sans titre 2](https://cloud.githubusercontent.com/assets/17679530/15431819/d4862776-1eab-11e6-88f4-16305904dbd0.jpg)

**Comment by charpeni** [comment] 2016-05-20 15:01
Thanks for the screenshot.

FYI : It should be Accueil and not Acceuil :)

**Comment by mnadbader** [comment] 2016-05-20 15:04
yes a typo mistake  :) thx

**Comment by mnadbader** [comment] 2016-05-20 15:09
i founded a solution by addind type='reset' in  homeDrawer scene and main scene

**Comment by joenoon** [comment] 2016-05-21 02:01
@mnadbader is this solved? The Example app has a working drawer.  I'm wondering if you need to set titleStyle to prevent it from obstructing the left button - but just a guess.

**Comment by mnadbader** [comment] 2016-05-21 09:46
the issue is that i have a duplicated navbars.  i debugued the component and i have elminated the issue by checking if hidenave=true to return null in render function of navbar. So i suggest that there's a bug whit navbar in this version.

**Comment by joenoon** [comment] 2016-05-21 15:54
@mnadbader It looks like if hideNavBar (now an inherited value) resolves to true that the NavBar component should never be rendered: https://github.com/aksonov/react-native-router-flux/blob/2d84f885a6723d3a0dfba18a4db6554e6260581f/src/DefaultRenderer.js#L144

Can you check against the Example app and see if theres a bug you can reproduce so I can take a look?  

I my guesses would be you might need to set these to `true` in an outer scene: `<Scene key="root" hideNavBar={true} hideTabBar={true}>`.  Or you might need to make use of getSceneStyle as shown in the Example.  If its the first fix, then I wonder if thats something that the library could do automatically... let me know and we'll go from there.

**Comment by wzywno** [comment] 2016-05-25 10:53
@mnadbader  Hi, I have a problem with SideDrawer implementation for RN 0.26.2.
Can you share how body of your ```class SideDrawer extends Component {}``` looks?

**Comment by reddingit** [comment] 2016-05-31 03:53
I solve this problem by add some code at render() function in NavBar.js, see below:
![qq20160531-0](https://cloud.githubusercontent.com/assets/5533582/15662730/2e126fd4-2726-11e6-880b-4b9469d21dfd.png)

**Comment by aksonov** [comment] 2016-06-08 07:22
Please check latest version, closing it for now.

**Closed by aksonov** 2016-06-08 07:22 UTC
Labels: bug
