### ISSUE TITLE
`No current Router is set` issue

### ISSUE THREAD

**Issue by yuilsang** [aksonov/react-native-router-flux#223] opened 2016-02-18 12:18 UTC
Problem. 
1. Use `sceneConfig={Navigator.SceneConfigs.FloatFromBottom}` (Redux)
2. If you pop through a gesture, when the following acts 'No current Router is set' error
3. The same problem occurs in the demo

How do you solve?

**Comment by Elyx0** [comment] 2016-02-18 20:27
Same issue, no idea.

**Comment by aksonov** [comment] 2016-02-19 08:00
It looks the same as #197 - currently React Native doesn't allow to override actions for SceneConfigs. So you could implement your own animations and own gestures but don't use Navigator's gestures (you could disable them easily).

**Comment by aksonov** [comment] 2016-02-19 08:02
You may vote for product pain: https://productpains.com/post/react-native/override-swipe-back-behavior/

**Comment by aksonov** [comment] 2016-02-19 08:06
it is duplicate of #197, closing this ticket

**Closed by aksonov** 2016-02-19 08:06 UTC

**Comment by jamesone** [comment] 2016-03-30 05:08
Has this been fixed in 2.x? I cannot update to v 3 as I have dependencies for other packages that require a lower RN version.

**Comment by aksonov** [comment] 2016-03-30 07:34
@jamesone It cannot be fixed in v2. You could disable swipe only (search other issues)
