### ISSUE TITLE
Cannot find element for parent=SCENE_NAME within current state

### ISSUE THREAD

**Issue by jeroenbourgois** [aksonov/react-native-router-flux#370] opened 2016-03-22 15:49 UTC
Hi

I have the following Router setup

```
      <Router>
        <Scene key="modal">
          <Scene key="preloader" hideNavBar={true}  component={Preloader} initial={true}  title="Preloader" />
          <Scene key="login" component={Login} />

          <Scene key="sidemenu" component={SideMenu}>
            <Scene key="welcome" component={Welcome} title="Welcome" />
            <Scene key="home" component={Home} title="Home" />
          </Scene>
        </Scene>
      </Router>
```

When calling `Actions.welcome()` on another page, I get something like:

`Cannot find element for parent=sidemenu within current state`

I think I am doing something wrong with the nesting (`SideMenu` is a `Drawer` component) but cannot figure out what I am missing.

Thank you for this wonderful component!

**Comment by aksonov** [comment] 2016-03-22 16:52
SideMenu should have single child, Scene container. Please try to reproduce the issue on component Example. Also you could try to debug by printing state within Reducer - reducer cannot find parent of 'welcome' action for some reason.

**Comment by jeroenbourgois** [comment] 2016-03-23 13:55
Hi, I updated my code so that the SideMenu has a single child and I added the reducer. Still the same error, this is the output:
```
REDUCER -> ACTION: Object {type: "RootContainerInitialAction"}
REDUCER -> ACTION: Object {key: "home", type: "push"}
ACTION_CLICK -> Failed AssertionError {name: "AssertionError", actual: undefined, expected: true, operator: "==", message: "Cannot find element for parent=main within current…pe":"push","key":"0_preloader"}],"key":"0_modal"}"…}
```

This is my current router:
```
<Router createReducer={reducerCreate}>
        <Scene key="modal" hideNavBar={true}>
          <Scene key="login" type="replace" component={Login} title="Inloggen" />
          <Scene key="welcome"  hideNavBar={true} component={Welcome} title="Welcome" />
          <Scene key="preloader" hideNavBar={true} component={Preloader} initial={true}  title="Preloader" />

          <Scene key="sidemenu" component={SideMenu}  title="ballekes">
            <Scene key="main" navBar={NavBar}>
              <Scene key="home" component={Home} title="Home" />
            </Scene>
          </Scene>
        </Scene>
      </Router>
```

For now I can bypass the issue by letting the action call `sidemenu` but then the animation let's the sidemenu slide out real fast :) bit weird.

Thanks for your efforts

**Comment by aksonov** [comment] 2016-03-23 14:01
Could you modify Example project to reproduce the issue?

**Comment by jeroenbourgois** [comment] 2016-03-23 14:03
Ok, I will do it asap. Meanwhile I dropped two minor PR's ;) I am not super technical so it are two documentation updates, but hey, my way of helping out, appreciate your feedback on my issues so I need to give something back :)

**Comment by aksonov** [comment] 2016-03-23 14:06
You may also print state returned from defaultReducer to understand why it cannot find parent...

**Comment by jeroenbourgois** [comment] 2016-03-23 20:52
Ok, I can reproduce with the Example project. Modification is very easy:

Change line 14 that says
```
<Button onPress={Actions.register}>Go to Register page</Button>
```

To (the change is the actions, where I want to trigger a nested view like 'loginModal', which is similar what I was doing:

```
<Button onPress={Actions.loginModal}>Go to Register page</Button>
```

Then the same error is thrown.

**Comment by spaceoi** [comment] 2016-03-24 06:29
Got the same error.

**Comment by slamus** [comment] 2016-03-25 09:18
I've got the same error.
I've got around it by setting `initial={true}` to my equivalent of my 'welcome' route.
Then I just need to call the parent route to go to this this route.

```
      <Router createReducer={reducerCreate}>
        <Scene key="root" hideNavBar={true} component={MainContainer}>

          <Scene
            key="Login"
            type="replace"
            component={LoginPageContainer}
            initial={true}
          />
          <Scene
            key="ProfileCompleteness"
            type="replace"
            component={ProfileCompletenessPageContainer}
          />

          <Scene
            key="Platform"
            type="replace"
            component={PlatformContainer}
          >
            <Scene
              key="Lobby"
              type="replace"
              initial={true}
              component={LobbyPageContainer}
            />
            <Scene
              key="PageTest"
              type="replace"
              component={PageTestContainer}
            />
            <Scene
              key="Profile"
              type="replace"
              component={ProfilePageContainer}
            />
            <Scene
              key="EditProfile"
              type="replace"
              component={EditProfilePageContainer}
            />
            <Scene
              key="Friends"
              type="replace"
              component={FriendsPageContainer}
            />
            <Scene
              key="AboutUs"
              type="replace"
              component={AboutUsPageContainer}
            />
            <Scene
              key="Show"
              type="replace"
              component={ShowPage}
            />
          </Scene>


        </Scene>
      </Router>

```

**Comment by aksonov** [comment] 2016-03-25 12:20
So you want to go inside tabs container (i.e jump + push) ? Is it duplicate of #350 ?

**Comment by jeroenbourgois** [comment] 2016-03-27 21:40
Not not that I know. I just want to navigate directly to a route inside my sidemenu (drawer). It also has a key but I cannot access keys inside. This does not really seem like push jump? When using the example I get the same error

**Comment by gustavovnicius** [comment] 2016-03-30 02:34
@aksonov I've found something that I dont know if it is correct:

My Scenes are configured like this:
![screenshot from 2016-03-29 23-26-28](https://cloud.githubusercontent.com/assets/2379486/14129999/adf40be2-f605-11e5-8ff0-bacd914a30b6.png)

And...
![screenshot from 2016-03-29 23-23-27](https://cloud.githubusercontent.com/assets/2379486/14129964/671051ae-f605-11e5-97c9-25f69dc5cbbe.png)

This is a log from Reducers.js:17, note that only the "login" scene is on children, and at Reducers.js:20 it iterates on children. The "drawer" scene shouldn't be listed there too? Looking at the code, I'm wondering if this could solve the problem because at Reducers.js:20 it iterates on state.children, if the children tree was complete, it would have found the correct scene (I am calling  "Actions.content()" inside the "login" scene). Am I wrong?

**Comment by aksonov** [comment] 2016-03-30 07:36
@gustavovnicius Good catch! Looks like you are right, Reducer should iterate also over 'scenes' where all scenes are stored.

**Comment by aksonov** [comment] 2016-03-30 07:43
@gustavovnicius However Drawer should have only one child, check example.

**Comment by jeroenbourgois** [comment] 2016-03-30 08:08
@gustavovnicius even without modifying the Example a lot you can reproduce the bug. Just calling a nested Scene already triggers the error. I will try to investigate that as soon as I have the time.

**Comment by aksonov** [comment] 2016-03-30 08:13
@jeroenbourgois Actually it is not error. You are requesting from component several actions at once (jump + push). So it could be good enhancement, yes, but not error.

**Comment by jeroenbourgois** [comment] 2016-03-30 08:17
@aksonov ah ok. I did not realize that I was doing multiple actions, since I called only one action. So that might solve my inital problem too, but then when I would press 'back' it would go back to the intermediate route which I never wanted to access anyway...

Like in the Example, when I am on the `register` page and I want to go to `loginModal2`, I should have two actions, one to go to `login` and then to `loginModal2`. But when I press back, will I go to `register`? Probably not, but `Login` instead

**Comment by aksonov** [comment] 2016-03-30 08:19
We have ‘clone’ property now for such cases (to run some screen from different locations). You could define such screen at root level with clone attribute and then call it where you want.

**Comment by gustavovnicius** [comment] 2016-03-30 13:40
> @gustavovnicius However Drawer should have only one child, check example.

I didn't understood why... For me it should have as many as needed.

**Closed** 2016-04-26 07:50 UTC

**Comment by yeomann** [comment] 2018-06-25 13:29
`However Drawer should have only one child, check example ` just to let people know who are still encountering issue, the thing is in drawer scene create a scene with no component={} and then give as many Childs you want to that parent. which is actually a single child of the drawer as statement says that `Drawer should have only 1 child`
