### ISSUE TITLE
HotReload not working as expected

### ISSUE THREAD

**Issue by danielbenedykt** [aksonov/react-native-router-flux#2224] opened 2017-08-12 14:02 UTC
### Version

- react-native-router-flux v4.0.0-beta.16
- react-native 0.46.1

### Expected behaviour

Using hot reload, every time some code changes, the router should re-render but stay at the current selected scene.

### Actual behaviour

When the router gets re-rendered it doesn't honours the current rendered scene and/or route in the store. It dispatches a focus action for the the initial Scene.

### Steps to reproduce
For non-obvious bugs, please fork this component, modify Example project to reproduce your issue and include link here.
1. Create at least 2 scenes
2. Navigate to a non initial screen
3. Make any change to that screen or related component
4. It will hot reload, but it will go back to the initial screen

**Comment by aksonov** [comment] 2017-08-14 09:52
Duplicate of https://github.com/facebook/react-native/issues/13240 
I will convert Example project screens to classes.

**Closed by aksonov** 2017-08-14 09:52 UTC
