### ISSUE TITLE
Can't change backgroundColor of the app.

### ISSUE THREAD

**Issue by Amin52J** [aksonov/react-native-router-flux#2039] opened 2017-07-15 14:41 UTC
I'm using **react-native-router-flux** version **4.0.0-beta.11** and been trying to change the backgroundColor of the app in a variety of methods suggested over the internet but unfortunately none worked and the background is always the default gray color. The things I tried are listed below:

- passing a function that returns a style to `getSceneStyle` prop of the Router component
- passing a style object to `sceneStyle` prop of the Scene component
- wrapping the Router component inside a View element and styling the View

I also tried logging something inside the function passed to `getSceneStyle` prop but doesn't seem to fire.

here's my actual code:

    export default class App extends React.Component {
      render() {
        return (
          <Provider store={store}>
            <Router navigationBarStyle={{backgroundColor:theme.primary}}
                    barButtonTextStyle={{color:theme.secondary}}
                    barButtonIconStyle={{tintColor:theme.secondary}}
                    titleStyle={{color:theme.secondary}}>
              <Scene key="root">
                <Scene key="home" component={TodoListApp} title={texts.todoListTitle}/>
              </Scene>
            </Router>
          </Provider>
        );
      }
    }

**Comment by aksonov** [comment] 2017-07-15 14:43
Looks like duplicate of #2033

**Closed by aksonov** 2017-07-15 14:43 UTC
