### ISSUE TITLE
Custom title not centered on Android after upgrade to 4.0.1

### ISSUE THREAD

**Issue by pehagg** [aksonov/react-native-router-flux#3207] opened 2018-08-24 05:52 UTC
### Version
Tell us which versions you are using: 

- react-native-router-flux v4.0.1
- react-native v0.56
- os Android

### Expected behaviour

Title should be centered.

### Actual behaviour

The title used to be centered before upgrading from 4.0.0-beta.27 to 4.0.1. Title aligns to the left, next to the back button. Using titleStyle that centers the component doesn't help. Removing the renderRightComponent view required for centering the title on Android didn't help either.

This is the style definition for the title component:

```
const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
});
```

**Comment by daviscabral** [comment] 2018-08-24 06:01
This seems to be related to the `react-navigation@2` upgrade. 

Checking the link below, it seems now they have a `headerLayoutPreset` prop to manage that. That's not supported yet and will have to add it to the list.

https://github.com/react-navigation/react-navigation/pull/4588
https://github.com/react-navigation/react-navigation/issues/4615

**Comment by pehagg** [comment] 2018-08-24 06:09
Was able to fix this by adding `flex: 1` to the style definition of the custom title component. Got inspiration from https://github.com/react-navigation/react-navigation/issues/544. Using titleStyle doesn't seem to have any effect. Closing issue.

**Comment by daviscabral** [comment] 2018-08-24 11:28
I'll keep this opened since it was a existent feature that is not working anymore and probably will be an easy fix.

**Comment by aksonov** [comment] 2018-09-06 07:20
Duplicate of #3153

**Closed by aksonov** 2018-09-06 07:20 UTC
Labels: enhancement
