### ISSUE TITLE
hideTabBar sometimes doesn't work

### ISSUE THREAD

**Issue by luco** [aksonov/react-native-router-flux#2076] opened 2017-07-20 14:27 UTC
Im having this issue. `hideTabBar` sometimes does and sometimes does not work.
On my app, for example, the messages inner view does hide the tabBar while the profile doesn't.

```
<Scene key="tabbar" 
              tabs
              tabBarComponent={this.tabBarElement.bind(this)}
               >

                  <Scene key="home" title="Home">
                    <Scene key="homeMain" title="Home" component={Home} />
                    <Scene key="profile" title="Profile" component={UserProfile}  hideTabBar={true} />
                  </Scene>

                  <Scene key="messages" >
                          <Scene key="messagesMain" title="Messages" component={Messages}/>
                          <Scene key="messageView" component={Message}  hideTabBar={true} />
                        </Scene>
```

Tips?

**Comment by aksonov** [comment] 2017-07-20 14:30
Duplicate of #2012 ? It seems ReactNavigation has issues with TabBar...

**Comment by luco** [comment] 2017-07-20 15:01
@aksonov Figured it out.

I was importing NavBar:
`import {Actions, NavBar} from 'react-native-router-flux';`

Removing fixed it. Should I submit a PR to Docs to specify that `hideTabBar` will only work if NavBar is not imported?

**Comment by aksonov** [comment] 2017-07-20 15:08
Hm, I can't find correlation between null NavBar - v4 doesn't export it anymore and `hideTabBar` option... Are you sure that you didn't use that empty NavBar anywhere (so it could broke things) ?

**Comment by luco** [comment] 2017-07-20 17:51
Not that I remember. Just removing it fixed.

**Closed** 2017-07-20 20:35 UTC
