### ISSUE TITLE
Performance in android

### ISSUE THREAD

**Issue by albo1337** [aksonov/react-native-router-flux#441] opened 2016-03-31 14:07 UTC
I don't know what I'm doing bad, but if I do this:

```
const scenes = Actions.create(
  <Scene key="root">
      <Scene key="tabbar" component={TabBar} tabs={true}>
          <Scene key="homeTab" title="Home" icon={TabIcon}>
              <Scene key="home" component={Home} title="Home"/>
              <Scene key="login" component={Login} title="Login"/>
          </Scene>
      </Scene>
  </Scene>
);

export default class Example extends React.Component {
    render() {
        return (
            <Router createReducer={reducerCreate} sceneStyle={{backgroundColor:'#F7F7F7'}} scenes={scenes}/>
        )
    }
}
```
the performance on android is really bad. If I switch a view it takes 10 seconds until it switches. I've tested this with several devices.

In iOS this issue is not occuring...

Could you help me pls?

best regards,

albo

**Comment by aksonov** [comment] 2016-03-31 14:17
duplicate of #355

**Closed by aksonov** 2016-03-31 14:17 UTC

**Comment by albo1337** [comment] 2016-03-31 14:23
Allright, so Navigation is useless on react native android?

**Comment by aksonov** [comment] 2016-03-31 14:30
So far, yes. You may try v2 version for Android.
