### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by BipinBhandari** [aksonov/react-native-router-flux#772] opened 2016-06-03 04:25 UTC
### Version
Tell us which versions you are using (react native 0.26 is required for v3): 

react-native-cli: 0.2.0
react-native: 0.26.2

- react-native-router-flux v3.?.?
- react-native v0.?.?

### Expected behaviour
I was expecting the example app would run.

### Actual behaviour
<img width="372" alt="screen shot 2016-06-03 at 10 09 32 am" src="https://cloud.githubusercontent.com/assets/5967448/15768728/4ced3d68-2973-11e6-9b16-137f67529a55.png">

### Steps to reproduce

1. git clone https://github.com/aksonov/react-native-router-flux.git
2. npm install
3. react-native run-ios

**Comment by cridenour** [comment] 2016-06-03 15:36
I believe you need to cd to Example to run it. Can you try and report back?

**Comment by aksonov** [comment] 2016-06-08 07:12
I can't reproduce, closing it.

**Closed by aksonov** 2016-06-08 07:12 UTC
