### ISSUE TITLE
renderRightButton gets hidden by the nav bar on 3.2.2

### ISSUE THREAD

**Issue by SudoPlz** [aksonov/react-native-router-flux#398] opened 2016-03-25 21:07 UTC
Ok I kept researching and I found out that the button WAS indeed rendered but it it is rendered BEHIND the nav bar.. Like so: 
![screen shot 2016-03-25 at 22 04 11](https://cloud.githubusercontent.com/assets/3070948/14052817/a0559fba-f2d5-11e5-9eb7-e77ccb0dc362.png)

Thats my code: 

      class ARightBtn extends React.Component {
          render(){
              return <Text style={{
                width: 80,
                position: 'absolute',
                height: 120,
                width: 200,
                top: 50,
                right:0,
                padding: 8,
                backgroundColor: 'red',
                color: '#000000'
            }}>RightBtnTest</Text>
          }
      }
and then I use it like so:

    <Scene key="EmailSignIn" title="Sign In" type="push" hideNavBar={false} titleStyle={{color:Colors.mainTextColor}} renderRightButton={()=><ARightBtn/>} initial={true} >
        <Scene key="EmailSignIn1" component={EmailSignIn} title="Sign In" navigationBarStyle={{backgroundColor:Colors.primaryColor}} renderRightButton={()=><ARightBtn/>}  />
        <Scene key="EmailSignIn2" component={Onboarding} title="Sign In"/>
    </Scene>

What can I do @aksonov ?

**Comment by aksonov** [comment] 2016-03-26 07:21
Please modify Example accordingly to show the bug. From your sources is it not clear - it could be parent navbar that hides children one.

**Comment by aksonov** [comment] 2016-03-27 07:32
Closing it until you give me Example modification.

**Closed by aksonov** 2016-03-27 07:32 UTC

**Comment by SudoPlz** [comment] 2016-03-28 13:52
Please reopen the issue, here is the example modification. 
The SAME exact issue happens on the example, here is a photo:

<img width="220" alt="screen shot 2016-03-28 at 16 52 23" src="https://cloud.githubusercontent.com/assets/3070948/14079333/7ab643cc-f505-11e5-9d2d-f5d7fd1dddb1.png">

https://github.com/SudoPlz/react-native-router-flux/blob/master/Example/Example.js

**Comment by aksonov** [comment] 2016-03-29 07:51
I can't reproduce it with latest version (3.2.4), it is shown above nav bar correctly.

**Comment by SudoPlz** [comment] 2016-04-08 10:19
We are now in 3.2.7 but I still can't render a button on the nav bar.
I just slightly [modified the example](https://github.com/SudoPlz/react-native-router-flux/blob/master/Example/Example.js) to also render a button in the login and register screen of the example but the button is not rendered.. 

In fact during the transition I can see the button of the login screen below the main bar. Would you mind reopening the issue please?

**Comment by amitbobade2007** [comment] 2016-04-11 13:29
@aksonov i am getting this issue in 3.2.8 for Scenes inside Drawer. Not able render right button with default navbar or custom navbar.

**Comment by amitbobade2007** [comment] 2016-04-12 08:35
@aksonov renderRightButton function is not gets assigned in Componentwillmount method. Instead of receiving renderRightButton/renderLeftButton/renderBackButton from this.props.navigationState, receiving from this.props.

**Comment by SudoPlz** [comment] 2016-04-12 09:02
It has something to do with a parent navbar overlapping the child, if you use the renderRightButton on the root schene with no other schenes it always works!
